### ISSUE TITLE
Passing in additional classes

### ISSUE THREAD

**Issue by time4tea** [react-bootstrap/react-bootstrap#101]
Much similar to #95 but for panels and buttons, the following doesn't seem to work. Is that by design? 

```
<Panel className="bob" header="Header" bsStyle="success">

</Panel>
```

different to the GlyphIcon, here transfer props to isn't used, by the looks of it.
same goes for button.

Thanks!

James

**Comment by promethe42** [comment]
I think the issue still exists for the Nav component:

```
var Header = React.createClass({
    render: function()
    {
		return (
            <div id="header">
                <Navbar>
    		    	<NavBrand>cocorico</NavBrand>
                    <Nav className="pull-right">
    					<NavItem eventKey={1} href="#">Link</NavItem>
    					<NavItem eventKey={2} href="#">Link</NavItem>
    			    </Nav>
    		  	</Navbar>
            </div>
		);
	}
});
```

doesn't work as expected.

**Comment by taion** [comment]
`Nav`'s classes apply to the `<nav>`, not the `<ul>`. Use the `pullRight` prop there.

**Comment by taion** [comment]
And next time check the docs first - this is all clearly shown there.

**Comment by darkalghul** [comment]
<NavDropdown title="Dropdown" id="collasible-nav-dropdown">
        <NavDropdown.Item href="#action/3.1">Action</NavDropdown.Item>
</NavDropdown>

The NavDropdown create a div element and inside that element create a link tag with the following properties:
<a aria-haspopup="true" aria-expanded="false" href="#" class="dropdown-toggle nav-link" role="button">Dropdown</a>

How do I add a Font Awesome icon and a span tag instead of the text, also how do I add more classes to the link tag additional to the "dropdown-toggle nav-link" classes?
