### ISSUE TITLE
React 0.14 Parent Contexts vs. Portals and Modals

### ISSUE THREAD

**Issue by epferrari** [react-bootstrap/react-bootstrap#1097]
It seem with React 0.14 as the contexts API becomes stable, the React team is going to be moving away from owner-contexts in favor of parent-contexts. See [discussion here](https://gist.github.com/jimfb/0eb6e61f300a8c1b2ce7) and an explanation of owner vs. parent [here](http://facebook.github.io/react/docs/multiple-components.html). Now, whether or not I personally think this is a logical shift (and I don't), it's happening, which means our context is no longer going to be defined by the composite components we create, but follows the DOM tree instead. As I understand it, soon rendering through a portal to another part of the DOM going to break the contextual relationship we are trying to create across our application, and it's not immediately clear (to me anyway) how to pass that context a) through a portal, and b) through a portal that's used internally by bootstrap overlays and modals.

Has anyone else come across similar issues while building composite components that rely on contexts?

**Comment by jquense** [comment]
You might be slightly misunderstanding 'parent based context' it is still composite component based (vs DOM tree based) but instead of being tied to the componet that created the sub element it is inherited from the component that actually renders that subelement. In most cases this won't break any existing code, since children are almost always rendered as a subcomponent of both the owner, and the parent. 

The one use case, as you note, that does break is Portals/Overlays, luckily along with parent based contexts React `0.14` also adds [`renderSubtreeIntoContainer()`](https://github.com/facebook/react/blob/master/src/renderers/dom/ReactDOM.js#L40) specifically to address this.

**Comment by taion** [comment]
Whatever you do, don't make the mistake I did and create a horrible hacky workaround just to squelch the React v0.13 error messages.

**Comment by epferrari** [comment]
What, did you overwrite console.warn to ignore those pesky warnings? Don't think
I haven't considered it!
Jason, I'm understanding the parent contexts alright. it's just to me it makes
sense that context comes from the owner it's called from rather than where it
ends up nesting. But I'm not Facebook, in talent or in ability to shape this so
that point is moot.
However, renderSubtreeIntoContainer doesn't appear to be handling the context
passing, or more likely I'm doing it wrong, although my implementation matches
the (very sparse) documentation available on it. I'll post a sample here in the
morning, maybe someone can point out where I'm going astray.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Fri, Jul 31, 2015 at 11:06 PM, Jimmy Jia <notifications@github.com> wrote:
Whatever you do, don't make the mistake I did and create a horrible hacky
workaround just to squelch the React v0.13 error messages.

—
Reply to this email directly or view it on GitHub
[https://github.com/react-bootstrap/react-bootstrap/issues/1097#issuecomment-126858304] .[https://github.com/notifications/beacon/AGvKVswUiAIdsJCtQZLkziaytyGO9ZVEks5ojD1fgaJpZM4Fj4H-.gif]

**Comment by jquense** [comment]
there isn't likely to be any good docs yet since it's still in beta, but you can search around the react issues for more info.  I can say with certainty that the reason it was added was to address portals specifically. I can't really offer support for it tho because we don't support 0.14, and don't plan on it until 0.14 hits a proper release.

**Comment by epferrari** [comment]
Understandable. Thanks for your prompt feedback on this issue, Jason.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Fri, Jul 31, 2015 at 11:32 PM, Jason Quense <notifications@github.com> wrote:
there isn't likely to be any good docs yet since it's still in beta, but you can
search around the react issues for more info. I can say with certainty that the
reason it was added was to address portals specifically. I can't really offer
support for it tho because we don't support 0.14, and don't plan on it until
0.14 hits a proper release.

—
Reply to this email directly or view it on GitHub
[https://github.com/react-bootstrap/react-bootstrap/issues/1097#issuecomment-126861466] .[https://github.com/notifications/beacon/AGvKVpsSUwQN74meDPodaz_4iPJLwYS1ks5ojENdgaJpZM4Fj4H-.gif]

**Comment by taion** [comment]
Fixed in #1153.
