### ISSUE TITLE
Feature request: LeftTabs component

### ISSUE THREAD

**Issue by kennyw12** [react-bootstrap/react-bootstrap#1111]
We want to create Tabs that look like this:

![simple left tabs](https://cloud.githubusercontent.com/assets/1689040/9094273/b11e42ca-3b65-11e5-85c4-d46f3d61a949.png)

and this:

![complicated left tabs](https://cloud.githubusercontent.com/assets/1689040/9094287/c20f411a-3b65-11e5-8b4c-2373f40163bf.png)

Here's the HTML/CSS for the [top component (simple left tabs)](http://jsbin.com/mosagifaxu/1/edit?html,output) and for the [bottom component (complicated left tabs)](http://jsbin.com/yosohavumo/edit?html,output)

Would you be open to a new component - `LeftTabs` - that could build these two examples? Here's what we think the API could look like:

Simple left tabs:

```jsx
<LeftTabs defaultActiveKey={1} navWidth={2}>
  <Tab title="meep">Content 1</Tab>
  <Tab title="foo">Content 2</Tab>
  <Tab title="bar">Content 3</Tab>
  <Tab title="baz">Content 4</Tab>
</LeftTabs>
```

Complicated left tabs:

```jsx
<LeftTabs defaultActiveKey={1} navHeader="Service Plans" contentHeader="Plan Features" navWidth={4}>
  <Tab title={<Row>
      <Col xs={5} className="tab-title">Spark</Col>
      <Col xs={7}>Free</Col>
    </Row>}>Content 1</Tab>
  <Tab title={<Row>
      <Col xs={5} className="tab-title">Boost</Col>
      <Col xs={7}>$10/month</Col>
    </Row>}>Content 2</Tab>
  <Tab title={<Row>
      <Col xs={5} className="tab-title">Amp</Col>
      <Col xs={7}>$50/month</Col>
    </Row>}>Content 3</Tab>
  <Tab title={<Row>
      <Col xs={5} className="tab-title">Shockingly long plan name is important to test</Col>
      <Col xs={7}>$1000/month</Col>
    </Row>}>Content 4</Tab>
</LeftTabs>
```

And of course, we'd make a PR for it :grin: 

The Pivotal UI Team
@atomanyih @ctaymor @gpleiss @kennyw12 @matt-royal @nicw @stubbornella

**Comment by kennyw12** [comment]
This is similar to #469.

**Comment by jquense** [comment]
I think the problem with something like this is that it would require react-boostrap to ship its own stylesheet, in addition to needing the base bootstrap one. While we've definitely gone beyond the feature set of upstream bootstrap, its been in the realm of javascript, and specifically stuff that naturally falls out of reimplementing components in React. Personally I don't want to also be in the business of maintaining css for this project, especially since the upstream styles are so complex.

Others on the team may feel differently though! I would say though that making sure that you have hooks into the current tab component so that LeftTabs could be implemented on top of them, perhaps as seperate npm module, is something we'd be happy to explore.

**Comment by taion** [comment]
Doing this a lot today but I pretty much echo what @jquense said - if we can re-use the CSS from e.g. http://react-bootstrap.github.io/components.html#navs-stacked, then this would be great. It's a lot trickier otherwise, though, since we want to ship something that will work with normal Bootstrap CSS.

**Comment by ctaymor** [comment]
We're only using existing bootstrap CSS on this. We can make them look like the stacked nav if you like:
http://jsbin.com/veneyucaje/edit?html,output

**Comment by taion** [comment]
Very cool. Sounds reasonable to me, then, if it just re-uses existing CSS and glues together something handy. @jquense?

Would it be possible to make this a config option on the `Tabs` component from #1109, or does this work better as a separate `LeftTabs`?

**Comment by ctaymor** [comment]
Yes, was just considering that. How about adding an optional leftNavWidth prop, which takes a number of bs columns. If the prop is provided, it will be left tabs with that width on the nav.

The Pivotal UI Team
@atomanyih @ctaymor @d-reinhold @kennyw12 @matt-royal @nicw @stubbornella

**Comment by taion** [comment]
I'd prefer to have both a `position` in `{'left', 'top'}` prop and a `navWidth` prop, just in case we need to handle more use cases later on.

**Comment by taion** [comment]
Or `tabPosition` or whatever... something along those lines.

**Comment by jquense** [comment]
ahh very cool, I should have looked a bit closer! I think I'm fine with something like this if we are just gluing together existing bootstrap stuff. Although if its just as easy to release it as a separate component perhaps its better to do that and give ya'll a repo to host it in the RB org. If its easy to implement as part of the tabs rewrite though then I don't mind having it in core.

**Comment by ctaymor** [comment]
It's easy to implement as part of the tabs rewrite. We'll get on it, and add it to the existing tabs rewrite PR with @talon's suggestion for the api.

The Pivotal UI Team
@atomanyih @ctaymor @d-reinhold @kennyw12 @matt-royal @nicw @stubbornella
