### ISSUE TITLE
"show" prop on Modal not working

### ISSUE THREAD

**Issue by prashcr** [react-bootstrap/react-bootstrap#1179]
When I set `show` to true, it just crashes with the error below instead of showing a Modal.

[Codepen demo](http://codepen.io/prashcr/pen/NqVbzE)

[Uncaught TypeError: Cannot read property 'firstChild' of undefined in React, React-Bootstrap](http://stackoverflow.com/questions/32048356/uncaught-typeerror-cannot-read-property-firstchild-of-undefined-in-react-rea?noredirect=1#comment52004417_32048356)

**Comment by jquense** [comment]
This is definately due to multiple instances of React. are you aware that you are using the super alpha react 0.14 build in your example? That particular branch/tag isn't going to work with the bower build yet, it bundles react-dom which is including its own copy of react, which is conflicting with the one you have on the page.

cc @taion for future reference we need to externalize react-dom, but for now there isn't a cdn build of it yet.
