### ISSUE TITLE
React-Bootstrap best practice for variable numbers of `input` fields?

### ISSUE THREAD

**Issue by philipwhiuk** [react-bootstrap/react-bootstrap#1206]
In HTML you can provide a series of `input` with the same name, appending `[]` and it would get interpreted by a server-side language like PHP as an array.

So for example:

```
<input type="checkbox" name="myArray[]" />
<input type="checkbox" name="myArray[]" />
<input type="checkbox" name="myArray[]" />
<input type="checkbox" name="myArray[]" checked="checked" />
```

would provide `$_POST['myArray'] = array(false, false, false, true)`

In R-B I tried to do something similar client-side by providing the same ref or the ref with []s following it but I only get the last one. If I do `myArray[1]` .. `myArray[2]` I get all 4, but not as a JS array.

What's the best practice method for this kind of scenario where I don't know how many input fields I'm going to need until runtime.

**Comment by taion** [comment]
That's not "in HTML", that's just how PHP handles it.

If the number of child inputs doesn't change, you can use the new-style `ref` callback per point 3 here: http://facebook.github.io/react/blog/2015/02/24/react-v0.13-rc1.html#new-features and build an array. It's also not the end of the world to e.g. iterate through your refs and filter by name or something.

A more full-fledged way would be to pass down a unique ID or key to each of the children, and either use lifecycle hooks to explicitly register/deregister themselves with the parent, or manage an array in the parent's state with the values of the inputs.

I'm going to close this issue because there's nothing React-Bootstrap-specific here, though.

**Comment by philipwhiuk** [comment]
Thanks for the advice, closing is fine.
