### ISSUE TITLE
Brainstorm possible API Simplifications with parent context

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#1222]
With react 0.14 and proper parent based contexts we have a potential opportunity to do some more interesting API's. In general i think we need to use this feature sparingly, and definately expose it to our users directly. In my experience context works great when you control both the context giver and receiver, and doesn't cause the sort of annoyances that you get with flux/routers using it.

 I can think of a few cases where we have either leaky private api props, or sub-optimal api's due to children needing to be immediate children of a parent component.

First one that jumps out is `ModalHeader` which has a onHide injected in for automatic wiring of the close button. We could rely on context for that, we could also provide something like `Modal.Dismiss` which just wraps `Button` but wires onClick to onHide for the Modal (I do that [here](https://github.com/jquense/react-bootstrap-modal#modaldismiss) it's a nice shortcut).

Another instance (and I think there are a few of these sorts) is `Nav` and `Navbar` where we set the `navbar` prop, this is a bit wonky when the Nav is wrapped in a div, or other parent.

Others I missed? Possibilities? good idea or bad idea?

**Comment by taion** [comment]
:+1:

Almost everywhere where we have "semantic" children that have to get specific things passed to them from parent would be better handled by pulling things down from context.

This would fix just about all of those annoying cases, except for maybe #1181.

**Comment by taion** [comment]
I don't know why I added this to the React v0.14 milestone. We definitely need to do this, but it's not a blocker for an initial React v0.14 release. Sorry!

**Comment by taion** [comment]
#1473

**Comment by mlandalv** [comment]
Another component I can think of is `Tabs` and `Tab` where the use of context would allow for more advanced usages.

My scenario is that I define a couple of specific tabs, e.g. `FooTab`. Amongst other things, they have an `Immutable.List` as prop whose number of items are supposed to be reflected in the tab title (the list is used for other things too). Currently this is not possible - the title prop has to be passed explicitly to `FooTab`. The title `FooTab` passes to the `Tab` component doesn't seem to be used att all.

Initially my FooTab's render looked something like this:
```
let { eventKey, items, ...props } = this.props;
let title = ´Blabla (${items.count()} ex)´;

return <Tab title={title} eventKey={eventKey}>
   other stuff for rendering the items
</Tab>
```
And instead of using the `Tab` component I was planning on using my custom element:

    <FooTab items={fooItems} evenKey={2} />

But that didn't work. It seems like the `Tabs` component certain props to be passed to its children, and if not found they are ignored. So in my case I have to create the title and pass it to my component. The title `FooTab` passes to `Tab` is simply ignored.

**Comment by jquense** [comment]
@mlandalv #1525 ;)
