### ISSUE TITLE
Tabs behavior when activeKey is null

### ISSUE THREAD

**Issue by taion** [react-bootstrap/react-bootstrap#1227]
We currently treat `null` and `undefined` identically for deciding whether a `Tabs` component is controlled: https://github.com/react-bootstrap/react-bootstrap/blob/v0.25.0/src/Tabs.js#L196

Is this what we want, or should we interpret `null` as "controlled, but nothing selected"?

**Comment by jquense** [comment]
I tend to prefer letting `null` indicate no value, vs uncontrolled. react inputs treat `null` the same as undefined but that works because value is a string value, so you can use `''` for "empty". Most components that will be uncontrolled won't have that luxury so `null` is the only good option for an explicit empty value. All that to say thats why I went with allowing null in [uncontrollable](https://github.com/jquense/uncontrollable/blob/master/src/createUncontrollable.js#L47)

**Comment by taion** [comment]
Oh, we should just use uncontrollable here. But as a quick patch, seems like we should make that check be

```js
this.props.activeKey !== undefined
```

then.
