### ISSUE TITLE
Left Tabs shouldn't use `Grid`

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#1276]
The Grid component in the Left Tabs configuration adds a `container` class which has set width's, effectively means the tabs will overflow their parent if the width is less than the bootstrap page width amount. Using it in things like Modals becomes untenable. I don't think we should be using the Grid component, its too prescriptive, either we add padding to offset the row margins, or just let the user handle it.

**Comment by taion** [comment]
Ah shoot. Brain fart on my part. Should it just be a `div`?

**Comment by jquense** [comment]
Probably, yeah. The only reason you'd want the container, is that its padding balances the negative margins on `.row` but I'd just leave that for the user to manage. The other related issue is that `style` and `className` props go to the inner tab element, which makes it hard to undo this (or add padding in the future)

**Comment by taion** [comment]
Looking at this a bit more closely - because I use both `Grid` and `Row` here, the padding all does cancel out. My concern with using e.g. just `Row` is that then the left positioned `Tabs` component wouldn't be correctly usable without being dropped into a `Grid` anyway to make up for the negative margins on `Row`.

I think doing the `Grid` > `Row` wrapping was the only way I could make things work correctly both embedded into an existing grid row and used standalone.

Maybe the right thing to do is to just move `containerProps` from the `Row` to the `Grid`? `id`, `className`, and `style` sit on there.

**Comment by jquense** [comment]
well it'll also work if dropped into a `Col` which will handle margins correctly. I think that leaving the grid will end to more cases of overriding styles (made harder by all the media queries involved) than it helps. I could be way off on that intuition tho

**Comment by taion** [comment]
I really didn't understand Bootstrap grids well enough to have written this code.

Okay, so let's say we do `div` and kill the `Grid` and the `Row`. Would it be appropriate for us to apply clearfix to that wrapping `div`? Things are screwy otherwise.

**Comment by taion** [comment]
I'll do just the `div` for now. Without additional customization, the `Tabs` component will take the full width, so the lack of clearfix shouldn't be an issue unless something weird is happening.

**Comment by taion** [comment]
Nope, that's wrong, I need to `clearfix` the `div` for this not to look strange.
