### ISSUE TITLE
Button in Nav without list

### ISSUE THREAD

**Issue by adjohnson916** [react-bootstrap/react-bootstrap#1404]
Per http://getbootstrap.com/components/#navbar-buttons, I'd expect to be able to put plain buttons in a nav without wrapping in a list element.

But:
```html
<Navbar>
  <CollapsibleNav eventKey={0}>
    <Button>OK</Button>
  </CollapsibleNav>
</Navbar>
```
currently (with `react-bootstrap@0.27.1`) results in:
```html
<div class="navbar-collapse collapse">
  <li><a href="#" class="btn btn-default" role="button">OK</a></li>
</div>
```
whereas I'd prefer simply:
```html
<div class="navbar-collapse collapse">
  <a href="#" class="btn btn-default navbar-btn" role="button">OK</a>
</div>
```
or:
```html
<div class="navbar-collapse collapse">
  <button type="button" class="btn btn-default navbar-btn">OK</a>
</div>
```

A workaround for now is:
```html
<Navbar>
  <CollapsibleNav eventKey={0}>
    <button type="button" className="btn btn-default navbar-btn">OK</button>
  </CollapsibleNav>
</Navbar>
```

**Comment by taion** [comment]
Do we need something like `NavButton` for this?

**Comment by jquense** [comment]
I think the problem here is that its trying to put a Button in a `Nav` which isn't right, the button should just go in the NavBar, is the CollasibleNav the only API for adding `navbar-collapse` to the navbar? If so the problem is the assumption that the "collaspible" part will always be contained in a Nav which isn't the case, it could jsut as easily be a `navbar-form` plain ol Div, a `navbar-{right-left}` etc.

**Comment by taion** [comment]
Covered by #1496
