### ISSUE TITLE
0.26.x npm bug

### ISSUE THREAD

**Issue by schutterp** [react-bootstrap/react-bootstrap#1406]
I recently upgraded to version 0.26.2 and am still on reactjs 0.13. My issue is when I run `npm install`, react 0.14 is installed as a dependency! This is breaking all the things since my code (and react-bootstrap) are expecting react 0.13. The crazy part is that different dependencies are downloaded if I run the same command with the name arg, e.g. `npm install react-bootstrap`, from the exact same state! 

Starting state:
1. All dependencies installed except react-bootstrap, clean npm cache
2. package.json specifies exact version: `"react-bootstrap": "0.26.2"`

run `npm install`
```
react-bootstrap@0.26.2 node_modules/react-bootstrap
├── classnames@2.1.5
├── keycode@2.1.0
├── dom-helpers@2.4.0
├── react-prop-types@0.3.0 (warning@2.1.0)
├── lodash-compat@3.10.1
├── babel-runtime@5.8.25 (core-js@1.2.1)
├── react@0.14.0 (envify@3.4.0, fbjs@0.3.2)
├── uncontrollable@3.1.3 (invariant@2.1.1)
└── react-overlays@0.4.4 (react-prop-types@0.2.2, warning@2.1.0)
```
(return to starting state) run `npm install react-bootstrap`
```
react-bootstrap@0.26.2 node_modules/react-bootstrap
├── classnames@2.1.5
├── keycode@2.1.0
├── dom-helpers@2.4.0
├── lodash-compat@3.10.1
├── uncontrollable@3.1.3 (invariant@2.1.1)
├── react-overlays@0.4.4 (react-prop-types@0.2.2, warning@2.1.0)
├── react-prop-types@0.3.0 (warning@2.1.0)
└── babel-runtime@5.8.25 (core-js@1.2.1)
```
This may be an npm issue but I think it's more likely related to some release shenanigans with react-bootstrap 0.26.x. What happened with 0.26.3 and 0.26.4? Perhaps they were accidentally tagged incorrectly? Can they be unpublished?

**Comment by taion** [comment]
0.26.2 has the wrong peer deps. You'll want to use 0.26.4.

**Comment by schutterp** [comment]
I downgraded to 0.26.2 because I saw the same issue with 0.26.4 and the changelog doesn't list 0.26.3 or 0.26.4. Perhaps this issue at least warrants an update to the changelog?

**Comment by taion** [comment]
Right, that's just NPM2's busted peer dependency handling, because of https://github.com/react-bootstrap/react-overlays/blob/v0.4.4/package.json#L42. @jquense I suppose it might be possible to cut a react-overlays v0.4.5 that specifies just ^0.13? I don't really see the point of working around NPM2 peer dep bugs though.

Consider using NPM3 to manage this, or just don't run `npm i react-bootstrap@0.26.x` like that until after you've already installed `react@0.13.x`. At any rate this is not our bug.

**Comment by schutterp** [comment]
Thanks for the info. Dependency hell is... hell! I guess this is part of the risk of using the latest and greatest tools like react-bootstrap in production. If a minor peer dep 'workaround' could save me (and maybe others who can't use npm3 yet) from this hell though why not!

**Comment by taion** [comment]
Just install React 0.13 before you install React-Bootstrap and you should be fine.

**Comment by lzhang** [comment]
Why not make `react-overlays` a peer dependency of `react-bootstrap`? Since they should all be using the same version of react at runtime?

**Comment by jquense** [comment]
its not a peer dependency, that would limit anyone who wanted to use react-overlays for non RB related things to the version RB is is using, which is a pain

**Comment by lzhang** [comment]
What I mean is set `react-overlays` as a peer dependency of `react-bootstrap`. Anybody could use `react-overlays` without installing `react-bootstrap`. Both packages would have `react` as their peer dependency, and since they are siblings in the dependency tree that should ensure they get the same version of `react`.

Are you saying that a possible use case is having both `react-bootstrap` and `react-overlays` installed as deps, hoping to get different versions of `react` for each in the same project?

**Comment by taion** [comment]
We don't want different dependencies on React. It's pulling in different deps because NPM2's handling of peer dependencies is buggy. react-overlays is just fine as an actual dependency.

**Comment by adamdicarlo** [comment]
@taion We just ran into this problem, too. The problem is **react-overlay 0.4.4** still has a bad peer dependency version range:

```
  "peerDependencies": {
    "react": ">=0.13.0"
  },
```
https://github.com/react-bootstrap/react-overlays/blob/v0.4.4/package.json#L42

So while it was fixed in this package (react-bootstrap) until it's fixed for react-overlays, anyone still on npm 2 trying to use react-bootstrap is in a bind!

**Comment by taion** [comment]
Just specify `"react": "0.13.3"` in your `package.json`.

**Comment by adamdicarlo** [comment]
That works... if you don't have an `npm-shrinkwrap.json` file. Then npm 2 gets really silly and decides it needs to install React 0.14 as well.

And I just tried this in a new directory, generating a new shrinkwrap *when in a good state* (no react-0.14 present). Wipe out node_modules, run `npm i` again, and react-0.14 shows up. :(

**Comment by adamdicarlo** [comment]
I think you could definitely say this is just a bug with npm 2. It really should not behave this way.

But just to make it clear, here's the minimal test case in a gist: https://gist.github.com/adamdicarlo/21d8a71568922870e4ab
