### ISSUE TITLE
sr-only the text content of the checkbox label

### ISSUE THREAD

**Issue by reggi** [react-bootstrap/react-bootstrap#1424]
The default checkbox label shows along with the checkbox:

```jsx
<Input type='checkbox' label='Checkbox' checked readOnly/>
```

![screen shot 2015-10-19 at 9 38 35 pm](https://cloud.githubusercontent.com/assets/296798/10595739/cb2429f8-76a9-11e5-90a2-b9efa31163f6.png)

So I tried `labelClassName='sr-only'`:

```jsx
<Input type='checkbox' label='Checkbox' labelClassName='sr-only' checked readOnly/>
```

Then it hid the entire checkbox because the checkbox itself is within the label. 

Why is the checkbox nested within the label?

Is there away to provide a label, and not display it and only allow it for screen-readers?

**Comment by egauci** [comment]
Instead of label, use aria-label and leave out labelClassName. The aria-label attribute is part of the HTML standard.

Bootstrap CSS seems to have a "margin-left: -20px" rule for checkboxes, which may have strange effects if you don't have a visible label.

From an accessibility perspective, "Checkbox" would be a very bad aria-label value. The assistive tech knows it's a checkbox.

**Comment by taion** [comment]
That's an excellent suggestion, @egauci. Thanks!
