### ISSUE TITLE
Warnings about requirements for assistive technologies.

### ISSUE THREAD

**Issue by santiagoaguiar** [react-bootstrap/react-bootstrap#1426]
This won't be very popular I guess. 

On the project I'm working on we have more than a good share of code already running on `react-bootstrap`, and have recently decided to upgrade from 0.21.2, which was an important effort. 

Our only remaining issue are the number of warnings (now shown in bright red on react 0.14 ;)) about:
` The prop 'id' is required to make 'Component' accessible for users using assistive technologies such as screen readers Check the render method of Component`

Though I understand the importance of having excellent support for assistive technologies and promote it's usage, at this point, and given the rest of our code base, investing time on fixing _just_ this warnings while the rest of the site (which is a specific purpose web app for internal use) isn't designed for accessibility, is a waste of time.

Would it be possible to enable these checks for assistive technologies support on-demand? Or at least be able to disable them?

Thanks!

**Comment by taion** [comment]
It's a PropType warning. Like any other, they're no-ops in production.

**Comment by santiagoaguiar** [comment]
I know, but unlike most warnings, since our site is not designed for accesibility, we don't actually need to fix these ones. All other warnings are things that we must fix, either now or once we update in the future.

Like is mentioned on the react 0.14 release notes:
`Our warnings appear when you use patterns that will break in future releases and for code that is likely to behave unexpectedly, so we do consider our warnings to be “must-fix” errors`

I guess that the point is if aria is optional to use react-bootstrap, or required. If it's required, then a warning seems right, otherwise I think it shouldn't be there. And I suppose that, to actually require you to create ARIA compliant apps, react-bootstrap will probably need a lot more checks than just validating `id`s are provided; only having that but no other checks doesn't seem particularly useful either, since you will still need some other tool around (some kind of linter or validation tool).

**Comment by taion** [comment]
I'd open an issue on react-prop-types then to discuss adding some sort of global override for disabling the `isRequiredForA11y` checks. The relevant code doesn't live in this repo any more.

**Comment by jquense** [comment]
we are slowly working to make sure that all components _are_ a11y compliant. Ideally we want to just take care of the a11y concerns automatically however, in cases where we need `id`s we can't just handle it ourselves because of how react handles server side rendering we can't just generate an ID if you don't provide one. 

in general our policy is to try and be unobtrusive but when we will choose to side with being a11y compliant vs not. since we need an ID to be a11y compliant adding it as a required prop is the most straight forward and honest approach. I would consider it the same way I'd consider us changing the prop api of any other prop/component.

**Comment by taion** [comment]
I agree with you there. I think it might be reasonable to have a global flag controlling whether a11y errors actually are errors, though, and to provide some mechanism in RPT for disabling error reporting on those.

**Comment by jquense** [comment]
Yeah I am not sure what react's position on propType errors is now, its always just be advisory, so i've always assumed these didn't apply to there "they are must-fix errror policy" but who knows.

I'd be fine considering a global switch, tho I don't love first class a11y overrides (this may not be that case tho as you say). tbh anyone can kill these or any proptype warning by just mutating `Component.propTypes.myprop = noop` that may be _too_ hacky though :P

**Comment by jonasfj** [comment]
I know this issue is closed, but adding some documentation saying what this id is supposed to identify would be nice...

I assume that this must be an id for an HTML element that acts as a label for the button. A mixin or utility to generate a random id might also be nice (otherwise components won't be composable).

In particular all objects should probably expose an `.id` property. If I understand this correctly :)

**Comment by jquense** [comment]
The `id` in these cases is just a normal html ID, it should be globally unique, and identifies the thing the ID is being applied too. We can't generate random ID's becasue it breaks server side rendering. https://github.com/facebook/react/issues/5867

**Comment by villesau** [comment]
What about providing an option to disable the warnings? We already wrap most of the bootstrap components we use so that would be easy to add in the wrapper. I think this is a real issue and should definitely be reopened. Having false-warnings has already caused us to accidentally ignore valid errors.

By having prop to disable id requirement would work as then we wouldn't need to have unique identifier for the id for every occurrence, but just a single prop instead.
