### ISSUE TITLE
Project intro for docs

### ISSUE THREAD

**Issue by syllog1sm** [react-bootstrap/react-bootstrap#147]
I'm excited to see how much has gotten done on this. I have some more time to work on the docs now, so I've had a quick start, just adding some explanation to the Getting Started page:

https://github.com/syllog1sm/react-bootstrap/commit/d65e35e7f55c65979d373b6110943259db031d2e

Questions:

1. Do you think direct comparison between Bootstrap and React-Bootstrap code is a good idea? If so, which component do you think shows us off the best?

2. Should something like this live on the main page? I'm thinking of the examples on the React.js project page. It's probably a good example.

**Comment by AlexKVal** [comment]
> https://syllog1sm.github.io/react-bootstrap/introduction.html

 IMHO. It is better than nothing.

Though it needs to change the code with ```React.DOM.button```.
And maybe it would be nicer to just place the link to `Components` page instead of `Example`.
It would result then in less maintaning of this page in future.

It needs for another maintainer :eyes: to express approval :wink:

**Comment by mtscout6** [comment]
I do like the concept of this, although it can use some cleanup. The styling is off in a few places.

![](http://cl.ly/image/3Y2I3B2f3X2C/Image%202015-04-22%20at%208.44.05%20AM.png)

Note the odd solid grey line there.

![](http://cl.ly/image/123V0422000G/Image%202015-04-22%20at%208.44.38%20AM.png)

The padding on those code examples is non-existant.

![](http://cl.ly/image/003H0h3U3s3z/Image%202015-04-22%20at%208.47.09%20AM.png)

Can we get syntax highlighting with both those examples

![](http://cl.ly/image/3p181U1i2U34/Image%202015-04-22%20at%208.48.36%20AM.png)

This text is a little too large, I'd almost rather this to just be regular text without added styling. Because of it's size it doesn't seem to flow right with the components below.

**Comment by AlexKVal** [comment]
I mean only the https://syllog1sm.github.io/introduction.html page.
the https://syllog1sm.github.io/components.html where the `text is a little too large` already exists.

@syllog1sm could you provide please the updated version of the https://syllog1sm.github.io/components.html page ?
In case you are not just let me know. I would try to add fixes by myself.

**Comment by AlexKVal** [comment]
I'm sorry.. Fixed 
... update version of the https://syllog1sm.github.io/introduction.html page ?

**Comment by syllog1sm** [comment]
Feel free to make the edits if you have time. I'm really not a front-end
developer (I work on statistical natural language processing), and I
haven't looked at this for some time.

Looking at this again, I do think the wording could be improved a lot. I
still think it's good to have a page that explains what the project is
though, so I hope the text can be improved.

**Comment by AlexKVal** [comment]
I need some help about sourcing the code.

The @syllog1sm 's code for the page is here https://github.com/syllog1sm/react-bootstrap/commits/master in these commits 
https://github.com/syllog1sm/react-bootstrap/commit/d65e35e7f5 through https://github.com/syllog1sm/react-bootstrap/commit/4bcbfcfccd4

What is the best way to do it ?

I create a new branch in my fork for this issue.
Then ... ?

How to get all those commits mixed and fixed up by my (local) future commits 
and then make from all that
just one commit for PR to the main project ?

**Comment by mtscout6** [comment]
@AlexKVal Have you seen PR #149? I think that's the source for this.

**Comment by AlexKVal** [comment]
Thank you. I didn't know it.
The project is so big for me. There are a lot of places that I haven't seen.

Can we close this issue with the discussion be continued here https://github.com/react-bootstrap/react-bootstrap/pull/149. ?

**Comment by mtscout6** [comment]
Fine with me!
