### ISSUE TITLE
Change rendered tag of NavDropdown's Dropdown.Toggle

### ISSUE THREAD

**Issue by sompylasar** [react-bootstrap/react-bootstrap#1504]
Currently, the `useAnchor` value is hardcoded:
https://github.com/react-bootstrap/react-bootstrap/blob/1b2b77579876a72baede9dedefb618196ae7524f/src/NavDropdown.js#L12

This results in the anchor behavior where it is not applicable because there is no URL to navigate.
Please provide the `useAnchor` property of `NavDropdown` to override that.

Please share your thoughts why using anchor as the dropdown toggle is required for `NavDropdown`.

**Comment by jquense** [comment]
in the context of a Nav an anchor is required in order for the styles to work, see Navteq and the upstream examples of navs. in general tho because it's semantically correct, given that it's a navbar. 

if you want to do a custom sort of nav you can use the plain ol dropdown and use whatever you want as a toggle. check out the docs for custom dropdowns.

**Comment by sompylasar** [comment]
@jquense Thanks. I'll have to use the custom dropdown implementation then.
