### ISSUE TITLE
Can't put input field in the OverlayTrigger and Popover?

### ISSUE THREAD

**Issue by ripitrust** [react-bootstrap/react-bootstrap#1551]
it seems that any input field put into the OverlayTrigger and Popover  over a Modal is not functional

the input field simply cannot enter any input

**Comment by taion** [comment]
I have input fields in my popovers and they work fine.

**Comment by ripitrust** [comment]
it is not just input in a popover , but  input in a popover in a modal,  looks like the overlay has some issues stacking together

**Comment by taion** [comment]
Turn off `enforceFocus` on the `<Modal>`.

**Comment by ripitrust** [comment]
great, I never notice this in the Modal

thanks for this life saver

**Comment by jquense** [comment]
the more accessible solution might be to set the popover container to the modal itself, so you can retain the correct focus behavior

**Comment by ripitrust** [comment]
@jquense  thanks for your help

does that mean to not use Overlaytrigger , and just put Popover in the Modal , and then show it by calling popover method ?

**Comment by jquense** [comment]
You can still use the the OverlayTrigger, but you can make use of the `container` prop (inherited from `Overlay`). By default its the `document.body` which places the input outside the modal, and why the modal takes focus away from the input since its trying to keep focus inside itself. If you set the container to the Modal, it will append the popover to the modal and should keep it inside the focus scope.

that's all untested and you might need to tweak it a bit practically

**Comment by ripitrust** [comment]
@jquense 
great
thanks for your explanation  I am gonna take a look

**Comment by VinodLouis** [comment]
Keeping overlay container as  document.body and passing the magical param enforceFocus as enforceFocus={false} in Modal resolved my issue :)

**Comment by shubham-rajodiya** [comment]
> Turn off `enforceFocus` on the `<Modal>`.

Awesome, worked. Thanks a lot.

**Comment by MitchTalmadge** [comment]
I assigned my `Modal.Body` to a ref and used the ref `current` value as the `container` attribute value on the `OverlayTrigger`. Works great now.

**Comment by amanullah01** [comment]
> Turn off `enforceFocus` on the `<Modal>`.

Thank You Bro. You save few lives.
