### ISSUE TITLE
Custom dropdown won't disappear when click area outside the dropdown

### ISSUE THREAD

**Issue by fantasy8-me** [react-bootstrap/react-bootstrap#1564]
Using version 0.27.2.
When use dropdown component like `NavDropdown`, the dropdown menu will disappear when we click on the area outside the dropdown.

But we I use custom `Dropdown` as below, seems no this feature, have to click on the `toggle` again to hide the dropdown, is it expected or any setting required?
```
      <Dropdown id="context-drop-down"
                className={this.props.className + ' context-menu site'}
                onToggle={this.props.toggleMenu}
                ref="dropdown">
        <div bsRole="toggle" className="dropdown-toggle"><i className="fa fa-bars"></i> {this.props.title}</div>
        <div bsRole="menu" className={'dropdown-menu'}>
          <MenuItem href={href} eventKey="library"> library </MenuItem>
          <MenuItem header> documentation </MenuItem>
        </div>
      </Dropdown>
```

**Comment by jquense** [comment]
Its expected the default Dropdown menu is the thing that implements the close on click outside behavior, so using a custom one wouldn't have that.

**Comment by nimerritt** [comment]
Perhaps it could be noted it the documentation? I expected the default behaviour as well.

**Comment by lucidlive** [comment]
I also expected this behavior and I'm curious as to what the solution is...

**Comment by jquense** [comment]
The solution is to implement the close on click in your custom Menu :P I suggest using react-overlays/root-close-wrapper since thats what the Dropdown menu uses.

**Comment by dvdgarcia** [comment]
Do you have any example of this jquense? I was expecting as well, an event or something to close if user clicks outside. The reason why I implemented my own dropdown is because the current react-bootstrap has not a dropdown with multiselect, it's a very common component but this version has not it :S and other which I found are not valid completely so I did one myself but the point to close clicking outside turns on complex
