### ISSUE TITLE
OverlayTrigger with trigger="focus" doesn't open Popover on Safari

### ISSUE THREAD

**Issue by DiogoDoreto** [react-bootstrap/react-bootstrap#1570]
Bug can be seen right on examples page:

https://react-bootstrap.github.io/components.html#popovers-trigger-behaviors

"Focus" button doesn't show popover on Safari. Tested on Safari 9.0.2.

**Comment by cvrebert** [comment]
Probably because the example isn't following http://getbootstrap.com/javascript/#callout-popover-dismiss-click

**Comment by abobwhite** [comment]
I am having this issue as well. My popover is triggered just via an icon, not a button, however, the premise is the same: ```trigger="focus"``` is not displaying the popover at all.

**Comment by abobwhite** [comment]
Looks like @cvrebert is right. I had to wrap my actual content to trigger the overlay in an anchor tag with tabIndex to get it to work. This should probably be mentioned in the docs and linked to the bootstrap docs.

**Comment by jquense** [comment]
you should be able to just add a tabindex to anything to get it to work, which makes items focusable, and therefore usable with the focus trigger

**Comment by jquense** [comment]
In general tho I am not sure there is anyway to address from an API perspective on our end.

I also find it odd that safari doesn't respond to focus events correctly for none links?

**Comment by abobwhite** [comment]
btw, I was having this issue in Chrome

**Comment by cvrebert** [comment]
It's weird but true regarding Safari. Even tabindex isn't enough. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus
Safari is stingy when it comes to focusability.

**Comment by jquense** [comment]
thanks for the reference. That's crazy...it seems so hostile to anyone using a keyboard or Screen Reader, and (as far as I can tell?) way off spec?

**Comment by cvrebert** [comment]
No, you can't <kbd>Tab</kbd> into it either. There's a System Preference which makes Safari (& other native apps) behave "normally":

<img width="670" alt="sysprefs" src="https://cloud.githubusercontent.com/assets/419884/13075154/02c63876-d45e-11e5-8c06-9fc2fe3a657b.png">

An web a11y friend says Apple justifies the Safari behavior on the grounds of consistency with native apps.
As for why Apple makes native apps behave that way, `¯\_(ツ)_/¯`

**Comment by patrickhlauke** [comment]
"Apple knows best"

**Comment by cvrebert** [comment]
> That's crazy...it seems [...] \(as far as I can tell?) way off spec?

Sadly, no, FWICT.

`tabindex` merely SHOULD, rather than MUST, make the element focusable:
https://html.spec.whatwg.org/multipage/interaction.html#the-tabindex-attribute:specially-focusable-5

And the HTML spec itself doesn't cover click-focusing behavior:
https://html.spec.whatwg.org/multipage/interaction.html#activation:run-synthetic-click-activation-steps-3

Isn't the Web® wonderful? :smiling_imp:

**Comment by taion** [comment]
Per the discussion above, I don't think this is a bug here – the trigger is behaving as expected, it's just that the node in question isn't focusable.

**Comment by erobertshaw** [comment]
This still a major bug. Popover triggers are all broken by default. "click" means you have to re-click the element that trigger it, really bad ux. "hover" doesn't work on a touch screen. "focus" should be the go to but doesn't work on safari! This component is basically a write off if it's not fixed even if it's technically within spec. Thanks for all the hard word, sorry to be critical. Just sharing my experience using this component.

**Comment by SweetSoul** [comment]
Just for posterity.

I created a state variable to control the overlay and created an empty div with some CSS rules to get when the user leaves the popover so I could close it. Popover trigger set to "click".

Something like this:
`{toggler && <div className="canvas" onMouseEnter={() => setToggler(false)}></div>}`

And the CSS (in my case SASS):
`.canvas
  width: 100vw
  height: 100vh
  position: fixed
  top: 200px
  z-index: 9`

This worked for me because my thing was a top menu toggler with a submenu, so 200px worked fine... But it is an ugly and hacked way of making this with a nice UX ;)
