### ISSUE TITLE
<Navbar.Toggle/> does not get rendered without a space before the closing tag

### ISSUE THREAD

**Issue by Morriz** [react-bootstrap/react-bootstrap#1572]
```
<Navbar.Toggle />
```
gets rendered, while
```
<Navbar.Toggle/> 
```
does not...not very forgiving and shouldn't happen imo

**Comment by Morriz** [comment]
I am on version 0.19.3 btw

**Comment by jquense** [comment]
That can't be right...are you using a hand made compiler? In any case if it is a bug, that is the fault of your jsx compiler not the component, not thing we can do about that.

**Comment by Morriz** [comment]
Did you try it? I am using the react-redux example stack from erik rasmussen and cohorts...nothing strange there I hope. Will post there as well then

**Comment by jquense** [comment]
Did you try it? you can see from the examples in the docs that changing the whitespace between the closing angle bracket has no effect on the code working.

You are misunderstanding the problem, the jsx representation of Component is completely out of the hands of _any_ library or stack, and __totally__ in the hands of the compiler you are using to transform the JSX into `react.createElement` calls. The only place this could possibly be a bug is the compiler, since it's a syntax parsing error.

**Comment by Morriz** [comment]
I understand. I will report it where it should be looked at...tnx
