### ISSUE TITLE
Add support for checkbox/radio buttons

### ISSUE THREAD

**Issue by richardscarrott** [react-bootstrap/react-bootstrap#1587]
i.e. http://getbootstrap.com/javascript/#buttons-checkbox-radio

**Comment by taion** [comment]
Why don't you try looking at our docs before asking this kind of question on the issue tracker...

**Comment by taion** [comment]
Oh, I see - this is different. My bad. I don't believe we have this.

**Comment by egeriis** [comment]
I would like this too. Open to PR?

**Comment by taion** [comment]
Always.

**Comment by konung** [comment]
@taion Ha - Looked through the issues but missed this one. thanks for merging. 

@egeriis @richardscarrott  - gentleman - have you had any luck with this?

**Comment by egeriis** [comment]
@konung Yes, we've had some luck. We've build the component, but didn't get to do a PR yet. Will take a look at this moment :)

**Comment by egeriis** [comment]
@taion I've looked into this now. These are my findings.

There are a lot of differences from a regular button:

1. Instead of being a `<button>` element, these checkboxes/radio buttons are `<label>`s with an `<input type="checkbox|radio">` as child
2. The `<label>` requires a parent element with a `data-toggle="buttons"` attribute
3. This parent element needs to be present, and can be either a _button group_ or just a regular `<div>`

These differences makes me consider that these special buttons should be their own element(s).

-----

Here's an outline of my suggested implementation. Naming is not thought through at all 🙂

**Changes to `<Button>`**
Allow `<Button>` to have `componentClass` property, which provides the ability to render it as `<label>`.

**Add new element `<CheckboxRadioButton>`**
This element would basically render:

```js
<Button componentClass="label" bsStyle={this.props.bsStyle} bsSize={this.props.bsSize} active={this.props.active}>
  <input autocomplete="off" type={this.props.type} value={this.props.value} onChange={this.props.onChange} checked={this.props.active}>
</Button>
```

**Consider adding `addToggleWrapper` property to `<CheckboxRadioButton>`**
`addToggleWrapper` will control whether the component will wrap the `<Button>` in a `<div data-toggle="buttons">` element. This will default to `true`.

**Handle `<CheckboxRadioButton>` when adding as child to `<ButtonGroup>`**
Set `addToggleWrapper` to `false` when `<CheckboxRadioButton>` is a child of a `<ButtonGroup>` and ensure that the `<ButtonGroup>` will have the `data-toggle="buttons"` attribute set.

Not sure how if this is possible or reasonable. But I would like for the user to not have to remember to set the `data-toggle` attribute on the correct element.

**Comment by jquense** [comment]
thanks for taking a look into this! I actually think that in a React context the implementation of this component is going to be a lot simpler. upstream uses labels, because that will also trigger the checked state of the hidden checkbox, without javascript. We don't have that problem so the label isn't technically necessary, though imagine that the css demands it.

There is also no need to have `data-toggle` on the components, that is for the sake of the bootstrap.js file which we don't use, since all the components are reimplemented. The only additional logic that is needed is to sync the `checked` state of the checkbox with the `active` prop on the button. which can be done by listening in onChange/checked

**Comment by taion** [comment]
Seems like the most straightforward implementation would be to just add a `button` prop (or maybe `bsClass`?) to `<Checkbox>` and `<Radio>`.

**Comment by egeriis** [comment]
@taion That seems reasonable. Looks like the markup is pretty much there. I thought there would be a more straightforward solution 🙂
@jquense The label receives the button style, that would be it's only purpose. Of course the `checked`/`active` logic is re-implemented, I didn't consider that.

**Comment by ChrisRus** [comment]
I am willing to try a solution in a non-trivial scenario.

Meanwhile, for my scenario I think I can away with something custom -  I'll just emulate the mutually exclusive behavior desired for my radio buttons by building something custom (not based on <input type="radio" but rather using standard buttons or some custom-rendered flip of appropriate Glyphicons gets it done for me).

I'm guessing my custom approach is not viable for a general-purpose solution where the actual elements used to render a form are potentially significant?

Thanks.

**Comment by kevinrue** [comment]
Hi all,
How's this one going?
I noticed that on the demo page, the "grouped" radio buttons (1,2,3) do not seem to be linked together:  each of them can be selected individually, but then none of them get unchecked when selecting another one.
I am aware that `react-bootstrap` is an active project on several aspects, I am just curious whether anyone is still looking into this feature?
Thanks for all the work so far!

**Comment by mengfoobar** [comment]
@kevinrue  opened an issue for this
#2544

**Comment by jquense** [comment]
done

**Comment by m-derevyanko** [comment]
DONE WHAT? Sorry)

**Comment by RyanNerd** [comment]
So this is "done" where are the docs for how to use this?

**Comment by jquense** [comment]
https://react-bootstrap.github.io/components/button-group/#btn-groups-checkbox-radio

**Comment by bradwayne** [comment]
I have a survey question with choices a, b, c, d or e. They can select a though d but e will override other selections. How do I combine checkbox and radio buttons . The catch is that I need to do it in React.
