### ISSUE TITLE
Tabs are outlined when selected

### ISSUE THREAD

**Issue by isikfsc** [react-bootstrap/react-bootstrap#1615]
Tabs are outlined like focused html elemnts when they are selected.

**Comment by jquense** [comment]
they are focused html elements... Not sure what you are referring to here

**Comment by vnglst** [comment]
I had the same problem with my tabs and it also happens on the React-Bootstrap website (see screenshots) but not on the official Bootstrap website. Is this behavior intentional?

React-Bootstrap after clicking on the Tab:
<img width="1041" alt="schermafdruk 2016-01-22 10 28 59" src="https://cloud.githubusercontent.com/assets/3457693/12507030/624e71f6-c0f3-11e5-9ba3-1dbf348a5247.png">

Official Bootstrap after clicking on Tab:
<img width="789" alt="schermafdruk 2016-01-22 10 29 38" src="https://cloud.githubusercontent.com/assets/3457693/12507034/678be6d0-c0f3-11e5-8c33-80bded5c656b.png">

**Comment by vnglst** [comment]
I did manage to remove the glowing blue outline by adding this to my css:

```
a:focus {
  outline: none;
}

.btn:focus {
  outline: none;
}
```

**Comment by jquense** [comment]
The current behavior is intentional and the upstream bootstrap behavior is __wrong__. Proper Accessibility behavior for tabs (as dictated by the ARIA working drafts) requires that the selected tab be selected (and navigable by arrow keys).  

@vnglst removing the outline of every button and link is a really terrible practice. It makes your sites unusable for anyone who isn't using a mouse, because they can't see where focus is in the page. Focus outlines are there for a REASON and the reason is not because browsers think it looks nice. Removing it for aesthetics makes your site unusable to an entire subset of users.

**Comment by vnglst** [comment]
@jquense Thanks for taking your time and for replying. I didn't know that and removing them all together seems like a very bad idea indeed!

Wouldn't it be better though, to enable the highlighting of the outline of buttons and tabs only when the tab key is pressed? This seems to be standard behavior on most sites (also on the Bootstrap website). That way the website would still be usable without a mouse.

**Comment by jquense** [comment]
We aren't controlling when the outline is shown for buttons or links in general. We just focus stuff as it's require. The tabs API is being reworked in the next release so this may be less of an issue (I am not sure)

In general for outline this is a good resource: http://www.outlinenone.com/

**Comment by vnglst** [comment]
Oh, there's actually a website dedicated to it! I feel honored. ;-) Thanks for getting back so quickly.
