### ISSUE TITLE
Synthetic Events broken with React v. 0.14.7

### ISSUE THREAD

**Issue by noahzgordon** [react-bootstrap/react-bootstrap#1637]
It seems that the new React release has broken synthetic events for certain react-bootstrap event listeners and/or components. As of today, certain actions taken on machines with v0.14.7 installed resulted in the following error:
```
TypeError: 'null' is not an object (evaluating 'event.target.*')
```

This was not reproducible on machines with v0.14.6 installed.

I observed this failure in two scenarios: 
1. Binding to `onChange` with an Input component.
2. Binding to `onSelect` with a DropdownButton component.

This line from the latest React changelog might be handy: `Fixed memory leak in synthetic event system`
https://github.com/facebook/react/blob/master/CHANGELOG.md#react

As a temporary solution we've locked our React version to 0.14.6. However we'd like to upgrade versions in the future, so a solution on react-bootstrap's end would be preferable. Let me know if there's any other information I can provide to help.

**Comment by noahzgordon** [comment]
Also possible that this is just a problem with React 0.14.7, but figured I'd post it here and get some more information about whether or not it could be a problem with react-bootstrap first. We're only experiencing the issue for react-bootstrap components.

**Comment by Sinistralis** [comment]
Just tried to recreate this using React 0.14.7 and Bootstrap 0.28.2 with no success. Can you post the input and event handler in question?

**Comment by nfcampos** [comment]
this might help someone:
I had the same problem with the onChange of an Input not working after the upgrade to 0.14.7.
In my case it was because my onChange handler was using debounce, which meant the actual SyntheticEvent object was accessed asynchronously, and had therefore already been reused by React (see https://facebook.github.io/react/docs/events.html#event-pooling).
My solution for this was to wrap debounce like this:
```js
function debounceEventHandler(...args) {
  const debounced = debounce(...args)
  return function(e) {
    e.persist()
    return debounced(e)
  }
}
```
```js
<Input onChange={debounce(this.handleInputChange, 150)}/>
// becomes
<Input onChange={debounceEventHandler(this.handleInputChange, 150)}/>
```
Another solution is to access the value of the event synchronously and pass that as an argument to the event handler:
```js
<Input onChange={debounce(this.handleInputChange, 150)}/>
// becomes
<Input onChange={e => debounce(this.handleInputChange, 150)(e.target.value)}/>
```
(I know it's probably not a great idea to be calling debounce directly on the render() method, it's to make the examples clearer)

**Comment by zephyr-dev** [comment]
@nfcampos thanks for the example! This does seem to be the case for one of the inputs, because we're accessing the value asynchronously which I didn't realized was disallowed by React. We'll use `event.persist()` to address this issue. Will attempt to reproduce and verify that this works with 0.14.7 tomorrow.

**Comment by noahzgordon** [comment]
@nfcampos thanks for the example! This does seem to be the case for one of the inputs, because we're accessing the value asynchronously which I didn't realized was disallowed by React. We'll use `event.persist()` to address this issue. Will attempt to reproduce and verify that this works with 0.14.7 tomorrow.

**Comment by noahzgordon** [comment]
Using `event.persist()` did indeed fix the problem. Weird that accessing the values asynchronously worked as of 0.14.6. 

Anyway, thanks for the help @nfcampos and sorry for the unneeded issue @Sinistralis! I'll close the issue now.

**Comment by nfcampos** [comment]
@noahzgordon Glad the example helped!
