### ISSUE TITLE
DropdownButton doen't supports block property.

### ISSUE THREAD

**Issue by khakulov** [react-bootstrap/react-bootstrap#1680]
DropdownButton doen't supports block property.

**Comment by taion** [comment]
Seems like an easy fix. Care to put together a PR?

**Comment by hitchcockwill** [comment]
I took a stab at this today. It's a pretty simple fix, but leads to an edge case with styling that's not covered in the bootstrap library styling.

Line 22 in `src/ButtonGroup.js` requires that if the `block` prop is present that `vertical` must also be present.

The bootstrap styling for ButtonGroup expects that all children of `.btn-group-vertical` are instances of `.btn`. In the case of `DropdownButton`, we generate the following HTML where `.btn-group-vertical` has multiple children but only one `.btn`:

```
<div class="dropdown btn-group-vertical btn-block">
  <button id="dropdown-size-medium-block" role="button" aria-haspopup="true" aria-expanded="false" type="button" class="dropdown-toggle btn btn-default btn-block">Default Button</button>
  
  <ul role="menu" class="dropdown-menu" aria-labelledby="dropdown-size-medium-block">...</ul>
</div>
```

That, combined with this styling from bootstrap renders a button with no border radius on the bottom corners each time.

```
.btn-group-vertical > .btn:first-child:not(:last-child) {
    border-top-right-radius: 4px;
    border-top-left-radius: 4px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
}
```

![screenshot 2017-10-11 18 37 51](https://user-images.githubusercontent.com/1471313/31473703-783d6774-aeb3-11e7-89d3-7355d055c350.png)

One option here would be to make it so `block` does not require `vertical` in `ButtonGroup.js`, but I'm reluctant to make that change because I'm assuming that's there for a reason. 

Another option is to add some inline styling, but that seems hacky.

Looking for some other suggestions here. Any ideas?

**Comment by taion** [comment]
What does upstream TWBS show in their demos, if anything? Does `block` do anything for dropdowns if `vertical` isn't set?

We can just enable the feature and not update the docs if it's not something that's actually supported by default TWBS styling.

**Comment by hitchcockwill** [comment]
TWBS doesn't show a block level button dropdown in the docs. Adding the `btn-block` class to `.btn-group` and `.btn` gives the correct styling but when `.btn-group-vertical` is added the border radius is removed.

It seems to me that the correct implementation would be to have `.btn-block` added to the `.btn-group` and `.btn` elements without `.btn-group-vertical`, but that would require that change to the `ButtonGroup.js` proptypes that I mentioned above.

**Comment by taion** [comment]
Okay, I took a look at what's happening here.

`.btn-block` doesn't make sense on button groups period. The `display: block` property gets overridden, and it ends up just doing `width: 100%`, which is a silly thing for a class named `.btn-block` to do; I think that it does anything is essentially just by coincidence.

If anything, I'd drop the `block` prop from `<ButtonGroup>`. If a user wants a `<ButtonGroup>` with 100% width, he or she can just set `width: 100%` some other way, instead of applying the inappropriate `.btn-block` as a hack.

**Comment by taion** [comment]
The `block` prop shouldn't be used on `<DropdownButton>`. Closing this issue given pending deprecation of that prop in https://github.com/react-bootstrap/react-bootstrap/pull/2850.
