### ISSUE TITLE
Multiple radio inputs not working

### ISSUE THREAD

**Issue by davidkpiano** [react-bootstrap/react-bootstrap#1690]
See here for issue: http://esnextb.in/?gist=fff6baa60ddd5e42e4ff

Expected: "Yes" and "No" to be logged when the respective radio buttons are clicked.

Actual: only "Yes" gets logged.

**Comment by jquense** [comment]
thanks for the issue, this is the correct behavior and just how radio inputs with the same name are handled by browsers.

**Comment by nickzarate** [comment]
@jquense Sorry what do you mean by that's the correct behavior? Does that mean you shouldn't ever give radio inputs the same "name" prop?

**Comment by jquense** [comment]
you should give radio inputs the same name if the represent different possible values of the same field. By "correct" I mean that the browser correctly treats the group as a single input for one field and only fires the change once for the group, instead of once for the radio that becomes unchecked and again for the checked one.
