### ISSUE TITLE
Support 'target' prop on OverlayTrigger for explicit positioning

### ISSUE THREAD

**Issue by pcwinters** [react-bootstrap/react-bootstrap#1694]
`OverlayTrigger` ignores the `target` prop allowed by `Position` in `react-overlays`. I can't see any reason why you wouldn't want to allow that to be specific with an OverlayTrigger. It would default, naturally, to the current behavior and use the `OverlayTrigger` as target.

```
<OverlayTrigger
  overlay={filterMenu}
  placement='bottom'
  target={() => ReactDOM.findDOMNode(this.refs.trigger)}>
  <span>I want all of this to be part of the trigger, and it's a *lot* of content.
    But, I want the overlay to be positioned directly under 
    <span ref="trigger">this</span> word.
  </span>
</OverlayTrigger>
```

If I get a :+1:, I'll submit a MR, it should be really easy.

**Comment by jquense** [comment]
I think I am :-1: on supporting this, OverlayTrigger is meant to address them most common use of `Overlay` where you want to just show something over the thing you are clicking. In cases like the one above I don't think direct use of the Overlay component causes much undo burden

**Comment by taion** [comment]
I agree with @jquense .

**Comment by pcwinters** [comment]
OverlayTrigger already does a nice job of handling trigger events, show/hide state, delays, etc. And, it forwards position/overlay props to `react-overlay` components. `target` would be one more that has a reasonable default for simple use cases. I think it would be a mistake to be overly restrictive.

**Comment by taion** [comment]
If you can do this without messing up the code too much, I wouldn't necessarily be opposed to merging it, but we're not going to accept this as a feature request on our side for the time being.

**Comment by xvash** [comment]
@taion @jquense 

This would be great for my use case. I have a table with infinite scroll (suppose it supports up to a million rows) so elements are added/removed as the user scrolls.

Instead of adding say 200 OverlayTrigger handlers (20x10 visible cells) to each element, I would like to add one to the table wrapper and when the user hovers over the element, change the tooltip content and the target element.

I already wrote my own method for this, but why reinvent the wheel? I want the same handling of OverlayTrigger but control of the target.

**Comment by jquense** [comment]
@xvash you want to use Overlay for your use case, that's exactly what the lower level API is for.
