### ISSUE TITLE
Revamp <Pagination> API

### ISSUE THREAD

**Issue by taion** [react-bootstrap/react-bootstrap#1758]
Possibilities:
- `<PaginationButton>` -> `<Pagination.Item>`
- An actual sane API for customizing pagination links (maybe based on `children`?)

**Comment by bebraw** [comment]
If you want inspiration, see http://sapegin.github.io/react-pagify-preset-bootstrap/ . That's a little Bootstrap preset we did on top of react-pagify. Maybe you can mimic the API from there. It's very flexible.

**Comment by taion** [comment]
My current thinking is just to have a `renderItem()` function as the customization hook. I think `<Pagination>` has enough valuable logic inside that we can't just rip it apart (without forcing users to do a lot more work).

This is mostly just a placeholder so I don't forget, though.

**Comment by AndreiRailean** [comment]
You need to allow for more granular and smarter buttonComponentClass-like overrides.
I'm working on isomorphic stuff and need to have the component render the href link. I would be able to do this in `buttonComponentClass` except PaginationButton doesn't pass the page number down (by explicitly unsetting it in https://github.com/react-bootstrap/react-bootstrap/blob/ae48d58afc2bcfcc36cabec136bba33929387513/src/PaginationButton.js#L51)

As far as react-pagify goes - it's got a very confusing API - i wouldn't follow that unless you want to scare people away. I couldn't do isomorphic stuff with react-pagify either because href generator cannot be overridden to make it smarter.

One thing react-pagify has is more granular control over what tags are used to render pagination, but there's no need for it here because bootstrap prescribes a particular structure to pagination component. Rendering without ULs and LIs means it's no longer a bootstrap component but something that looks like one if you invest time into making it look (and act) that way. In that case you don't need react-bootstrap.

**Comment by taion** [comment]
That's a bug per https://github.com/react-bootstrap/react-bootstrap/issues/1866.

The API should be something like a `renderItem` callback.

**Comment by taion** [comment]
This was resolved in #2587.
