### ISSUE TITLE
Not possible to override bootstrap styles with className

### ISSUE THREAD

**Issue by ChiperSoft** [react-bootstrap/react-bootstrap#1773]
On every component that I've checked so far the className for the base element gets attached as `className={classNames(className, brandClasses)}`

Because of this, any className defined on the component shows up before the bootstrap classes, giving the bootstrap class higher precedence over the custom class.

The end result of this is that I can't set a class on a NavBar.Brand which overrides the text color without resorting to `!important`.

Can the ordering on these be reversed across the board?

**Comment by taion** [comment]
That's not how CSS precedence works.

**Comment by ChiperSoft** [comment]
Dammit, you're right, I don't know why I was thinking that's what was causing it.  Sorry to wasting your time.

**Comment by qur2** [comment]
Hi,

I'm running into the same issue. Would you care to elaborate a bit? How should one handle that?
I'm trying to pass down a class to a `<Dropdown>` component to modify the width styles but bootstrap styles overwrite mines.
And I want to customize a specific dropdown, not all of them.

Thanks for any hint.

**Comment by jquense** [comment]
qu2 your class need to have a higher specificity than the default styles, it's  othing to do with how we add classes

**Comment by qur2** [comment]
Ok, damned, the project I'm working on uses css modules, so I'm supposed to avoid nesting styles. Thanks for the answer.

**Comment by NeliHarbuzava** [comment]
Have this too. It is worst part of this lib. In most of other React libraries when we add className prop, our custom class names will append to the end of final class prop. This is what I think should be in this lib too. That's seems more intuitively because of our classnames called "custom" and most of the other libs uses this approach too. Why should we use  nested styles just for this reason?
