### ISSUE TITLE
.getValue() vs event.target.value?

### ISSUE THREAD

**Issue by Siyfion** [react-bootstrap/react-bootstrap#1821]
Really, much as the title suggests, assuming I have an input like so:

```jsx
<Input
  type="email" placeholder="Email"
  value={this.state.email}
  onChange={this.handleEmailChange}
  required autoFocus
  ref="emailTest"
/>
```

How should I be handling the change event?

```jsx
handleEmailChange(e) {
  this.setState({ email: e.target.value });
}
//
// OR
//
handleEmailChange() {
  this.setState({ email: this.refs.emailTest.getValue() });
}
```

And are there certain circumstances when I should choose one over the other?

**Comment by taion** [comment]
`<Input>` is deprecated and the latter API (with `getValue`) is no longer supported.

**Comment by Siyfion** [comment]
@taion Wow, when the hell did that happen!? I was only looking at this yesterday or so!?

**Comment by taion** [comment]
We released v0.29.0 yesterday, which deprecated the old `<Input>` components in favor of lower-level form components that allow more flexibility. These changes have been in alpha for a bit though.

**Comment by mosse** [comment]
Have been digging around the docs but am a little confused. What replaces getValue, or how can similar functionality be implemented in 0.29?

**Comment by taion** [comment]
The underlying DOM node is just the `<input>`, so you can do whatever you'd normally do there. The wrappers are much thinner now.

**Comment by wphampton** [comment]
So do we now use `ReactDOM.findDOMNode` to interact with it like this?

`<FormControl type="text" ref={ref => this.userEntry = ref} />`

```
focusUserInput () {
    ReactDOM.findDOMNode(this.userEntry).focus();
}

getUserInput () {
    return ReactDOM.findDOMNode(this.userEntry).value;
}
```

**Comment by taion** [comment]
Yes, same as if you were using an `<input>` directly. You can wrap this up yourself in a higher level "field group" component that handles labels, &c. if you want, and in fact if you use this pattern extensively I'd recommend doing so.

We just had to switch up the API to something a bit lower-level to better support use cases like horizontal forms.

Alternatively, you can use React Formal for form management, which is likely a more scalable approach.

**Comment by danmolitor** [comment]
Just so I'm clear on this. 

Before, I was able to do something like:

 `<Input ref={(input) => this._input = input />`

or whatever I would want the ref to be, and I would reference it by:

`this._input.refs.input.value`

Currently from trying to switch over, it seems like this is not an option while using the <FormGroup><FormControl> elements. Is this no longer possible? or does it just need to be written in a certain way? Thanks in advance.

**Comment by taion** [comment]
Attach the ref to the `<FormControl>` – you can then do `this._input.value` or whatever.

**Comment by taion** [comment]
Quick fix to the above comment.

**Comment by danmolitor** [comment]
Thanks for the quick response! That's what I tried, but I get undefined when I console.log the ref. It totally works fine with the last version using Inputs, but i'm trying to update my code to be current. Might be something to look into.

**Comment by taion** [comment]
The ref is just the React component – it shouldn't be undefined unless something else is going wrong.

**Comment by danmolitor** [comment]
Ah, just saw the edit with ReactDOM.findDOMNode. Awesome. That did it, thank you!

**Comment by pellejacobs** [comment]
Why doesn't `FormControls` not support this `this.refs.myInputRef.value` syntax? Based on the 0.14 react release notes, this seems to be the default syntax for input fields: https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#dom-node-refs. They even mention that findDOMNode often could be avoided: 

> Due to the DOM node refs change mentioned above, this.getDOMNode() is now deprecated and ReactDOM.findDOMNode(this) can be used instead. Note that in most cases, calling findDOMNode is now unnecessary.

In our project we have no other reason yet to import the react-dom library, so it feels like a shame to pull it in, just to do something, that could be done with the plain react library.

**Comment by taion** [comment]
What does that even mean? You have a hard dependency on react-dom via React-Bootstrap anyway if you're using it. That note about refs is for component-internal refs. `React.findDOMNode(control)` is just a much cleaner API than `control.refs.input`.

**Comment by dozoisch** [comment]
Don't you need react-dom to do the initial render anyway? 

And this.refs.inputRef.value can't work because FormControls is a composite component not a direct dom node. So you have to retrieve the dom node.

**Comment by jquense** [comment]
and for everyone at home,  the _right_ to get an input value is to use controlled inputs.  if you want to imperatively  grab value from a component you are already outside of the "React blessed way" so no problem requiring you use react-dom

**Comment by dozoisch** [comment]
totally agree with @jquense

**Comment by Artur-A** [comment]
First, try not to use` ReactDOM.findDOMNode` or do any DOM manipulation until there is no other way to do it. Although there are some optimizations a browser almost every time parses HTML page to find your element when you use `findDOMNode` or, behind the scene, `document.getElementById(id)`.
That is very unproductive. And that is why it is recommended in jQuery to find element and get link to a jQuery wrapper for reusing:
`var linkTojQueryObject = $("#id"); linkTojQueryObject.doOne(); linkTojQueryObject.doAnother();`
instead of the following non-optimized way with twice searching element in DOM: 
`$("#id").doOnething();  $("#id").doAnotherThing();`
Facebook team clearly writes about this idea:

>  **In most cases, you can attach a ref to the DOM node and avoid using findDOMNode at all.**
> findDOMNode() is an escape hatch used to access the underlying DOM node. In most cases, use of this escape hatch is discouraged because it pierces the component abstraction.

/----/
Second, it is even better to use already given in-memory data of an event. Save it locally in a Component  and then use.
```
<FormControl type="text"
    onChange={(e) => { this.WhatToDoWithChangedText( (e.target as any).value as string ) } }  />
```
Currently there is a problem with `EventTarget` type, which does not have `value` property. Thus one of the solution is to apply casting to any: `(e.target as any)`.

To have IntelliSense I use a helper interface:
```
export interface FormControlEventTarget extends EventTarget{
    value: string;
}
```
and then casting it to EventTarge to have string value:
` onChange={(e) => { this._text = (e.target as FormControlEventTarget).value } }`

/----/
Third, due the mentioned facts the refs string searching in DOM is deprecated by Facebook. So, the next is quite unproductive to use. React will use slow document.getElementById("myInput"):
```
<input ref="myInput" /> 
var input = this.refs.myInput.value; // or, which is the same
var input = this.refs["myInput"].value;
```
Instead of this Facebook suggests to take in-memory link to React object when it is mounted and use it later (similar to jQuery)
` <input type="text" ref={(refToReactObject) => this._localLinkToReactObject = refToReactObject} />`

P.S. Most of the code is written in TypeScript with ES6 support.
Hopefully it makes the situation more clear.

**Comment by jquense** [comment]
> React will use slow document.getElementById("myInput"):

FYI, that's not true, react knows what the DOM nodes are it doesn't query the DOM or use `getElementById` at all, so no worry about that not being fast. Also `getElementById` is really fast.

**Comment by Artur-A** [comment]
@jquense, you are write
document.getElementById(..) is a very fast operation in modern browsers.
Nevertheless, using memory reference is faster, and the code is much more clean and less error prone.

**Comment by jquense** [comment]
@Artur-A my point is that `findDOMNode` does use a memory reference. It doesn't query the DOM for the input it asks React for the node, and it stores a reference on each component so it's as quick as storing the reference yourself, or using a ref.
