### ISSUE TITLE
Accordion triggers a synthetic event warning in React v15

### ISSUE THREAD

**Issue by same31** [react-bootstrap/react-bootstrap#1829]
I copied the following example from the doc: http://react-bootstrap.github.io/components.html#panels-accordion in a fiddle with react v15.0.1 and react-bootstrap v0.29.0 : https://jsfiddle.net/same31/5v143xf3/7/

On the first click on a collapsible panel, this warning is triggered :

> Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're adding a new property in the synthetic event object. The property is never released. See https://fb.me/react-event-pooling for more information.

Is this possible to get rid of this warning ?

Thanks

**Comment by vincent-dm** [comment]
I also have this and additionally no synthetic event is passed to my `onSelect`-handler. Because of this the browser windows scrolls to the top of every page because I cannot call `preventDefault()` on the event...

**Comment by nickpalmer** [comment]
For me this is triggered by the Panel.js handleSelect function.

The function is setting e.selected = true and then checking it down below. I think @vincent-dm may be confused about the API, since the first argument to onSelect is the key and the second is the event.

Presumably e.selected is designed to be used by props.onSelect handlers to allow them to prevent handleToggle from being called. It maybe better to use a return value from onSelect() instead?

```
handleSelect: function handleSelect(e) {
    e.selected = true;

    if (this.props.onSelect) {
      this.props.onSelect(this.props.eventKey, e);
    } else {
      e.preventDefault();
    }

    if (e.selected) {
      this.handleToggle();
    }
  },
```

**Comment by taion** [comment]
We'd accept a PR to fix this. We're looking to replace this full API by the next breaking release, so maintaining the current one is not a high priority.
