### ISSUE TITLE
Safari: Collapse doesn't close correctly

### ISSUE THREAD

**Issue by ya-kostik** [react-bootstrap/react-bootstrap#1841]
Hi!
When I close collapse panel transition doesn't work.
That react-bootstrap version:
![bag](https://cloud.githubusercontent.com/assets/12064332/14745522/bfee649a-08bc-11e6-9223-a2c8b5623071.gif)

That vanilla bootstrap version:
![nobag](https://cloud.githubusercontent.com/assets/12064332/14745539/d76a3a40-08bc-11e6-8cb9-b6246c51b5b9.gif)

Regards.

**Comment by taion** [comment]
Works fine for me on http://react-bootstrap.github.io/components.html#panels-collapsible

**Comment by ya-kostik** [comment]
I'm sorry. Not tested in chrome. My fault. =(
All there really works well. The problem occurs in Safari on OS 9.1 X and iOS Safari too.

**Comment by taion** [comment]
You mean that with Safari, the collapse works in vanilla Bootstrap JS, but not here?

**Comment by ya-kostik** [comment]
I guess react-bootstrap use css transitions, but vanilla bootstrap use jQuery animate or something else.
But I guess I said stupid things.
Sorry.

**Comment by jquense** [comment]
We are jsut tryingto figure out what is different in your case vs waht we've tested here. it should work in Safari, and we don't do anything different from vanilla bootstrap, both use css and js to animate.

**Comment by taion** [comment]
I just checked – this is in fact broken for us on Safari.

**Comment by Inoir** [comment]
Any update here?

**Comment by schuma7** [comment]
The same thing happens when collapsing the responsive navbar on mobile. Chrome seems to work fine but Safari on Mac OS and iOS just jumps to the target position instead of smoothly transitioning to it.

**Comment by rafgugi** [comment]
hey how is it going here?

**Comment by jquense** [comment]
I'm doing well thanks for asking.

**Comment by kazazor** [comment]
👍  on fixing it

**Comment by kazazor** [comment]
Can we change the name of this bug to say that this is only on Safari?

**Comment by danielgefen** [comment]
👍 On fixing that also!

**Comment by Sivanga** [comment]
👍  On fixing it!

**Comment by jquense** [comment]
Friendly FYI everyone we're probably aren't going to get to this in any timely manner. So If it's important to you please consider sending a PR

**Comment by benbraou** [comment]
The issue is that browser reflow is triggered after the start of the collapse animation (Collapse component). 
Here is a quick summary of the what happens:

1. Before collapse starts, the dimension style property (width or height) is empty. It gets then updated with the height of the panel to collapse (let's say 70px)
2. After the component starts to collapse, a browser reflow is triggered and the dimension style property (width or height) is set to 0.

The fix is to trigger the reflow at step 1 instead of step 2: before the animation starts.
I tested this in macOS Safari and the issue is fixed (in transition component and collapsible panel )
I am going to send a PR for this. 

Since the commit is only to change when the reflow is trigger, I don't see how I can update the tests accordingly. Please let me know if you have any suggestion.
