### ISSUE TITLE
components could be a lot less verbose

### ISSUE THREAD

**Issue by jedwards1211** [react-bootstrap/react-bootstrap#1848]
Ideas for 1.0.0...

I rolled my own bootstrap wrappers starting in the day when dropdowns needed an overhaul in this project.
For awhile my components were very wordy.  However, over time I figured out how to get them to be very concise.  I would love to see the same developments in this project.  For example:

```jsx
<Button lg primary>Submit</Button>

<Alert error>Something went wrong</Alert>

<InputGroup>
  00.
  <Input type="text" value={...} onChange={...}/>
  <Button primary><Glyphicon plus/></Button>
</InputGroup>

<ListGroup>
  <li success badge={14}>Success</li>
  <a href="/info" info>Info</a>
  <Button warning onClick={...}>Warning</Button>
  <li danger>Danger</li>
</ListGroup>

<Form horizontal labelClass="col-sm-2" controlClass="col-sm-10">
  <Input  formGroup label="Email"    type="email"    placeholder="Email"/>
  <Input  formGroup label="Password" type="password" placeholder="Password"/>
  <div    formGroup>
    <Input type="checkbox"/> Remember me
  </div>
  <Button formGroup submit>
    Sign in
  </Button>
</Form>
```

**Comment by jquense** [comment]
Well in the case of the Form Inputs we had that syntax and but removed it in the last version _for_ more verbose versions. The general issue is that as a library serving lots of different use cases, more prescriptive (i.e. less verbose) components are less flexible and don't handle edge cases well. 

I have made wrappers similar to your Buttons, in the past as well, but it doesn't make sense here, because its less extendable, and increases the "reserved" props on the components significantly It is also much harder to prevent something like `<Button warning danger primary />`

Ultimately as a user you are definately encouraged to wrap the library components to create ones that best suit the needs of your application, the ease of that is one of the great parts of the React component model. For us, as a library and UI framework, the flexibility is a more important goal than "less verbose" if only because you can make the components less Verbose, but you can't easily make them more flexible than the underlying one allows.

**Comment by jedwards1211** [comment]
How is it less extendable?

`<Button warning danger primary />` isn't a problem; you just maintain a defined order of precendence.  Obviously the precedence begins with danger, warning.  The ideal order of success, info, primary is less clear, but it just needs to be defined.  The precedence is very convenient in cases like this:
```jsx
<Button warning={value > warningThreshold} danger={value > alarmThreshold}/>
```

**Comment by jedwards1211** [comment]
The other thing is, bootstrap is simple enough that in a lot of cases, if I'm going to make my own wrapper components, it's generally easier/more performant to just make them work standalone than to make them wrap components of this library.

**Comment by taion** [comment]
`<Button>` does a little bit more than that – it has logic for figuring out which specific component to render, and controlling handling things like `disabled` state and interacting properly with e.g. React Router.

**Comment by jquense** [comment]
I think if you looked through all but the simplest components here, you'd see that there is actually a lot of non-trivial logic in them that, you could recreate, but I would almost certainly not be simpler than wrapping these components.

You are of course welcome to build you're own, but we can't reasonably make the choice to exclude some valid use case for the sake of making other use cases simpler.

**Comment by jedwards1211** [comment]
@jquense that's fair, but what use case does `<Button lg primary>` exclude?  (In my components I support a `contextClass` prop as well, just like your `bsStyle` prop, for cases where it's more convenient).

**Comment by jquense** [comment]
with the above api you can do this: 

```js
const types = {
  'foo': 'danger',
  'bar': 'success'
}
<Button bsStyle={types[this.props.type]} />
```

among some, but generally while more convenient the API makes validation, and interop with custom bsStyles more complicated.

**Comment by jedwards1211** [comment]
My components support both ways of doing this, like so:
```jsx
<Button contextClass={types[this.props.type]} />
<Button primary />
```
If `contextClass` is given, it overrides any boolean props.  It's quite simple.  The same could be done supporting the boolean props with `bsStyle` as an optional override.

I'm really just trying to offer ideas to make code throughout the ecosystem more beautiful, as I might myself have to work on it one day.
