### ISSUE TITLE
Compatibility with awesome-bootstrap-checkbox

### ISSUE THREAD

**Issue by stephanedaviet** [react-bootstrap/react-bootstrap#1898]
There's this nice lib: https://github.com/flatlogic/awesome-bootstrap-checkbox that can be put with bootstrap to get checkbox/radio fancy and uniformly rendered among all browsers. It's quite popular but needs a subtle change in the way checkbox/radio DOM structure is declared. See below.

The classic bootstrap way (the one used in React Bootstrap):
```html
<div class="checkbox">
  <label>
    <input type="checkbox"> Check me out
  </label>
</div>
```

The adapted way need for _awesome-bootstrap-checkbox_ to work:
```html
<div class="checkbox">
  <input type="checkbox" id="checkbox1">
  <label for="checkbox1">
      Check me out
  </label>
</div>
```

There's currently no simple way to tweak the _React Bootstrap_ checkbox and radio components to alter the DOM structure in such a way.

Would you accept a pull request introducing a new property for those two components to switch to this alternate structure and thus provide ability to get styled checkbox/radio through the aforementioned library?

**Comment by jquense** [comment]
hi, we are only working supporting the vanilla bootstrap markup and components so wouldn't take a PR allowing "incorrect" markup for a normal bootstrap. However the Checkbox and Radio components are really simple components, so there wouldn't even be much to gain from allowing different markup there. You also don't need to use the the builtin checkbox or Radio components at all.

I would just write your own little wrapper for the awesome-boostrap-checkbox and use that instead of the components here
