### ISSUE TITLE
Custom props should not be transferred to child components

### ISSUE THREAD

**Issue by jochenberger** [react-bootstrap/react-bootstrap#1970]
React 15.2 will add a check for unknown props being passed to a component. A lot of `react-bootstrap`'s components pass their props down to their children leading to warnings like
```
"Warning: Unknown prop `bsSize` on <button> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in button (created by Button)
```
Other examples are: 
* `bsClass` on `<div>` tag (created by Well)
* `active`, `block`, `navItem`,  `navDropdown`, `bsStyle`, `eventKey` on `<a>` tag (created by SafeAnchor)
* `items`, `maxButtons`,  `activePage`, `boundaryLinks` on `<ul>` tag (created by Pagination)
* `glyph` on `<span>` tag (created by Glyphicon)

See https://fb.me/react-unknown-prop

**Comment by jquense** [comment]
wow that's really annoying React. thanks for the heads up

**Comment by taion** [comment]
This is why I always spread out the props I'm going to use 😛

**Comment by jquense** [comment]
I mean we do that as well. props like bsStyle and whatnot aren't used explicitly though. On a slightly different note this seems like an unneeded performance regression. There is no harm in passing in them through, since React is going to skip over them anyway, and the warning isn't useful to users since it doesn't catch the cases you might actually care about, which is props named thate same as DOM attributes that aren't really. Like `target` or `title`.

**Comment by jochenberger** [comment]
Yes, the warnings aren't useful, but they fill the console and distract from warnings that might be logged for users' code.

**Comment by jochenberger** [comment]
I guess we can close this in favor of #1994.

**Comment by andrewmclagan** [comment]
ahhh you all beat me to it.
