### ISSUE TITLE
Question: Modal show property

### ISSUE THREAD

**Issue by perrin4869** [react-bootstrap/react-bootstrap#1981]
I've seen some other react modals not using a `show` property, and instead opting for opening and closing the modal according to whether or not the modal is being rendered or not. I think that semantically speaking that makes more sense. Is there any reason `react-boostrap` isn't using that kind of API? Thanks!

**Comment by jquense** [comment]
the big reason is that you can't have the Modal own it's exit animation if it's only displayed on render since a component cannot delay it's own unmounting. The show prop also mirrors the bootstrap API, along with the native dialog API.  other than that I think an explicit visibility prop is more ergonomic of an api

**Comment by perrin4869** [comment]
Well, arguably, the reasons bootstrap api and native dialog API behave in a way similar to a react `show` prop is that they just don't have a concept of mounting and unmounting components like react does... and there has to be a way to animate a leaving component, otherwise `ReactCSSTransitionGroup` couldn't work.
