### ISSUE TITLE
Wrong error message when attaching a string `ref` to a custom Dropdown toggle button

### ISSUE THREAD

**Issue by jochenberger** [react-bootstrap/react-bootstrap#1993]
I have a custom `Button` as a `Dropdown` toggle. I attached a `ref` to it because I want to create an `Overlay`/`Tooltip` and want to use the `Button` as the `target`.
My code looks like this:
```javascript
<Dropdown>
  <Button ref="button" bsRole="toggle">...</Button>
  <Dropdown.Menu>
    ...
  </Dropdown.Menu>
</Dropdown>
```
The code leads to a warning: "String refs are not supported on `<Dropdown.Toggle>` components."
I think that this is a bug because I'm not even using the `<Dropdown.Toggle>` component. Actually I *was* using it, but switched to a custom button because of that warning.

**Comment by jquense** [comment]
The error message is a bit confusing, but it means that they are supported on that specific component _or_ any component filling the toggle bsRole, such as your Button above.

**Comment by jochenberger** [comment]
Could you please tell me the reason for that? I cannot think of a technical reason to prevent me from using a string ref there.

**Comment by jquense** [comment]
The implementation of the Dropdown requires it add a ref to the Toggle component, if you use a string ref it will replace it and your ref won't work. If you use a function ref they can both be applied since you can compose functions. This has always been the case, we only recently switched to warning about it, whereas before it would just silently ignore and replace the ref

**Comment by jquense** [comment]
Switch to using: `<Button ref={ref => this.button = ref} />` and everything will work fine.

**Comment by jochenberger** [comment]
Thanks for the explanation. I recommend rephrasing the warning to be less confusing though.
