### ISSUE TITLE
Make Input form group rendering optional?

### ISSUE THREAD

**Issue by yrashk** [react-bootstrap/react-bootstrap#205]
Hi,

I have a case where I can't possibly put two checkboxes close to each other vertically (in the same form group) and this doesn't look perfect. When the second checkbox is moved into the same group (manually, using Web Inspector), things look much better. Is there any chance we can have a boolean property for this? If necessary, I can do a pull request.

Thanks!

**Comment by taion** [comment]
:+1: 

As it is, it's impossible to get something like the checkbox/radio box groups in http://getbootstrap.com/css/#checkboxes-and-radios with `Input` elements, without manually mucking with `margin-bottom` or something.

**Comment by mtscout6** [comment]
This would be a welcomed change.

**Comment by taion** [comment]
Sure. What do you think of making it controlled as `<Input formGroup={false} ... />`? Or maybe `showFormGroup`? `useFormGroup`?

**Comment by mtscout6** [comment]
Sitting down and thinking this through a little deeper this morning. This issue
has a lot of similarities in the desire that #342 is requesting, and the two
should really be done together.

I think we should extract smaller components, where some are not publicly exposed.

We could add these components publicly:

- `RadioGroup`
- `Radio`
- `CheckboxGroup`
- `Checkbox`
- `TextArea`
- `TextInput` - With with `type` prop to support password, email, etc.
- `FileInput` - This one doesn't even work with our current implementation, but
  we should figure this one out at some point.
- `Select`
- `Static`
- `Submit`

@ivan-kleshnin Correct me if I missed one.

The public components would make use of these private components:

- `FormGroup` - Generic `form-group` and validation wrapper
- `InputGroup` - Generic label, help text, and addon wrapper

Each control than can should implement a `getValue()` function.

Since checkboxes do not correlate with each other the way radios do with the
name property, I'm thinking they'd be different group types. This gets
especially difficult when figuring out how to implement a `getValue()` function
for the two different groups.

Example form when all is said and done:

```
class MyForm extends React.Component {
  render() {
    return (
      <form>
        {/* type prop defaults to 'text' */}
        <Input label='Text' placeholder='Enter text' />
        <Input type='email' label='Email' placeholder='Enter email' />
        <TextArea label='Text Area' placeholder='textarea' />
        {/* inline prop optional */}
        <CheckboxGroup inline>
          <Checkbox label='Package 1' checked />
          <Checkbox label='Package 2' />
          <Checkbox label='Package 3' checked readonly />
        </CheckboxGroup>
        {/* inline prop optional */}
        <RadioGroup name='radio-name' checked='option1' inline>
          <Radio label='Option 1' value='option1' />
          <Radio label='Option 2' value='option2' />
          <Radio label='Option 3' value='option3' />
        </RadioGroup>
        {/* multiple prop optional */}
        <Select label='Select' placeholder='select' multiple>
          <option value='select'>select</option>
          <option value='other'>...</option>
        </Select>
        <Static label='Static Text'>Static value</Static>
        <Submit>Submit button</Submit>
      </form>
    );
  }
}
```

I know this introduces a lot of work and really isn't a quick solution, but I
feel that something like this would allow the flexibility that everyone is
looking for, and significantly simplify what is now a very large component.

Thoughts?

/cc @joemcbride

**Comment by taion** [comment]
That looks much cleaner than the status quo. Would this then have something like:

```html
<TextInput type='text' standalone />
```

if I want just an input element without the `.form-group` surrounding it, plus validation that no label is specified?

This is a larger refactoring that is more along the lines of #324, though, and is a bit orthogonal to this issue. But this issue is also not a big deal to me because I can just use `groupClassName` to get rid of `margin-bottom` on the `.form-group`, which is good enough for now.

Might make more sense to move discussion to #324 though.

**Comment by mtscout6** [comment]
I was reading between the lines a little bit on this since the original description highlights a concern of grouped checkboxes and radio buttons.

**Comment by taion** [comment]
Alternative is something like e.g.

```html
<FormGroup label="label" hasFeedback><TextInput type="text" /></FormGroup>
```

if you want a `.form-group` and label, but just

```html
<TextInput type="text" />
```

if you don't, but this seems to have much worse ergonomics for the normal use case, and only benefits a very small edge case.

In my case I am actually hitting this for a text input. Trying to build something a bit like the GH issues label selector, and I don't really want the filter element to end up in its own `.form-group`, because it's part of a larger composite group.

**Comment by mtscout6** [comment]
In that case a standalone prop makes sense.

**Comment by mtscout6** [comment]
@taion How does 8f8886a look to you?

**Comment by taion** [comment]
This looks great to me. Thanks!
