### ISSUE TITLE
Tab switch re-render the page on every switch

### ISSUE THREAD

**Issue by agarwalvinit** [react-bootstrap/react-bootstrap#2062]
I am using Tab component of react-bootstrap@0.29.5, When I am switching the tab, it is calling render method of the component containing the tab. Ex-
Tab component:-
MainTab.js:-
```
var React = require('react');
var ReactDOM = require('react-dom');
import { Tab, Tabs } from 'react-bootstrap';
import Test1 from "./test1";
import Test2 from "./test2";
var Test3 = React.createClass({
  render: function() {
    return (
     <Tabs defaultActiveKey={2} id="uncontrolled-tab-example">
      <Tab eventKey={1} title="Tab 1"><Test1 /></Tab>
      <Tab eventKey={2} title="Tab 2"><Test2 /></Tab>
      <Tab eventKey={3} title="Tab 3" disabled>Tab 3 content</Tab>
    </Tabs>
      );
  }
});
ReactDOM.render(<Test3 />, document.getElementById('main'));
```
test1.js:-
```
import React from "react";
var Test1 = React.createClass({
	render: function() {
		return (
			<div>
				Test1
			</div>
		);
	}
});
module.exports = Test1;
```
test2.js:-
```
import React from "react";
var Test2 = React.createClass({
	render: function() {
		return(
			<div>
				Test2
			</div>	
		)
	}
});
module.exports = Test2;
```
switching from test1 to test2 it calls the test1 render function first and then test2. This happens twice. Is it correct ? Why on tab switch the render function is getting called if there is no state change ?

**Comment by jquense** [comment]
it is correct. the tab state changes when you switch tabs and so rerenders (to hide one tab and show the other). React works by rerendering entire trees so you inner components also rerender. This is really normal in React, rerenders happen all the time, which is fine because they are very cheap since react only changes the DOM when your component actually changes

**Comment by agarwalvinit** [comment]
But why is it happening twice in same component i.e 2 times per tab. It should only render it once. right ?

**Comment by jquense** [comment]
there are a bunch of different updates happen, the main point tho here is that you shouldn't be checking how many times render() is called, its an irrelevant metric in React.

**Comment by kahramanfurkan** [comment]
I have the same problem. After a long effort I found the solution...

Setting the unmountOnExit prop to true prevents the DOM from rendering all tabs at once.But even if unmountOnExit is true, when you switch between Tabs, you will still see the child component rendered twice.This is because the transition value renders the <Tab/> component again.You must set transition to false.So to make sure that the child component is rendered only once, you should edit your code like this:

```
<Tabs
    activeKey={activeKey}
    onSelect={onTabChange}
    unmountOnExit={true}
    mountOnEnter={true}
    transition={false}>

{children}

</Tabs>
```
