### ISSUE TITLE
Transition to 0.29

### ISSUE THREAD

**Issue by deser** [react-bootstrap/react-bootstrap#2124]
Hi Guys,
seems it's almost impossible to level up from 28.* to 29 due to FormControl. I'm trying to change Input to FormControl , CheckBox, Radio, etc... but it's really too hard.You are advising to create own wrappers like 
```
function FieldGroup({ id, label, help, ...props }) {
  return (
    <FormGroup controlId={id}>
      <ControlLabel>{label}</ControlLabel>
      <FormControl {...props} />
      {help && <HelpBlock>{help}</HelpBlock>}
    </FormGroup>
  );
}
```

But this will fail in new react with warnings. 
My point is that for mature applications we'll need to implement almost the same `<Input />` like it was in 28.* . It was good as an abstraction layer from real DOM. We were able to write generic rendering functions for every type of control easily. Now we need not just to change previous `Input` to `<FormGroup><CheckBox/>...` but consider to change high level rendering logic as well. This is really weird to my mind. I'd say it was the most disappointing update...

**Comment by taion** [comment]
It'd work or fail in 15.2 the same as Input. If you're passing in unknown props to FormControl, it will warn. If you don't, it won't.

**Comment by deser** [comment]
The problem is deeper...

**Comment by jquense** [comment]
The old controls were not a good abstraction, they failed to cover very basic and common use cases such as horizontal forms well. Agree that this is a tough thing to update from, we also feel the pain having applications using RB, but the old API just was not tenable for a library. If it did happen to work for all your use cases then we encourage you to wrap up your own abstractions that fit your needs, like we have. However, it was clear from issues, bugs, and use that the old API didn't meet everyone's needs, and worse, actively prevented folks from using the components in common cases due to the lack of flexibility in the API

**Comment by deser** [comment]
How about return old abstractions using new controls inside?

**Comment by taion** [comment]
There's nothing to offer. That `<FieldGroup>` component is it.

Checkboxes don't get rendered the same way in Bootstrap anyway, so a generic labelled field group component has no business handling checkboxes.

**Comment by deser** [comment]
`That <FieldGroup> component is it.`
That's not true. It only renders but doesn't give interface (getValue, getChecked, etc...)

**Comment by taion** [comment]
Why should it? Use a controlled component or expose a ref. That API was busted and unusable in most use cases because of HoCs.

**Comment by taion** [comment]
The point of React-Bootstrap is not to present a half-cocked form input API that somehow makes it seem like less of an anti-pattern to use uncontrolled React components.

It's an intentional design choice here to expose exactly the React API for dealing with inputs. This is a component library, not a generic form input library.

**Comment by deser** [comment]
Ok, thanks guys
