### ISSUE TITLE
Prevent render cascade of modal on exit animation

### ISSUE THREAD

**Issue by msaspence** [react-bootstrap/react-bootstrap#2165]
If I do this

```
module.exports = function(props) {
  return (
    <Modal show={Boolean(message)}>
      <Modal.Body>
          <h2>{message}</h2>
      </Modal.Body>
    </Modal>
  );
}
```

When I unset `message` the modal animates off screen but the message is removed from the modal before the animation ends. This may be expected behaviour? But there are a couple of problems with this. 

* It is not consistent with `ReactCSSTransitionGroup`, which does freeze child rendering until the exit animation is complete
* There are a couple of works arounds:
  * Separate the data for the modal content and whether to show the modal. The problem with this is if you don't want to display the modal because the content it contains is no longer in your applications state (for example a record was deleted) depending on your application you cay have to do all kinds of gymnastics to keep that data in state.
  * Hack your own component that prevents the cascade, inside `Modal` but outside `Modal.Body`. This seems like a hack and something that should be build into `Modal`, at least under a config option.

*Note:* I suspect this is actually a problem with `react-overlays`'s `Transition`, and therefore affects anything built on that, including anything else using `Fade` or `Collapse`

**Comment by jquense** [comment]
This discussion more properly belongs in react-overlays, but I go back and forth on whether this should be built in. "freezing" the children while animating out _is_ the behavior you want in the case you describe, however I don't think it's the 1. the common case, and 2. true for all other cases.

> It is not consistent with ReactCSSTransitionGroup, which does freeze child rendering until the exit animation is complete

This isn't strictly true, it caches, the children in order to control multiple ins and outs, it's not something that makes sense, or is feasible for Transition to do here. In the past to deal with this I usually create my own Application or DataModal that listens for changes in visibility and uses a StaticContainer (like relay) to disable updates during the transition.

**Comment by taion** [comment]
Yeah, I think that's too specialized to apply here. `<StaticContainer>` in user space is probably the right thing here.
