### ISSUE TITLE
Can not disable a TabbedArea tab

### ISSUE THREAD

**Issue by tomgoldsmith** [react-bootstrap/react-bootstrap#217]
One of the props on a Nav is "disabled". This prop should be usable on the TabbedArea tabs to disable tabs.

**Comment by AlexKVal** [comment]
Can you please clarify ?
Is that a question or a feature proposal / request ?
Does it relevant yet ?

**Comment by AlexKVal** [comment]
In case of need, we'll reopen it.
I'm closing it.

**Comment by traviscooper** [comment]
Having same issue.

**Comment by mtscout6** [comment]
I'm not seeing [documentation](http://getbootstrap.com/javascript/#tabs) for this with Bootstrap. Though I can see the benefit to supporting something like this. Since the underying tab is just an anchor, I don't think this would be hard to implement nor would it be compromising to Bootstrap parity.

I'm assuming that you are looking for something like this:

![](http://cl.ly/image/3x2q3o1m2N3C/Screen%20Recording%202015-05-13%20at%2008.46%20AM.gif)

I monkey patched things to make that screen recording work, but it should be as simple as adding the `disabled` class to the `li` and adding some JavaScript to not activate the tab when it's disabled.

Of course the change will need tests and added documentation.

@traviscooper and @tomgoldsmith I think a PR for this would be awesome, and incredibly useful.

**Comment by traviscooper** [comment]
I have a small patch I was preparing, shall I send it? :)

**Comment by traviscooper** [comment]
If you pass the 'disabled' prop, straight through from TabArea -> TabPane -> NavItem, then it properly adds the disabled class to the tab and picks up the disabled functionality to not show the content as well.

**Comment by traviscooper** [comment]
https://github.com/react-bootstrap/react-bootstrap/pull/655 to fix this issue.

**Comment by mtscout6** [comment]
Well that was fast! Give me some time to review it :smile:
