### ISSUE TITLE
can't attach onMouseOver / onMouseOut events to NavDropdown

### ISSUE THREAD

**Issue by modosc** [react-bootstrap/react-bootstrap#2180]
not sure if this is by design or not - [this line](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/NavDropdown.js#L58) explicitly passes these props to the `Dropdown.Toggle` child element so there's no easy way to get them to stick.

my usage case is a `NavDropdown` that opens / closes on `mouseOver` / `mouseOut` - if the handlers are attached to the `Dropdown.Toggle` then moving from the toggle to the actual menu causes a `mouseOut` event to emit and the menu closes. attaching the handlers to the `NavDropdown` means that events from the toggle and menu bubble up and things work as expected. 

for now i'm just using a locally patched class that doesn't pass these props on but i'm curious of the reasoning here (and whether my solution will cause some other breakage?)

**Comment by jquense** [comment]
if you want to more finely control how props are passed to components you need to use the `Dropdown` component directly. The reason for the behavior in the NavDropdown and DropdownButton is because you almost always want to pass props to the toggle in the general use cases. In your case, you need the lower level API
