### ISSUE TITLE
[Feature] Add `.getValue()` to `FormControls`

### ISSUE THREAD

**Issue by crobinson42** [react-bootstrap/react-bootstrap#2196]
I was looking to start migrating several projects from React v0.14 to the most recent and I was suddenly stunned noticing this simple functionality is no longer available on FormControl Components. After reading through issues, public forum, and stackoverflow it seems there are A LOT more users interested in this being a feature of `react-bootstrap`.

[https://github.com/react-bootstrap/react-bootstrap/issues?utf8=%E2%9C%93&q=getValue()](https://github.com/react-bootstrap/react-bootstrap/issues?utf8=%E2%9C%93&q=getValue())

It's mentioned in #2124 that this is a Component library [and not a generic input/form library] which seems accurate, however, I feel it's important to provide some functionality here on FormControls re Bootstrap. It's not asking much, is it?

#1879, #1838, #1856, #1879, #1890

**Comment by taion** [comment]
Our official position here remains the same. We don't want to add an additional API for reading form contents beyond what React itself offers.

If you're looking for this, you have the required pieces to build this yourself on top of the components exposed here. This is in general not the right way to handle inputs in React, though.

**Comment by jquense** [comment]
Hi there. As noted in the various issues you've rounded up and more specifically here: https://github.com/react-bootstrap/react-bootstrap/issues/1821#issuecomment-231553361 Imperative API's are essentially an anti pattern in React. The most idiomatic API for managing values in our input components is the same as the native inputs, controlling the value via `onChange`. We'd rather steer people towards the best usage rather than adding API's that should only be used as escape hatches anyway.

Especially considering that adding this API save you almost nothing in terms of ease of use or usability, while at the same time signalling that this is a good way to manage form values in React.
```
this.refs.input.getValue()
```

vs

```
FindDOMNode(this.refs.input).value
```

We are going to push folks towards controlled inputs, and let them use the React escape hatches for when that isn't feasible or suit their use case.

**Comment by bobholt** [comment]
Not going to open yet another issue, but Dan Abramov has expressed the intention of the React team to deprecate `findDOMNode` in the future, as it blocks evolution of the library. He's taken the first step of making it throw errors in ESLint: https://github.com/yannickcr/eslint-plugin-react/issues/678#issue-165177220

If you don't want to add an imperative `getValue` method, there's no harm in exposing the raw DOM Node as a property of FormControl, which would allow the user to obtain it without using `findDOMNode`, and future-proofing their code.

**Comment by jquense** [comment]
If findDOMNode is deprecated then we will expose an inputRef prop, but we aren't jumping to invent api's on the discussion of the removal of another. especially since we have no idea what will replace it. As you can see from that issue both of us are highly active  in the discussion and aware of it. thanks!

**Comment by taion** [comment]
I wouldn't be opposed to adding `inputRef` anyway. It would hide the implementation detail regarding `<FormControl>`'s DOM node being an `<input>` a little bit better – plus we already have it on `<Checkbox>` and `<Radio>` anyway.

**Comment by danday74** [comment]
Any movement on this? currently being forced to use FindDOMNode but am getting warnings about its usage. I want to move away from it now.
