### ISSUE TITLE
Focus will not be set for active tab

### ISSUE THREAD

**Issue by akkie** [react-bootstrap/react-bootstrap#2220]
Please see this [fiddle](https://jsfiddle.net/uLgfkfuq/1/). If I select a tab from the dropdown then the dropdown retains focus. I think it would be better if the selected tab receives the focus.

I've also tried to set focus on the DOM element directly in the `onEntered` handler. But this does not work.

**Comment by jquense** [comment]
There isn't much we can do about focus behavior as combine components together. We work to make sure that focus behaves correctly for each individual component to meet a11y standards, but we can't define all possible interactions between our components, especially something like this where its just not possible to even know that is what is happening.

I'd move focus in the setState callback, or wrap the current logic in a timeout maybe so it occurs after the focus is moved to the dropdown

**Comment by akkie** [comment]
The combined component was only an example to show that the tab doesn't receive focus when it's set as active. This has nothing to do with combined components in general. I've searched through the code and found some components that can gain focus. So the question is, why does an active tab cannot get focus? In my opinion, an active tab should also get focus if a `tabIndex` is set for it.

Anyway, the issue in the previous fiddle was, that no `tabIndex` was set for the tabs. This [fiddle](https://jsfiddle.net/uLgfkfuq/2/) works as expected.

**Comment by jquense** [comment]
i'm not sure what you are asking. We aren't going to shift focus to the tab is programatically change it to active. The tabs can and _do_ receive focus. Pressing the tab key demonstrates that through and you'll see that the active tab is focused, using the arrow keys changes the active tab.

**Comment by soichih** [comment]
When I change the current tab programatically, sometimes the tab that was previously selected stays "focused" to make it look like this.

![image](https://user-images.githubusercontent.com/923896/224116899-810d2f49-cd6b-4a55-ac61-3eb69c952438.png)

The right most tab was previously selected, and I've changed the active tab to the middle. As you can see, the focus on the right tab is still focused and because of the bootstrap style 

```
.nav-tabs .nav-link:hover, .nav-tabs .nav-link:focus {
    isolation: isolate;
    border-color: var(--bs-nav-tabs-link-hover-border-color);
}
```

It shows the light border around the right most tab.

I believe that react-bootstrap tabs should call blur() on the previously selected item to prevent this from happening.

**Comment by Teajey** [comment]
If it helps anyone else, in my case I tacked this `controlled-tabs-focus-fix` class onto the `Tabs` component:
```css
.controlled-tabs-focus-fix .nav-link:focus:not(.active) {
  border-color: transparent;
}
```
