### ISSUE TITLE
Need More Enhancement

### ISSUE THREAD

**Issue by onlyongunz** [react-bootstrap/react-bootstrap#2253]
All of your Component need a constant behaviour. Seriously, your component are pretty painful to use if for each Component has different behaviour. E.g. Checkbox and Radio should have same behaviour with FormControl, but instead of using `ref`, you use `inputRefs` which is require passing a function that i even didn't know what kind of function it should be.

Btw, i think you need to improve your documentation too... it's not quite clear how to use your component, since every sample mostly have a BIG block of code. Add more commentary, or at least don't make us scroll too much.

Thanks!

**Comment by dozoisch** [comment]
All the different inputs can be used exactly as you would use HTML inputs. They have been design to provide the same API as a normal input. You can pass an onChange callback and value  just like you would on a normal `<input>` tag. 

Now, the reason why the property is called inputRef instead of ref it's because ref is a special react prop that will not be accessible from the component. The function passed in inputRef is EXACTLY the same function type you would pass in a normal react ref. See https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute for more information. Also, the function IS documented right here with an example:
![image](https://cloud.githubusercontent.com/assets/4422516/19052718/b7060f64-896c-11e6-9a84-78dddd897656.png)
