### ISSUE TITLE
Carousel component does not include all accessibility labels

### ISSUE THREAD

**Issue by cvincent** [react-bootstrap/react-bootstrap#2256]
I'm currently working on bringing a project using React Bootstrap up to ADA compliance. One of the issues we have is the Carousel component doesn't render all of the accessibility labels given in the example template in the Bootstrap documentation, specifically the "Next" and "Previous" labels.

Are these labels actually present but perhaps I'm missing some option to have them render? If not, I'd be happy to see if I can provide a pull request to bring this functionality in.

**Comment by jquense** [comment]
we don't usually have an option to disable a11y stuff, so if you aren't seeing it it probably isn't there,  which makes sense as the Carousel doesn't get a lot of love. We always appreciate PR's adding in a11y support

**Comment by ghusse** [comment]
I looked at the code, and you can add accessibility labels by setting the prevIcon and nextIcon properties. Instead of a glyphicon component, you can set it to a div containing an icon and a sr label.

I tried to add it to the code, and I seem to have 2 possibilities

- change the default icon component (but I need to add a level in the DOM)
- add them in the code, and add 2 more properties to the API of this component, allowing to customize the labels (previous and next by default)

**Comment by ghusse** [comment]
I think we can close this issue now, as my PR has been merged.
