### ISSUE TITLE
Static Modal does not work with closeButton={true}

### ISSUE THREAD

**Issue by vladimir-rovensky** [react-bootstrap/react-bootstrap#2450]
Hey everyone,

I came across an issue with the Modal component - when used as simple static html component (very first use case in the docs), and setting Modal.Header's closeButton=true, it crashes and doesn't render anything. Seems to be because the context is not initialized properly. I work around this by setting up the context in our wrapper component, but it should probably just work.

Example:
```
<Modal.Dialog>
      <Modal.Header closeButton={true}>
        <Modal.Title>Modal title</Modal.Title>
      </Modal.Header>

      <Modal.Body>
        One fine body...
      </Modal.Body>

      <Modal.Footer>
        <Button>Close</Button>
        <Button bsStyle="primary">Save changes</Button>
      </Modal.Footer>
</Modal.Dialog>
```

**Comment by joelseq** [comment]
I'm pretty sure if you want to have the closeButton prop you need to wrap the entire thing inside a <Modal> otherwise it doesn't really make sense since the closeButton prop is supposed to fire the onHide of its parent Modal which in turn can be used to set the show prop of the Modal to false. The basic example is used to illustrate what the Dialog itself inside the Modal will look like and isn't actually a Modal.

**Comment by vladimir-rovensky** [comment]
I have to disagree, the first use case is perfectly valid - I just want to render the Modal.Dialog and handle its showing/hiding myself. This makes the component much more flexible and usable - you have means to render just the modal as a siple React component and nothing else, no overlays, no portals. We have been using it this way for ages and it always worked.

To your second comment, the closeButton can just fire the onClose callback from the Header props, it doesn't have to crash if the context value is not there. This seems to be the intent in code as well (from the ModalHeader source):
```
  /**
   * A Callback fired when the close button is clicked. If used directly inside
   * a Modal component, the onHide will automatically be propagated up to the
   * parent Modal `onHide`.
   */
  onHide: React.PropTypes.func,
```
Nothing here says you HAVE to use it within Modal, there's simply no need to couple the two components like this.

**Comment by joelseq** [comment]
@vladimir-rovensky I think that comment is a little ambiguous but what I understood from it is that you can directly put onHide in the parent Modal and not have to put it inside the Modal.Header as the `createChainedFunction` util will automatically take care of that. So basically it's like you can choose to put it either in Modal or Modal.Header. I see no mention anywhere in the docs saying that Modal.Header can be used independently of Modal. Here's a quote directly from the docs:
```
A modal with header, body, and set of actions in the footer. 
Use <Modal/> in combination with other components to show or hide your Modal. 
The <Modal/> Component comes with a few convenient "sub components": 
<Modal.Header/>, <Modal.Title/>, <Modal.Body/>, and <Modal.Footer/>, 
which you can use to build the Modal content.
```

Also, I have to disagree with you as well on the first use case as a Modal is technically an overlay which is why the docs have listed it under the [Overlays section](https://react-bootstrap.github.io/components.html#overlays). It sounds to me like your use case is you want a dialog to show / hide depending on a certain input and you are trying to use sub components of the Modal component to make it work. If this is the case, then it is totally valid for you to set up the context yourself and not have to expect it from the library as this library is intended to mimic the same functionality provided by the bootstrap library.

**Comment by jquense** [comment]
the close button prop on the header doesn't make much sense if you aren't making a closeable modal, but I don't mind making it not throw a hard error there. if anyone wants to PR the fix (it's 1 line). 

as a work around I'd leave off the prop and add a close button to the header manually

**Comment by joelseq** [comment]
@jquense would you like it to throw an invariant warning or just work regardless?

**Comment by taion** [comment]
`<Modal.Header>` does accept an `onHide` prop. I'd say let's replace `modal.onHide` with `modal && modal.onHide`.

**Comment by vladimir-rovensky** [comment]
joelseq's PR fixes this perfectly. I understand the main use case for Modal.dialog is with the Modal wrapper, but I think this is still worth supporting. You have a simple dialog that renders in place and calls your onHide callback (whatever it may be) when the user clicks the close button. Makes it more flexible and customizable in my opinion. 
Note that the wrapper brings with it some extra complexity, e.g. the Portal's render() returns null, meaning ReactDOM.findDOMNode will return null as well, it's harder to locate the modal in unit tests, since it's rendered into document root etc. Nothing you can't work around, but sometimes it is just more convenient to render the bare dialog without the overlay.

**Comment by taion** [comment]
Right no this is fine. In a perfect world we'd put this context setup on `<Modal.Dialog>`, except that would mess with custom `dialogComponentClass`. Anyway I'm okay with this for now.

**Comment by taion** [comment]
fixed now
