### ISSUE TITLE
Unclear that some elements expect specific child elements

### ISSUE THREAD

**Issue by Relequestual** [react-bootstrap/react-bootstrap#2479]
Having resolved #2474, I notice the documentation doesn't specify that you can't add your own child elements without wrappers.

> The Nav component injects props automatically into the child elements, because it expects them to be NavItems.
> You need to create a wrapper component that doesn't forward the props to the li tag.
(https://github.com/react-bootstrap/react-bootstrap/issues/2474#issuecomment-279432492)

This is fine, but I would have had no idea this was the reason for the errors I was seeing. I didn't realise that parent elements could inject properties to child elements.

Shouldn't this sort of thing be documented?

(BTW, I'm really impressed with the open to closed ratio for issues! Great work!)

**Comment by jquense** [comment]
>  doesn't specify that you can't add your own child elements without wrappers.

This is a bit wrong. you _can_ use any component without wrappers, but as of React v15.3 you get those warnings. The problem is really that React decided that it's not going to automatically filter out props that aren't real html attributes on DOM components. Up until the last few versions of React this all worked fine. It still works fine, but you get warnings. 

In other words there isn't anything special about the behavior here except that React is warning about passing props the `li` doesn't recognize. I agree that we could make the documentation clearer on these points, since folks are getting tripped up on it now.

**Comment by Relequestual** [comment]
Ah. OK. I do remember reading a few comments of people reverting back to older versions of react to "fix" the problem. I would guess that you wouldn't expect to see these warnings when you compile your service for production?

Is the React team trying to say that this common practice as you put it in the other related issue, is no longer desierable?

**Comment by taion** [comment]
it's a relatively trigger-happy warning; in future versions those props will just get passed through as HTML attributes, which usually will be harmless
