### ISSUE TITLE
[Feature Request] OverlayTrigger multiple placement values

### ISSUE THREAD

**Issue by alexcastillo** [react-bootstrap/react-bootstrap#2499]
Hi!

Great work!

I could see the use case for a more complex OverlayTrigger placement. 

For example: `placement={ ['bottom', 'left'] }`

The secondary argument would be the alignment for the X axis.
Would you be interested in a PR for this enhancement with backward compatibility in mind?

Best,

Alex

**Comment by jquense** [comment]
e are open to adding more placement options (see: https://github.com/react-bootstrap/react-overlays/issues/52) however this will mostly likely involve custom css to get it working with bootstrap tooltips or modals, which we aren't willing to add to RB. If you just wnat the functionality to make it into Overlay and OverlayTrigger for use with a custom tooltip then please go for it. (going to close this issue here, please add more in react-overlays)

**Comment by alexcastillo** [comment]
Thanks for your reply! 
I'll follow-up on the react-overlays project.

**Comment by devongovett** [comment]
Made a pull for react overlays to address this: https://github.com/react-bootstrap/react-overlays/pull/175

**Comment by alexcastillo** [comment]
Cool!
