### ISSUE TITLE
Tabs component's new mountOnEnter doesn't do anything

### ISSUE THREAD

**Issue by alisman** [react-bootstrap/react-bootstrap#2506]
@taion thanks for your attention to onMountEnter issue.  Unfortunately, it doesn't seem like the new property is doing anything.  When I set unmountOnExit to true, only the initial tab shows up in the DOM.   I would expect this behavior to occur when mountOnEnter is set to true, but that's not the case in my testing.  (incidentally, unmountOnExit probably should NOT work this way).  I searched the codebase for mountOnEnter and I don't see this property actually used anywhere.  Your PR passed it down to the tab pane but it doesn't get referenced. 
Let me know if you want me to do a PR for this or if you would rather handle it.

**Comment by taion** [comment]
it gets passed to the react overlays. make sure you have the latest versions installed

**Comment by alisman** [comment]
overlays?

**Comment by jquense** [comment]
delete you node_modules and reinstall, making sure you have the latest version of everything

**Comment by alisman** [comment]
Hi guys, 
I reinstalled.  Checked version # in node_modules folder.  I have the latest.  But all tabs are still mounted in DOM.

**Comment by alisman** [comment]
Ok, I see it works now, but only if animation is set to true : (

**Comment by jquense** [comment]
yup it's a feature of the transition (animation) component!

**Comment by tomhalley** [comment]
Hi, same problem and thanks for fix. Can we decouple animation from mountOnEnter? I don't want my tabs to have animation, but I want the lazy loading, and I'm sure I'm not the only one.

**Comment by timrichd** [comment]
Also encountered this issue, is there a work around yet?

**Comment by RKushnir** [comment]
@timrichd Do you have `animation` enabled? Otherwise it doesn't work.
https://github.com/react-bootstrap/react-bootstrap/blob/08af669075b3576110e2e1801313bb96ca522cd7/src/TabPane.js#L262
https://github.com/react-bootstrap/react-bootstrap/blob/08af669075b3576110e2e1801313bb96ca522cd7/src/TabPane.js#L228

**Comment by dpetranek** [comment]
This is the workaround that we use:

Since the animation prop can actually accept a boolean or a react-transition-group Transition, we can achieve the no-animation effect and retain the lazy-loading by creating this Transition component:

```
const Quick = (props: any) =>
    <Transition {...props} timeout={1}>
        { props.children }
    </Transition>
```
Note the timeout value of 1ms.

Then we pass our custom transition as the animation prop:

```
<Tabs {...this.props}
      animation={(Quick as any)}
      mountOnEnter={true}
      unmountOnExit={false}/>
```

(The `(Quick as Any)` is to fool Typescript into allowing a non-boolean argument)
