### ISSUE TITLE
Significant delay on hiding custom overlays

### ISSUE THREAD

**Issue by allenylzhou** [react-bootstrap/react-bootstrap#2513]
When you have two custom overlays (think hover menus) that are triggered by hovering over a button, it takes a noticeable amount of time for one to hide before the next one shows:

https://jsfiddle.net/mhbLd8uo/

**Comment by dekelb** [comment]
There is a default animation for overlays.
You can set the animation to `false` and it will remove this delay:

https://jsfiddle.net/mhbLd8uo/1/

However - it would be nice if we could have access to the duration of this animation.

**Comment by jeffcstock** [comment]
It looks like this issue was closed without any resolution. Alternatively, there is no visible animation to the entering of the overlay, just the exit, as shown here: https://react-bootstrap.github.io/components.html#custom-overlays

Is there any way to access the duration of the animation without setting `animation={false}`?

I need to access the `onEntered` callback, but setting animation to `false` disables each of the transition callbacks. Therefore, it's impossible to access those callbacks without having an undesirable delay.

**Comment by taion** [comment]
There is a small animation there. It's just quick.
