### ISSUE TITLE
DropdownButton does not blur after selected

### ISSUE THREAD

**Issue by guiferrpereira** [react-bootstrap/react-bootstrap#2553]
When using `DropdownButton` with some `<MenuItem onClick={somePath}>` and the path that we open doesn't focus nothing, the button keeps selected. 

So it would be nice that the component have some `autoBlur` option that would do something like this:

`<DropdownButton onSelect={() => document.activeElement.blur()}`>

**Comment by jquense** [comment]
hi there, dropping focus would be an accessibility anti-pattern, and just be broken for anyone using a keyboard to navigate. it's not something we'll add to RB and I'd strongly reconsider doing it in your own app. thanks!

**Comment by villesau** [comment]
@jquense is there any way to make blur happen programmatically? This behaviour totally kills usability as we need to be able to focus back to input after item is selected so that user does not have to manually click back to input after selecting an item from dropdown. I tried to get handle to DropdownToggles ref, but it doesn't have blur method. It's not very good framework design to make decisions like this. It limits the application developers ability to make smooth ux possible.

**Comment by jquense** [comment]
The current behavior for focus is the correct _speced_ behavior for dropdown menus according to w3c authoring standards. It works the same as a select input which keeps focus on the input once an item is selected. That said you can handle this case the same as you might with the select input. After the item is selected manually move the focus to where you want it (e.g. away from the button). So rather than try and blur the dropdown (which would just leave nothing focused), move focus to where you want it

**Comment by villesau** [comment]
@jquense thanks for quick response! 
I'm working on input using slate.js (http://slatejs.org/#/rich-text ), where i can explicitly define that it has focus either using state trasform object, or focusing to editor component using ref. But even when  i've selected what i want from dropdown, and said to slate editor to focus it self, the dropdown still retains focus. That's why i want to explicitly blur it.

**Comment by villesau** [comment]
@jquense i guess this is the reason, see the order of console log messages:

menu item on select <-- when MenuItem onSelect is called
move focus to editor <---- it calls my function to focus back to my component
Dropdown.focus method called <--- this is in Dropdown.focus method, and it's called after i've made my changes -> focus moved back to dropdown

I think this means that it's not possible to move focus anywhere programmatically from dropdown.

**Comment by jquense** [comment]
yeah its not the prettiest but you can put your focus() call in a  `setTimeout(() => input.focus(), 0)` so it is called after the dropdown. I agree that's not the most elegant solution, but focus management on the web is already a mess so the above is sort of par for the course.

**Comment by villesau** [comment]
yep that's what I did as my last resort :( indeed not the prettiest solution.

Thanks for the very active help with this!
