### ISSUE TITLE
order of className

### ISSUE THREAD

**Issue by akwmak** [react-bootstrap/react-bootstrap#2675]
Hi,
I am new to react-bootstrap. I have the following code:

`<Navbar inverse collapseOnSelect fixedTop className="navbar-custom">`

The rendered output is:
`<nav class="navbar-custom navbar navbar-inverse navbar-fixed-top">...</nav>`

Notice the **navbar-custom** is placed in the front (causing my custom css to be ignored), how do I make it to the end of the classes, i.e.
`<nav class="navbar navbar-inverse navbar-fixed-top navbar-custom">...</nav>`

I appreciate your help! 
Thank you. 

akwmak

**Comment by jquense** [comment]
you can't adjust the order of css classes on the element. That is ok however, because the css cascade doesn't care about the order of classes written in the attribute, only the order they are defined in your css and the specificity of the selector. 

to make your class work you need to make it more specific then the existing styles.
