### ISSUE TITLE
Setting Modal content dynamically throws "modalContent.hasAttribute is not a function" error (see console)

### ISSUE THREAD

**Issue by manumid** [react-bootstrap/react-bootstrap#2726]
I need to use one single modal to show content (changing its title, body and footer dynamically). For this, I change it through Javascript events.

Once the user close the Modal (by Close button or "selecting" content), I change its content (waiting to Modal.onExited). Although it works fine, react-bootstrap throws an error "modalContent.hasAttribute is not a function" in the browser's console. If I set a little timeout after Modal.onExited gets called, no error is given.

See fiddle [here](https://jsfiddle.net/manumid/69z2wepo/83357/).

In function onExited (lines 40-50) (called when Modal.onExited gets called):

- If I chose Option 1 (line 44), it throws the error.
- If I choose Option 2 (line 49), no error is given.

**Comment by taion** [comment]
Thanks for the repro. This is happening because the modal node is a comment, which doesn't support `hasAttribute` (or really any of the other methods).

@jquense 

Do you know under which conditions `getDialogElement` can return something falsy in https://github.com/react-bootstrap/react-overlays/blob/7531cf928e40c627373dd3df721e8ea9c09b29b2/src/Modal.js#L517

I wonder if we should just add a "ref holder" component around the dialog.
