### ISSUE TITLE
Can't resolve 'react-bootstrap' in typescript project

### ISSUE THREAD

**Issue by danilNikolaenko1990** [react-bootstrap/react-bootstrap#2745]
here is my package.json
```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@types/jest": "^20.0.6",
    "@types/node": "^8.0.19",
    "@types/react": "^16.0.0",
    "@types/react-bootstrap": "0.0.52",
    "@types/react-dom": "^15.5.2",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-scripts-ts": "2.5.0"
  },
  "devDependencies": {},
  "scripts": {
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  }
}

```

and tscongig.json
```
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}
```

this is my usage
import {Alert} from "react-bootstrap";
or
import * as UI from 'react-bootstrap';

please help, what have I done wrong?

thanks for helping

**Comment by jquense** [comment]
I'm not sure honestly none of us use TS and the types are maintained by someone else. You may have something configured wrong or the type def may be wrong. Unfortunately though I don't know enough to say

**Comment by omaskery** [comment]
Apologies for reviving an old-ish thread, I daresay @danilNikolaenko1990 has long since solved their problem or otherwise worked around it - but this is still one of the top results when researching this problem, so I thought I'd document my solution here.

I'm new to this domain in general, so I'm uncertain of my correctness, but for me: the problem was that I hadn't appreciated that the "@types/abcdefg" modules in npm were _just_ type information, not code. As such having @types/react-bootstrap only defines the interfaces - meaning you need to also have react-bootstrap installed for the dependency to resolve (understandably, because that's where the code "really is").

It seems odd to me that the @types/react-bootstrap package does not have a dependency on react-bootstrap, but perhaps it makes sense when you're more familiar with this area!

Hope this helps someone in the future :)
