### ISSUE TITLE
Modal animation doesn't update as expected.

### ISSUE THREAD

**Issue by smoleniuch** [react-bootstrap/react-bootstrap#2761]
Hi,

I'm trying to create custom ModalManager class and i have problem with showing/hiding animations.I would like to have control how modal will display/hide all the time,for example modal will show up with animation and hide without it.Is there any way to achive such a thing?

Here is some slim example of [ModalManager](https://jsfiddle.net/smoleniuszek/q7g923cq/3/)

Its weird because my code work on first transition but when you press hide button it doesn't overwrite default animation property.I have also noticed that div with modal drop doesn't disappear after last modal hide.

**Comment by jquense** [comment]
So my guess is that your manager is not rendering any modals when their hide is `false`, this causes the modal to unmount immediately, since mounting in React is synchronous. Animation out requires that you wait, until the Modal finishes animating out before removing it overwise the ending animation is cut off. This is why the Modal api is a `show` prop, vs doing something like `show && <Modal />` toggling the prop to true or false keeps it the component mounted the whole time.

**Comment by smoleniuch** [comment]
But the modals does not unmount,they are just hidden.Methods `dsiplay() && hide()` manipluate show property.

**Comment by jquense** [comment]
If you have more than one modal open at the same time that might be the problem as well. That isn't supported on the normal bootstrap modals.

**Comment by taion** [comment]
You need to enable the animation and hide the modal on separate ticks. You can't simultaneously enable `animation` and disable `show`.
