### ISSUE TITLE
Checkbox' id is not set

### ISSUE THREAD

**Issue by TrejGun** [react-bootstrap/react-bootstrap#2765]
text input aka FormControl can get `id` from FormGroup's `controlId`
however Checkbox can't do the same
so htmlFor attribute on associated label points to nowhere 
and I can't check checkbox by clicking on label

https://codepen.io/trejgun/pen/YxjXQZ?editors=1111

**Comment by taion** [comment]
`<Checkbox>` isn't meant to be used in a `<FormGroup>`. The markup for checkbox labels doesn't work that way.

**Comment by TrejGun** [comment]
@taion 
Lets say you are not using Checkbox'es in FormGroup's but this doesn't mean my markup is invalid.
I can create form fields from strings, numbers, arrays and hashes using FormControl and only for booleans I have to use Checkbox which is not behaves the same

Yeah I totally aware of you laziness and and not-willingness of changing anything in your perfect codebase since I called you `moron` 1.5 year ago. Nothing has changed from that time except you changed your twit https://twitter.com/jimmy_jia/status/697333082572070912 to say `fucking idiot`

But the problem is: not everybody wants to spend their time to dig into your code to fix anything knowing you will just ignore PR

By the way all this is true for react-big-calendar as well, you have 2 PR for `resource view` and ten requests for `yearly view`  but you are to lazy (aka busy with other important things) to merge these PR's.

**Comment by jquense** [comment]
The reason you don't find much success in any place is that you act like an entitled jackass. No one owns you anything, this is OSS and its maintained by folks who bend over backwards in their spare time, at the expense of other hobbies and work to work for free. You on the other hand repeated resort to personal attacks when you don't mildly and promptly get your you, which is why no one wants to help you.
