### ISSUE TITLE
Modal to appear when div on Fullscreen

### ISSUE THREAD

**Issue by GoChartingAdmin** [react-bootstrap/react-bootstrap#2868]
Hi,

I have a div which is currently on full screen mode.  The modal can appear on top of the div on full screen only if the modal is appended as a child to the div.  By default, modals get appended to the document body.  Below is a solution implemented in angular

https://github.com/angular-ui/bootstrap/issues/3686

Was wondering how do I replicate the same in react-bootstrap.

The use case also applies to popovers

Appreciate your help

SD

**Comment by GoChartingAdmin** [comment]
Same is the case when Popovers as well

**Comment by GoChartingAdmin** [comment]
Got it hidden in the private props.  Many thanks for this wonderful package

**Comment by taheerahamed** [comment]
@GoChartingAdmin  how you fixe this issue ?

**Comment by MattRiddell** [comment]
Sorry that this may be a couple of years too late but this came up when I searched for a solution.

Basically you can set `container={myRef}` on the `<Modal>` to a container you'd like to hold the modal dialog.  That way it will exist inside your react app instead of being added to the document (which no doubt is outside your react app).
