### ISSUE TITLE
update license for src/utils/TransitionEvents.js?

### ISSUE THREAD

**Issue by acroyear** [react-bootstrap/react-bootstrap#2884]
Currently you have the BSD(+Patents) License embedded in that file. React as of 15.6.2 is now MIT. Can you update this file to reflect and reference the appropriate License?

**Comment by taion** [comment]
We should probably stop using it entirely...

**Comment by jquense** [comment]
yes I only copied it for strict v1 compat when we moved the repo here. we should stop using it  or replace it with dom-helpers

**Comment by orenssm** [comment]
I wanted to upvote this request. When Wordpress posted the blog article about blacklisting React due to BSD+Patents, this causes some stirs. We are in the process of updating to latest 15.X of React (or possibly 16) with the goal of not having any BSD+Patent references. One reference in the JS bundle is coming from TransitionEvents. It is not even clear if this license applies anymore since where it was copied from is now MIT, but trying to convince legal is an uphill battle..

**Comment by taion** [comment]
Feel free to PR this.

**Comment by kevinzwhuang** [comment]
I'll take a look at this later today. (Saw this note on the top of `CarouselItem`, the only instance I found where `TransitionEvents` is used):
https://github.com/react-bootstrap/react-bootstrap/blob/d8cf4f46d59cf417173dd9e158a295d7133b2f08/src/CarouselItem.js#L7-L8

I'll test if simply using timeout is sufficient to replace it and PR tonight.

**Comment by acroyear** [comment]
I saw there was some discussion over at facebook/react requesting them opening up ReactTransitionEvents so react-bootstrap wouldn't need this internal copy...but they didn't accept it.

**Comment by jquense** [comment]
folks if anyone wants to jump in on this. we can swap out ReactTransitionEvent stuff for the stuff in `dom-helpers`

**Comment by kevinzwhuang** [comment]
@jquense @taion Just opened #2902 to swap out TransitionEvents w/ `dom-helpers`'s `transition` helper
