### ISSUE TITLE
How do you manage this repo along with react-bootstrap-npm?

### ISSUE THREAD

**Issue by atulrpandey** [react-bootstrap/react-bootstrap#292]
Do you manually copy over the src folder from here to react-bootstrap-npm project?

Thanks in advance. :)

**Comment by mtscout6** [comment]
Have you considered using a pre-publish script defined in the package.json and forget the second repo?

See: https://docs.npmjs.com/misc/scripts

**Comment by mtscout6** [comment]
I've been looking into this a bit this morning and there's a few considerations to think about here.

These types of issues keep cropping up (#325 #218), and they will likely continue to crop up.

However, copying everything in `cjs/` to the root of the repo is a non-starter since cleaning that up would be a nightmare.

What I'd like to do is rename `cjs/` to `lib/` which is more in line with other modules out there, including React. Then include a pre-publish script command.

This would be a breaking change though since you would need to change `require('react-bootstrap/...')` to `require('react-bootstrap/lib/...'`. Although `require('react-bootstrap').NavItem` would still work.

The benefit is that issues of the raw repo getting published to npm would go away, and you could remove the second repo.

**Comment by mtscout6** [comment]
Fixed with #326
