### ISSUE TITLE
Cannot type 'space' symbol into FormControl shown in the Modal, when it is rendered in the `Nav`

### ISSUE THREAD

**Issue by alexander-ignatow** [react-bootstrap/react-bootstrap#2934]
I can type space in using the same code outside of the Modal
ctrl-c/ctrl-v works - the space is pasted into the FromControl
 
Using `keyboard={false}` for the Modal did not help

Layout looks like this:
```
<Nav>
   <NavDropdown>
    <MenuItem>
       <CustomOpenButton ... />
        <Modal>[inputs go here]</Modal>
    </MenuItem>
  </NavDropdown>
</Nav>
```

**Comment by alexander-ignatow** [comment]
The workaround:

Do not wrap Modal in the MenuItem:
```
<Nav>
   <NavDropdown>
    <div className="mimic-menu-item">
       <CustomOpenButton ... />
        <Modal>[inputs go here]</Modal>
    </div>
  </NavDropdown>
</Nav>
```

**Comment by jquense** [comment]
don't put the modal in the navitem. I think this is due to the new event bubbling behavior in react 16 portals. The navitem if catching the key events and intercepting them, not thinking they are coming form in a modal.

We should maybe consider not using createPortal for Modals, it's not really the right tool for the job :/

**Comment by taion** [comment]
Or perhaps explicitly stop propagation? Either way, not much we can do right away.

**Comment by Meetyouafter** [comment]
Hi!
I had the same problem with dropdown, but i can fixed it with change <Dropdown.Item> to <div className="dropdown-item">.
And then pass function with change className with ref for close dropdown
