### ISSUE TITLE
Navbar doesn't work correctly on Bootstrap 4

### ISSUE THREAD

**Issue by shaieis** [react-bootstrap/react-bootstrap#2984]
In the [getting stated page](https://react-bootstrap.github.io/getting-started/introduction)
It is said to include latest styles from CDN:
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">

**This already points to Bootstrap 4** which causes problems with <Navbar>

Even the example: "Navbar Basic Example" doesn't work correctly.

**Comment by robertsonmcclure** [comment]
Don't use the latest styles. I just spent an hour debugging this in my own code. Fixed by changing 

`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">`

to

`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">`

as I learned in https://github.com/react-bootstrap/react-bootstrap/issues/2978

**Comment by florentcuret** [comment]
same issue here

```
<Grid fluid>
	<Row>
		<Col xs={4} md={6}>test</Col>
		<Col xs={8} md={6}>test2</Col>
	</Row>
	<Row>
		<Col xs={4}>test3</Col>
		<Col xs={8}>test4</Col>
	</Row>
</Grid >
```

here the output with latest
![latest](https://user-images.githubusercontent.com/1671431/35862499-2c8d80e8-0b4c-11e8-8c20-715f3e3fdaab.png)

here the output with 3.3.7
![3 3 7](https://user-images.githubusercontent.com/1671431/35862500-2ca1f4ba-0b4c-11e8-976b-8b6af8be23e2.png)

you can see in that the .col-xs classes are not available anymore

![screen shot 2018-02-06 at 14 46 07](https://user-images.githubusercontent.com/1671431/35862624-9835673e-0b4c-11e8-8cb0-9f2d2f347502.png)

![screen shot 2018-02-06 at 14 46 32](https://user-images.githubusercontent.com/1671431/35862625-984c53c2-0b4c-11e8-975f-519a104e0dd9.png)

**Comment by jquense** [comment]
We don't support v4 please read the docs and other issues
