### ISSUE TITLE
v4: Carousel

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3024]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/components/carousel/)

- [ ] Update from v3
- [ ] Support page visibility api
- [ ] Sub components

**Comment by zshnr** [comment]
Hi @jquense I would be happy to help with this :)

**Comment by jquense** [comment]
All yours!

**Comment by zshnr** [comment]
@jquense: Hey Jason, sorry for the slow progress on this issue but I am slowly making my way through it :) I had a couple of questions:

1. At some point I may need some guidance, would someone have capacity to help me in that case?
2. How do you feel about using class properties rather than setting state and binding functions in the constructor?

Thanks!

**Comment by jquense** [comment]
> At some point I may need some guidance, would someone have capacity to help me in that case?

Yeah definitely, I recommend opening up a WIP (work in progress) pull request, as a start then it's easier to discuss specific bits of the code as well as provide a place to talk about it.

> How do you feel about using class properties

Yeah go for it, we are generally using them on new dev, sometimes you see them as the normal `.bind` because we haven't updated the code in a while

**Comment by zshnr** [comment]
Unfortunately, I won't be able to work on this issue due to time constraints. Can it please be marked as available? My apologies :(

Thanks!
