### ISSUE TITLE
v4: Navs

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3038]
**Read first!** [Contributing](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md) | [Structuring a PR](https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/V4-Contributing.md ) | [Bootstrap docs](https://getbootstrap.com/docs/4.0/components/inavs/)

**Comment by patrickmcelwee** [comment]
The problem seems to be when `&addOnPanel` is the final url param and the page is loaded. An extra slash is being appended to the URL. 

I believe it is most likely caused when running `python -m SimpleHTTPServer`. I get this error when running python 2.7.5. I do not get it with python 2.7.13. I believe it is most likely caused by this issue: https://bugs.python.org/issue23112, which was resolved at some point in the 2.7 series.
