### ISSUE TITLE
Documentation landing page, getting started guide, and other non-API pages

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-bootstrap#3043]
We really should update, and expand the non-api pages to better reflect the current React ecosystem. A lot of the info here hasn't been updated since React was a much smaller ecosystem

**Comment by jquense** [comment]
that would be lovely, all yours. Don't hesitate to ask any questions here 👍

**Comment by ejachang** [comment]
Would I be able to get a little bit more detail on what exactly you mean by expanding and updating the pages to reflect the current React ecosystem? I'm not too sure if this refers to the information in the documentation or state management, tools, and testing? Since the Doc landing page was mentioned I had understood it to be the latter. 

I was also not clear if this in reference to the goal of splitting the docs in a similar manner to how Bootstrap does as mentioned in the wiki, or is that more related to ticket #3041?

Thank you!

**Comment by ejachang** [comment]
Would I be able to get a little bit more detail on what exactly you mean by expanding and updating the pages to reflect the current React ecosystem? I'm not too sure if this refers to the information in the documentation or state management, tools, and testing? I understand it to be the former, but with the Documentation landing page included in the pages I wasn't too sure.

Thank you!

**Comment by jquense** [comment]
Yeah I was thinking the information in the actual docs pages. There used to also be a page with general instructions on jsx and other basic react concepts I removed recently. It would be really nice if we had more beginner or getting started info beyond "how to install". Some thoughts like how the library relates to the original bootstrap, what's the benefit, etc. As well a nicer landing page beyond the wall of bullet points and warnings :p

Does any of that make sense, I don't have a super well formed idea, but our general docs are lacking compared to other similar libraries

**Comment by ejachang** [comment]
Hi - sorry for the late response. Yes, it does make sense! I'll let you know if I have more questions in regards to the overall big picture of updating the non-API pages.

If possible, would I be able to know where to find what the general instructions on jsx and other basic react concepts looked like? Was it in application to react-bootstrap, or just a general overview on how jsx works and other basic react concepts to give the reader a general sense of how react worked? I'm also a bit curious what the pre-existing documentation looked like. Thanks!

**Comment by jquense** [comment]
> Was it in application to react-bootstrap

Not really, it was more of a general guide to react and jsx, written at a time when that info was less widely available. Now a days the reactjs docs site does a fine job at all that. It'd be better if react-bootstrap could focus more on the bootstrap specific things. I've already covered this a _little_ bit by reorganizing the [getting started page](https://deploy-preview-3124--react-bootstrap.netlify.com/getting-started/introduction), but there is still tons of room for more.

> I'm also a bit curious what the pre-existing documentation looked like

We don't have it up but you can navigate the repo to an older tag (say pre v0.28.0) and run it or look at the code for an idea.

**Comment by ejachang** [comment]
Hi jquense, apologies I've been rather slow about this! 
I saw that the landing page was updated last week and that this has been moved to "In progress". It's been taking me longer than I thought to work on this, and in part because I've been focusing more on details e.g. writing about the way jQuery affects react-bootstrap. But let me know if that is something to add and if this issue is still fine for me to work on?
