### ISSUE TITLE
Should Bootstrap 4 be a separate project?

### ISSUE THREAD

**Issue by bootrino** [react-bootstrap/react-bootstrap#3081]
There are so many differences between Bootstrap 3 and 4, perhaps it should be a separate project.

I am anticipating that putting them both into this project is going to make things painful and complex to use.  Is this possibly right or an unfounded concern?

**Comment by jquense** [comment]
I don't think it's probably manageable to make the seperate projects. I mean we aren't planning on supporting both at the same time, but instead take teh same appraoch as bootstrap, bump a major version and that will be react-bootstrap, bootstrap v4 components  built for react. Past versions targeting v3 will still work and be as stable as they are now, but we won't be actively adding new stuff to those versions (though we;ll probably continue with bug fixes since we'll have projects using v3 for a while)

**Comment by bootrino** [comment]
Hmmm.

It's worth thinking about.

Bootstrap 4 is more for newer browsers and there's going to be a long term need for BS3.

It might get confusing to be sorting through V3 and V4 of this project.

Sounds like it might have been a good time for this project to fork itself and let the current project remain as the long term stable BS3 React implementation.

Even the fact that I am asking this question is an indication of the coming challenges.

**Comment by jquense** [comment]
I'm not sure why we would do that if upstream bootstrap is not. It's going to be more maintainable longer term to match how they work vs trying to something different. Regardless of how much people will continue to use v3, upstream bootstrap is not updating that version at all anymore (and hasn't for months) I don't think there is a ton of value in trying to be more nimble in that regard than the library we are porting.
