### ISSUE TITLE
DropdownButton (0.32.1) causes ref error with React 16 (16.3.2)

### ISSUE THREAD

**Issue by shamas** [react-bootstrap/react-bootstrap#3140]
Error is:
>Uncaught Error: Element ref was specified as a string (inner) but no owner was set.

Code that triggers this is:
```
export class Dropdown extends React.Component<Object, {}> {
  render() {
    return <DropdownButton title={this.props.initialValue}
        style={{color: '#333', fontSize: '18px',
                fontWeight: '300', minWidth: '180px'}}
        id="genericDropdown" onSelect={this.props.onSelect}>
      {this.props.options.map((v,i)=><MenuItem key={i} eventKey={v}>{v}</MenuItem>)}
    </DropdownButton>
  }
}
```

**Comment by jquense** [comment]
Sounds like you may have multiple versions of react installed accidently

**Comment by shamas** [comment]
I use ref often throughout the rather large code base, this is the only code block that causes this error.

**Comment by jquense** [comment]
Yes, definitely. In the meantime tho the API is supported by react so shouldn't cause errors. It's still likely you multiple instances of React in your bundle. We will be changing the the string refa going forward but it will only hide that underlying issue of having multiple instances!

**Comment by ripplegupta03** [comment]
I am getting the same error in my project using react-bootstrap, DropdownButton is triggering the error. Verified that its not a multiple react copy issue in my case. When can we expect this to get fixed.
Using:
"react": "^16.2.0",
"react-bootstrap": "^0.32.0"

**Comment by shamas** [comment]
Something to try is that I might have been including 2 copies of my compiled js, one in the index.html and another injected into the index.html by webpack dev. I migrated away from this library before confirming this was an issue, but it is something to try.

**Comment by jquense** [comment]
@shamas this is 100% not an issue with react-bootstrap, you shouldn't have had to migrate away if you didn't want to. This error is an indication of a build configuration error in ones app. The package that is the "cause" of it is unrelated to the error it just happens to be the package that triggered npm to do something odd , or uncovered something in your build. I'm only mentioning it because there is more than likely a bigger problem or misconfiguration in your app, that you were seeing.

**Comment by jquense** [comment]
@ripplegupta03  I would add again, i am 100% sure this is not a bug in react-bootstrap because this error is in React, caused by a normal ref, and impossible for us to fix, as much as i'd love to help.

this is error is caused by having multiple instances of React, even if you think you don't you do, i'm sorry that this is a such an annoying issue with react, but there is really nothing we can do about it on our end.
