### ISSUE TITLE
Panel::onToggle() - make it optional or ...?

### ISSUE THREAD

**Issue by antzhdanov** [react-bootstrap/react-bootstrap#3141]
I am not quite sure which of the two following is correct. Either:

- docs on new Panel API doesn't seem to be 100% correct (https://react-bootstrap.github.io/components/panel/#panels-collapsible). 
First example in the section doesn't pass `onToggle` prop, although it is listed as required when `expanded` is set (I'm getting a `Failed prop type` warning).
- or `onToggle` should be optional. Example I refer to has a button that toggles `expanded` flag in state, and in my use case I don't need any callbacks for `onToggle`. Of course, I could pass a NOOP function to it, but it's so wrong.

**Comment by elliottkopp** [comment]
I'm also facing this issue.  We have a collapsible panel whose `expanded` property is controlled from a button elsewhere on the page.  I'm not sure why I need to supply `onToggle`.  `onToggle` doesn't control `expanded` in my case.  Something else does.

The example antzhdanov linked will indeed result in the error "Warning: Failed prop type: You have provided a `expanded` prop to `Panel` without an `onToggle` handler prop. This will render a read-only field. If the field should be mutable use `defaultExpanded`. Otherwise, set `onToggle`."

Agree that `onToggle` should be optional.

**Comment by bpas247** [comment]
I assuming this issue isn't relevant in the beta releases, but is this still relevant for the latest release supporting bootstrap v3 (`v0.32.4`)?

**Comment by kosmiq** [comment]
Closing since no new feedback for a long time.

**Comment by jakebellacera** [comment]
Any way we can bump this? Passing a noop function feels wrong and is still the case in v0.33.1, unless I'm mistaken?
