### ISSUE TITLE
Keyboard prop won't work on modal

### ISSUE THREAD

**Issue by eicel** [react-bootstrap/react-bootstrap#3172]
`<Modal show={this.state.show} backdrop="static" keyboard={false}>
    ...
</Modal>`

Modal seems to won't listen "keyboard" property, it's still closing on pressing escape key.

**Comment by taion** [comment]
can't reproduce this; it works fine on our docs page https://react-bootstrap.github.io/components/modal/

if you have a repro, please share it

**Comment by masciugo** [comment]
https://github.com/react-bootstrap/react-bootstrap/issues/1783

**Comment by yabdabs** [comment]
Thanks @eicel 

Taking out onHide works and keyboard="false" wasn't needed

**Comment by sernaferna** [comment]
I think this issue needs to be reopened because the `keyboard` and `onHide` parameters should not be tied together like this. I'm trying to create a modal in which a user does a lot of typing, perhaps including use of the _Escape_ key, so I want to set `keyboard` to `false` but I still want the modal header to have a `closeButton`. Given the current implementation I can choose one or the other: I can disable keyboard handling _or_ I can have a close button, but not both. 

(In fact, given what the poster above has mentioned, the `keyboard` property doesn't seem to do anything; only `onHide` is useful.)

There's a code sandbox reproducing the issue [here](https://codesandbox.io/s/modest-panna-dcep33?file=/src/App.js), but it's easy enough to paste the code as well:

```jsx
import React, { useState } from "react";
import { Button, Modal } from "react-bootstrap";
import "./styles.css";

export default function App() {
  const [m1Showing, setM1Showing] = useState(false);
  const [m2Showing, setM2Showing] = useState(false);

  return (
    <div className="App">
      <h1>Reproducing Modal Issues</h1>

      <div className="mb-4">
        <Button onClick={() => setM1Showing(true)}>
          Properly ignores Esc but close button doesn't work
        </Button>
        <Modal keyboard={false} show={m1Showing}>
          <Modal.Header closeButton>Keyboard Disabled</Modal.Header>
          <Modal.Body>
            <p>
              I won't close if you hit <em>Esc</em>, but neither will I close if
              you press the header's close button
            </p>
          </Modal.Body>
          <Modal.Footer>
            <Button onClick={() => setM1Showing(false)}>Close</Button>
          </Modal.Footer>
        </Modal>
      </div>

      <div>
        <Button onClick={() => setM2Showing(true)}>Doesn't ignore Esc</Button>
        <Modal
          keyboard={false}
          show={m2Showing}
          onHide={() => setM2Showing(false)}
        >
          <Modal.Header closeButton>Keyboard not disabled</Modal.Header>
          <Modal.Body>
            <p>
              Close button in the header now works, but pressing <em>Esc</em>{" "}
              will close the modal even though it's not supposed to.
            </p>
          </Modal.Body>
          <Modal.Footer>
            <Button onClick={() => setM2Showing(false)}>Close</Button>
          </Modal.Footer>
        </Modal>
      </div>
    </div>
  );
}
```

As shown I can always create my _own_ button and close the modal that way, but why should I not be able to to have `closeButton` in the header too?

**Comment by kyletsang** [comment]
@sernaferna can you please open a new issue and add details?  This is a 4+ year old thread and the advice above most likely corresponds to the 0.x version where behavior is different.
