### ISSUE TITLE
Warning: React does not recognize the `transitionAppear` prop on a DOM element

### ISSUE THREAD

**Issue by petrdanecek** [react-bootstrap/react-bootstrap#3175]
After 0.32.x upgrade from 0.31.5 I'm observing this:

> Warning: React does not recognize the `transitionAppear` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `transitionappear` instead. If you accidentally passed it from a parent component, remove it from the DOM element. 

It appears together with Modal opening. I'm using react 16.4.

Originally I thought that it related to some other component as npm install says:

```
npm WARN react-16-bootstrap-date-picker@5.1.2 requires a peer of react-bootstrap@^0.31.0 but none was installed.
npm WARN react-16-bootstrap-date-picker@5.1.2 requires a peer of react-dom@^15.5.4 but none was 
installed.
```

The issue is observed even for empty modal without any other component in modal.

![image](https://user-images.githubusercontent.com/29194829/41336129-8f4dfb10-6eeb-11e8-9758-2334d3fd8ab9.png)

The workaround is to rollback to 0.31.5. The issue may be related to this change:
![image](https://user-images.githubusercontent.com/29194829/41336415-785ead54-6eec-11e8-9424-81efbb699f87.png)

**Comment by dangrabcad** [comment]
Can I ask why this was closed? I'm sure it was for a good reason e.g. the error comes from using the library wrong; but it would be really helpful as a user of your library to know the reason. I have exactly the same error in 0.33.1, the latest version supporting Bootstrap 3. It looks like it's caused by some version incompatibility - it started when updating React to 16.8 - but there's no information here or in the documentation to know what versions of things are expected to work or how I might find that out for myself.
