### ISSUE TITLE
Documentation for `eventKey`

### ISSUE THREAD

**Issue by skfd** [react-bootstrap/react-bootstrap#320]
What does this property do?

**Comment by Xuhao** [comment]
@skfd Me too, this confused me but no documentation to check.

**Comment by mtscout6** [comment]
@skfd and @Xuhao We'd love pull requests adding documentation, which is part of the [1.0.0 Roadmap](https://github.com/react-bootstrap/react-bootstrap/wiki#100-roadmap).

**Comment by mtscout6** [comment]
Also related to #419 since that work will need documentation before closing.

**Comment by oliviercardoen** [comment]
I also agree. As a newcomer, it's hard to understand this stuff. I believe it will become clearer in 1.0.0.

**Comment by mik01aj** [comment]
+1. And I still don't understand it, even after reading @trentgrover-wf 's comment.

Do I need this if I don't use the handleSelect callback?

**Comment by davesag** [comment]
I'm just starting to play with this too and I'll admit to being confused by the `eventKey={x}` properties. I can't see `eventKey` prop documented anywhere. How do I, for example, handle a click?

My guess is `eventKey={0}` is just a placeholder and not an actual property, and, as such I'd replace `eventKey` with, say, `onClick={this._myClickHandler}` or something.  I'll experiment but it would be good if someone could provide a more concrete example of this.

**Comment by taion** [comment]
It's just for `onSelect`... except for on `Nav`-related items where `activeKey` is involved.

**Comment by davesag** [comment]
Sorry @taion but that makes no sense to me.  Can you point me at a fully fleshed out example of a `Navbar` component in use or some documentation for the `eventKey` property?

**Comment by taion** [comment]
http://react-bootstrap.github.io/components.html#navs

**Comment by davesag** [comment]
@talon yes but what is the meaning of the values assigned to `eventKey`? Like why would I use `{1}`? what does the `1` mean? The docs say the value can be `any` — I'm just not getting what `eventKey` actually does, how it's used, or what the values ought to be. Perhaps you could explain that for me.

**Comment by taion** [comment]
It gets matched to the `activeKey` in the `<Nav>`...

**Comment by davesag** [comment]
So how do I use that to tell my content component to change?  Currently, in my hand-rolled `NavItem` component register the component with a `navStore` (I'm using the flux pattern) and then my `_handleClick` method fires off a `navStore.select(this.props.itemCode)` which, in turn triggers an `'update'` event that both my `NavItem` and `Content` components listen to.

    let NavItem = React.createClass({
      displayName: "Navigation-Item",
      propTypes: {
        code: React.PropTypes.string.isRequired
      },

      getInitialState: function() {
        return {
          selected: false,
          active: true
        };
      },

      componentDidMount: function() {
        navStore.on('update', this._handleChange);
      },

      componentWillUnmount: function() {
        navStore.removeListener('update', this._handleChange);
      },

      _handleClick: function() {
        navActions.select(this.props.code);
      },

      _handleChange: function() {
        let selected = navStore.selectedItem === this.props.code;
        this.setState({
          selected: selected
        })
      },

      _acceptsClick: function() {
        return (this.state.active && !this.state.selected);
      },

      render: function() {
        let classes = [];
        if (this.state.active) classes.push('active');
        if (this.state.selected) classes.push('active');
        let classNames = classes.length ? classes.join(' ') : null;
        if (this._acceptsClick()) {
          return (
            <li className={classNames}>
              <a
                  href="#"
                  onClick={this._handleClick}
                  title={constants.NAV_ITEMS[this.props.code].description}
              >{constants.NAV_ITEMS[this.props.code].title}</a>
            </li>
          );
        }
        return (
          <li className={classNames}>{constants.NAV_ITEMS[this.props.code].title}</li>
        );
      }
    })

So I'm trying to work out how to do the equivalent with React-Bootstrap. How would I tell my Content component that the `Navigation`'s `activeKey` has changed, so it then knows to change itself?

**Comment by taion** [comment]
If you're controlling `activeKey`, then you control that. Otherwise, use `onSelect`. Anyway, this is beyond the scope of the issue, and our issue tracker is not great as a Q&A forum - try Stack Overflow or Reactiflux.

**Comment by davesag** [comment]
@taion okay thanks.  I think I'll just implement the bootstrap styles etc manually within my hand-rolled components. Seems quicker than trying to work out `React-Bootstrap` — I'll revisit this project when your documentation is more complete.

**Comment by taion** [comment]
React-Bootstrap currently has over 100 examples and close to 5000 words of prose documentation (not including the contents of the props tables). It sounds like you're asking for a fairly basic pattern about invoking a callback on item selection, and there's multiple examples on the components page demonstrating this use case. If you need additional guidance, the other forums I've pointed you to are actually both really good fits for Q&A and getting additional help - I think you'll get good results if you ask there.

**Comment by pzrq** [comment]
First time React-Bootstrap user, similar reaction to @skfd.
https://react-bootstrap.github.io/components.html#navbars-mobile-friendly

<img width="852" alt="in all fairness the my first navbar reaction was what s this react prop eventkey thing" src="https://cloud.githubusercontent.com/assets/1217010/20235363/e27ca540-a8e3-11e6-825d-22e94c40bf21.png">

I'll have a go since this is my top Google for "react bootstrap eventkey" which arises very naturally if you're building a new React/Bootstrap application and want a `<Navbar>`, then think mobile responsive too if it's copy/paste then why not 👍 

* `eventKey` is just a plain old [React prop](https://facebook.github.io/react/docs/components-and-props.html). 
* `eventKey` is specifically a [`<NavItem>` component prop](https://react-bootstrap.github.io/components.html#navs-props-navitem).
* `eventKey` is passed to the [`<Nav>` onSelect callback](https://react-bootstrap.github.io/components.html#navs-props-nav).
* `eventKey` is used to set the `<Nav>` component's [`activeKey` prop](https://react-bootstrap.github.io/components.html#navs-props-nav).

Taken together, this means that when a user clicks on a `<NavItem>`, triggering the `onSelect` callback, that the `eventKey` is sent up to the `<Nav>` and used to set the `<Nav> activeKey` prop, marking the `<NavItem>` with an [`active` CSS class just like other bootstrap examples](http://www.w3schools.com/bootstrap/bootstrap_tabs_pills.asp).

**Comment by ignorabilis** [comment]
After all these writings it was still unclear to me that you actually need to set activeKey on Nav to one of the corresponding eventKeys - it does not happen automatically and you are free to have whatever logic is needed.

For example `activeKey={this.state.activeKey}` sets the `activeKey` from the state. A naive implementation would be then to use `onSelect` and set the `this.state.activeKey` to whatever comes as the first argument in `onSelect`. A proper implementation would be to derive the `activeKey` from the current page and not use `onSelect` at all since a user can get redirected from another link/button.

**Comment by syang** [comment]
@ignorabilis "A proper implementation would be to derive the activeKey from the current page and not use onSelect at all since a user can get redirected from another link/button." what is the proper implementation (if using onSelect event to update the current activeKey is not the proper one)? Thanks.

**Comment by ignorabilis** [comment]
@syang  Your app needs to know at which page it is - let's say it's in a global state (using a Flux store for example).  Then the active key should come from this global state instead of being changed `onSelect`. Otherwise if the user gets to that page in some other way `onSelect` will not be triggered and the active key will not change.

**Comment by chaseholdren** [comment]
Still confused by this in 2018.

**Comment by pacificsoftdevld** [comment]
<MenuItem onSelect={this.handleSelect} eventKey="1" />

handleSelect = e => { console.log(e); // e is eventKey above }

**Comment by oshiniG** [comment]
Warning: React does not recognize the `eventKey` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `eventkey` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

If we change the eventKey in to eventkey it's not set the active item. What is the best way without warning?
''
<Dropdown.Item eventKey="1.1"}>{label}</Dropdown.Item>)
''

**Comment by melvinroest** [comment]
This is what I read in the current docs (March 2020).

> The callback is called with an eventKey, which is a prop from the selected <Nav> descendant, and an event.
> 
> ```
> function (
>  eventKey: mixed,
>  event?: SyntheticEvent
> )
> ```
> 
> For basic closing behavior after all <Nav> descendant onSelect events in mobile viewports, try using collapseOnSelect.

Source: https://react-bootstrap.github.io/components/navbar/
