### ISSUE TITLE
In SubNav component, activeKey not work

### ISSUE THREAD

**Issue by warmhug** [react-bootstrap/react-bootstrap#322]
<Navbar fluid brand={brand} toggleNavKey={3}  >
      <Nav activeKey={2}>
        <NavItem eventKey={1} href="#" onSelect={sel}>Link</NavItem>
        <NavItem eventKey={2} href="#" title="xxx">Link</NavItem>
        <SubNav activeKey={11} text="subNav">
          <NavItem eventKey={1} href="#">Link</NavItem>
          <NavItem eventKey={11} href="#">Link</NavItem>
        </SubNav>
      </Nav>
    </Navbar>

 the `activeKey` in `SubNav` does not work.

**Comment by taion** [comment]
Three things here -

1. `SubNav` isn't documented anywhere - I'm not sure it's actually part of our public API, and it certainly doesn't make any sense nested in a `Navbar` like that
2. `Nav` injects its `activeKey` to all of its children - the explicit `activeKey` prop on your `SubNav` is a no-op
3. If you change `activeKey` on the `Nav` to `11`, you can see that the `active` class is added to the appropriate `NavItem`, but because this nested navigation usage is not appropriate in this context, stock Bootstrap CSS applies no special styling there
