### ISSUE TITLE
Add displayName to components

### ISSUE THREAD

**Issue by dspacejs** [react-bootstrap/react-bootstrap#3279]
I've just tried switching from reactstrap to react-bootstrap. One thing reactstrap does is assign a `displayName` to their components.

This makes it easy to test, such as by using Enzyme's [`find()`](https://airbnb.io/enzyme/docs/api/ReactWrapper/find.html) function to search for the existence of a component.

But in react-bootstrap this isn't possible because components don't have a `displayName`. So doing something such as `find('Navbar')` will return 0 results, even if it's actually rendered.

This can also be seen when using `debug()`'s output, as the name of a component is `[object Object]`:

```
<[object Object] expand="lg" fixed="top">
  ...
</[object Object]>
```

**Comment by jquense** [comment]
The component s do have display names, tho they aren't specified as static properties since react and enzyme are smart enough to use the function names. I'm not sure why your getting bad results from enzyme maybe you need to update? We use enzyme for our own test here and aren't seeing the same thing in termed of unnamed components

**Comment by jquense** [comment]
I mean you should check your version of enzyme.

**Comment by dspacejs** [comment]
Also note some components such as `Navbar` don't have a proper `displayName` for testing.

This is what's expected from `debug()`:
```
ForwardRef(Bootstrap(Navbar))
```
But the output is:
```
ForwardRef(Bootstrap(undefined))
```

**Comment by nortonwong** [comment]
You can avoid relying on `displayName` by using [constructor selectors](https://airbnb.io/enzyme/docs/api/selector.html#2-a-react-component-constructor):
```js
wrapper.find(Navbar);
```
This is less fragile, and won't cause problems if unrelated components share similar names.

**Comment by bpas247** [comment]
FWIW a lot of our components now explicitly have a `displayName` property (ones that have been migrated to properly forward their refs, that is). [Navbar](https://github.com/react-bootstrap/react-bootstrap/blob/788947ef097a5b32b8a08823e038c543ca859ea3/src/Navbar.js#L201) happens to be one of these components.

@dspacejs is this still an issue? otherwise I think I'm gonna go ahead and close it 😃

**Comment by dspacejs** [comment]
@bpas247 feel free to close it :+1:
