### ISSUE TITLE
Migration guide issues

### ISSUE THREAD

**Issue by cymen** [react-bootstrap/react-bootstrap#3336]
I'm reading https://react-bootstrap.netlify.com/migrating/ and trying a migration of an existing project and I noticed:

* the guide doesn't mention the (presumed) removal of `Well`
* says `MenuItem` became `DropdownItem` but it is really `Dropdown.Item` (also has extra word from in `from to`)
* `ControlLabel` -> `Form.Label`
* `FormGroup` -> `Form.Group`
* `FormControl` -> `Form.Control`
* `Radio` -> `Form.Radio`
* `Checkbox` -> `Form.Check`

It would be great to have suggestions or workarounds for:
> removed Navbar.Header
> removed Navbar.Form

**Comment by jquense** [comment]
Happy to take PR improving the wording! for some clarifications tho, we don't cover every change that is in bootstrap4, (please check their notes for that) so workarounds for Navbar.Form are probably out of scope for the migration doc, and it should be (hopefully) clear looking at the navbar docs how to build a new navbar with the equivalent functionality. 

For components like `FormControl` vs `Form.Control` both are correct, the new component is FormControl, and you can import it as such (`import FormControl from '..')` We do prefer to show you the more convenient static property export since it saves time typing but in general the mapping from the old to new component in the doc is correct.

**Comment by bpas247** [comment]
Working on this right now. I will open a PR soon.

**Comment by QuantumInformation** [comment]
Thanks for Dropdown.Item

**Comment by QuantumInformation** [comment]
What do we replace this with 

`<Nav pullRight={true}>`

**Comment by jquense** [comment]
@QuantumInformation you are going to get very little feedback commenting quickly on old, closed issues. I'd suggest trying the support avenues for questions, like discord

**Comment by QuantumInformation** [comment]
Then why don't you lock the issue?

Its a relevant migration question, that gets lost in Discord.

**Comment by jquense** [comment]
i'm tell you for your sake so you can get some help quicker, ppl don't tend to respond to or look at comments on closed issues.
