### ISSUE TITLE
V4: Navigation dropdown options hiding 

### ISSUE THREAD

**Issue by imi56** [react-bootstrap/react-bootstrap#3357]
Navigation dropdown options are hiding if it is leftmost.
[Please refer this](https://i.stack.imgur.com/A1auB.png)

`<Navbar collapseOnSelect expand="lg" bg="dark" variant="dark">
  <Navbar.Brand href="#home">React-Bootstrap</Navbar.Brand>
  <Navbar.Toggle aria-controls="responsive-navbar-nav" />
  <Navbar.Collapse id="responsive-navbar-nav">
    <Nav className="mr-auto">
      <Nav.Link href="#features">Features</Nav.Link>
    </Nav>
    <Nav>
      <NavDropdown title="Dropdown" id="collasible-nav-dropdown">
        <NavDropdown.Item href="#action/3.1">
          Awesome Action One
        </NavDropdown.Item>
      </NavDropdown>
    </Nav>
  </Navbar.Collapse>
</Navbar>`

**Comment by riteshtyagi** [comment]
Facing the same issue, the dropdown items hide randomly behind similar cards

**Comment by bpas247** [comment]
Is this issue still relevant in the latest release?

**Comment by srianbury** [comment]
Still looks like an issue on 1.4.3

## To Reproduce

Steps to reproduce the behavior:

1. Ensure the navbar is expanded
2. Click on the dropdown in the navbar
3. The dropdown opens with the right half out of view (and the window width increases).

## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/epic-glade-qnqsh?file=/src/App.js).

## Expected behavior

The options should right align with the button automatically.  Similar to `menuAlign="right"` on the `DropdownButton` component.

## Screenshots

![error](https://i.stack.imgur.com/A1auB.png)

## Environment (please complete the following information)

- Operating System: windows
- Browser, Version: Chrome 87
- React-Bootstrap Version: 1.4.3

## Additional context

None

**Comment by kyletsang** [comment]
NavDropdowns support align prop now in v2
