### ISSUE TITLE
Warning: Rendering <Context.Consumer.Consumer> is not supported...

### ISSUE THREAD

**Issue by Richard87** [react-bootstrap/react-bootstrap#3362]
![image](https://user-images.githubusercontent.com/5749715/48190437-01f5cc80-e343-11e8-9546-81c85b99c97b.png)

I think the fix for #3347 introduced this bug:
(For the record, I also upgraded to React 16.7-alpha.0, but I _don't_ think that's the cause :) )

Full error message:
```
index.js:1452 Warning: Rendering <Context.Consumer.Consumer> is not supported and will be removed in a future major release. Did you mean to render <Context.Consumer> instead?
    in nav (created by Navbar)
    in Navbar (created by Uncontrolled(Navbar))
    in Uncontrolled(Navbar) (at src/index.js:127)
    in div (created by Row)
    in Row (created by Context.Consumer)
    in div (created by Container)
    in Container (created by Context.Consumer)
    in NavContainer (at Page.js:48)
    in Query (at ComponentQuery.js:64)
    in ComponentQuery (created by Mutation)
    in Mutation (created by Apollo(ComponentQuery))
    in Apollo(ComponentQuery) (at Page.js:48)
    in Query (at App.js:22)
    in App (at src/index.js:13)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:12)
    in ApolloProvider (at src/index.js:11)
```

Pinging @nathanstitt , Here is your stack trace :)

**Comment by Daarien** [comment]
It started after I've updated to 1.0.0-beta.2

**Comment by nathanstitt** [comment]
I've debugged this and it's coming from: https://github.com/4Catalyzer/react-context-toolbox/blob/master/src/mapContextToProps.js#L12

That line attempts to get the `Consumer` property so that ContextToolbox can support being passed either a `Context`, or a `Context.Consumer`.  However it's failing because Context.Consumer also has a `Consumer` property, most likely so that React can detect it's being used inappropriately and issue the warning we're seeing.

React Bootstrap and React Overlays pass a mix of just `Context ` and `Context.Consumer` to toolbox.  If we want to continue to use ContextToolbox as-is we'll need to pass it only Context so the line above will do the right thing.  However, since that the check above isn't working I think that should be fixed and then everything will pass `Context.Consumer` to ContextToolbox.

I opened https://github.com/4Catalyzer/react-context-toolbox/issues/9 there to discuss

**Comment by aeggers-fdi** [comment]
This also seems to be an issue in the Tabs/TabContainer. Not sure if it has the same root cause in react-context-toolbox.
Stacktrace:
```
Warning: Rendering <Context.Consumer.Consumer> is not supported and will be removed in a future major release. Did you mean to render <Context.Consumer> instead?
    in TabContainer (created by Tabs)
    in Tabs (created by Uncontrolled(Tabs))
    in Uncontrolled(Tabs) (at src/index.js:127)
    in SearchTabPanel (at App.js:12)
    in div (at App.js:8)
    in App (at src/index.js:7)
```

**Comment by joonashak** [comment]
FYI, getting this for `Form` as well.

**Comment by Richard87** [comment]
I just updated to beta.3 and it seems to be fixed  :+1:
