### ISSUE TITLE
How do you use the dev branch instead of master?

### ISSUE THREAD

**Issue by mkondel** [react-bootstrap/react-bootstrap#3372]
I want to be able to use Panels and Accordions, but the current master (1.0.0-beta.3) does not have them. There is a branch called 'bs3-dev', and I saw that it has Accordion.js and Panel.js. Installation worked just fine, but now the bootstrap.css is not getting picked up.

![image](https://user-images.githubusercontent.com/3288757/48530064-187cb600-e864-11e8-936a-dc94fbc4dc0e.png)

![image](https://user-images.githubusercontent.com/3288757/48530041-f84cf700-e863-11e8-997b-2566e6e0d3bb.png)

I have tried installing the bs3-dev brach, then doing to node_modules/react-bootstrap and running ```yarn && yarn build```. There was no change, the CSS is still not loaded.
Please let me know if you have a way to import and use the bs3-dev branch.

**Comment by taion** [comment]
`bs3-dev` is the v0.x line (currently v0.32.4). Note that this corresponds to Bootstrap 3 rather than Bootstrap 4. Equivalents of those components still exist in Bootstrap 4, but have been replaced by the "card" component: https://getbootstrap.com/docs/4.1/components/card/#about.

For new projects, you should prefer Bootstrap 4.
