### ISSUE TITLE
Implement Toast

### ISSUE THREAD

**Issue by a-martynovich** [react-bootstrap/react-bootstrap#3464]
Toasts are [added to Bootstrap](https://getbootstrap.com/docs/4.2/components/toasts/) in v4.2. I'm not sure if I can implement this myself, so anyone interested is welcome.

    <Toast 
        show={this.state.show} 
        onShow={this.onShow} 
        onHide={this.onHide} 
        animation={this.props.animation}
        autohide={this.props.autohide}
        delay={this.props.delay 
    />

**Comment by bpas247** [comment]
I'm currently working on #3409 right now. I might be able to open a PR in the coming days though, would also like to see this component as part of the library :+1:

**Comment by mxschmitt** [comment]
Looking forward that this will be implemented. Thanks for your work!

**Comment by timkindberg** [comment]
Might be good to add in placement options? I'm thinking: top, top-left, top-right, right, left, bottom, bottom-left, bottom-right, center?

**Comment by timkindberg** [comment]
I almost see this as a javascript util instead of a component (or both). The challenge is doing the auto stacking for the dev who might be triggering Toasts from multiple places in their code, maybe even from redux actions, error handlers in ajax calls, etc. So it would be easier to manage as a function that is called and then we can control everything about it.

```
import { toast } from 'react-bootstrap'

const MyComponent = () => {
  const showToast = () => toast.show({
    ...options
  })
  return <button onClick={showToast}>Show Toast</button>
}
```

The two other libs I looked at both seem to do it this way but they make you put a `<ToastsContainer />` somewhere in your app. Not sure if that's necessary (it seems unnecessary to me at first glance).

- https://www.npmjs.com/package/react-toasts
- https://fkhadra.github.io/react-toastify/

**Comment by RALifeCoach** [comment]
Is someone currently working on this?

**Comment by taion** [comment]
not as far as i know

**Comment by mxschmitt** [comment]
I'm currently working on it. #3685

**Comment by mxschmitt** [comment]
I've finally merged it and it will be included in the next  release. I guess a new version will released in the next few days. :)

**Comment by gino8080** [comment]
it is possible to show Toast calling it by code ?

I mean something like Toast.show({...options}) ?

**Comment by mxschmitt** [comment]
@gino8080 currently not, but a simple wrapper for showing and automatically timing out them would be kinda useful for some users.
