### ISSUE TITLE
add active prop where suitable

### ISSUE THREAD

**Issue by flying-sheep** [react-bootstrap/react-bootstrap#352]
e.g. bootstrap has special variables for active `MenuItem`s .

we should add an `active={this.state.active}` prop instead of requiring `className={classSet({active: this.state.active})}`

**Comment by mtscout6** [comment]
:+1: We take pull requests.

**Comment by taion** [comment]
Was `MenuItem` the only component that was missing an `active` prop?

**Comment by mtscout6** [comment]
Before closing we should take a survey of all the components that would need this.

**Comment by AlexKVal** [comment]
I'm closing it.
If a user has a problem with the `active` in any component, 
then them will create a specific issue.
(as this one. that is particularly about `MenuItems`)
:cherries:

**Comment by mtscout6** [comment]
I think this is a valid point to ensure that it is correct for Bootstrap parity. Which is why I was saying that a more thorough survey is needed before closing. Unless you are proposing a better way to track progress towards Bootstrap parity.

**Comment by AlexKVal** [comment]
My personal point of view is:
there has to be some compromise
between `Bootstrap parity` and `practical value` of implementing this `parity`.

`Bootstrap`-way and `React plus Boostrap`-way - IMHO is not the same.

`Bootstrap` deals with web-develomplent tasks - its own way.
That way is defined by `jQuery` constraints.

`React-Bootstrap` has the powers of `React`. 
This project can and does deal with the same web-develomplent tasks another way.

`Bootstrap` API is dictated by `Bootstrap`+`jQuery` constraints 
and this is not automatically mean that its API is good and best.
I'm sure there are good parts and bad parts. As everywhere.

Therefore - IMHO - this project should not strive to full parity.

Demand and Supply define what is needed and what is not.
`R-B` already 2+ years old. 
If we take a look through issues and PRs history, we will see,
that those not implemented components and features - they are just not in demand.
Hence it is not necessary to implement them.
Implementing parity for only the sake of parity - it is a bad business :smile: 

Let's market - i.e. our users - define what has to be implemented. And only when it is needed :wink: 

Something like that.
Sorry for the missive
:cherries:

**Comment by mathieumg** [comment]
> Therefore - IMHO - this project should not strive to full parity.

Just to be clear, we mean feature parity, not API-parity.


> If we take a look through issues and PRs history, we will see,
> that those not implemented components and features - they are just not in demand.

That's a hasty conclusion. There are some components among them which I use, but haven't gotten around to create the proper wrapper yet. See https://github.com/react-bootstrap/react-bootstrap/issues/56#issuecomment-116646243

**Comment by mtscout6** [comment]
@AlexKVal I understand your concern with maintaining features that are not used or needed. Though this issue is evident of a feature of Bootstrap that we are missing, and is wanted. The `active` class is regularly used within Bootstrap to convey different styling for an active item. I proposed a broader survey of all the components since I'd see this as a requirement of our 1.0.0 release.

Another point to consider is that this project is a team effort. If you're unsure of a feature and it's usefullness, then state so and ask the rest of the collaborators if they agree. If the majority of the team agrees to such, then I'd feel a lot more comfortable with the decision. I know this can be a slow process since we would need to elicit feedback, but the end product will be more desirable by everyone.

**Comment by AlexKVal** [comment]
I apologize for my haste :blush: 

Just wanted to deal with as much open issues as I can :rocket: 

I've done it as I used to do it with private projects in my company 
(where all decision making is on me)

Just an old good custom in the wrong place :blush: 
(motto: if you want to ship a product in the sensible period of time, you have to say 'no' a lot of 'wants and wishes', otherwise the next version will never be released)

I really appreciate your patience and guidance on this :cherries:

**Comment by mathieumg** [comment]
> if you want to ship a product in the sensible period of time, you have to say 'no' a lot of 'wants and wishes'

With milestones, it's all about triaging those properly, and pushing back if that comes up. Of course, some don't have their place in library land and should be discarded.

**Comment by ariporad** [comment]
I'd like to try to add some active props to some things, is there anything I need to do before I start (ex. Checking with someone, adding my name to a list, etc.)?

**Comment by taion** [comment]
@ariporad Nope, just go for it!

**Comment by taion** [comment]
This was actually resolved.
