### ISSUE TITLE
How to solve peer dependency below

### ISSUE THREAD

**Issue by wmgstar** [react-bootstrap/react-bootstrap#3532]
![Screen Shot 2019-03-07 at 4 50 51 PM](https://user-images.githubusercontent.com/47307975/54093634-21cfe800-4357-11e9-94ca-89c12455c5b1.png)

**Comment by taion** [comment]
not related to this repo; we don't depend on ts-pnp

**Comment by wmgstar** [comment]
please check image
```
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 -3 but none is installed.
```

**Comment by jquense** [comment]
also (confusingly) not us. that's the vanilla bootstrap package, which we don't depend on but do suggest installing for the css. You can safely ignore the warning or if you don't want it, vendor in the bootstrap styles, or use them from a CDN. We can't really "fix" this otherwise as it's upstream from us.
