### ISSUE TITLE
Event key is being cast to string.

### ISSUE THREAD

**Issue by illogicz** [react-bootstrap/react-bootstrap#3536]
The documentation states it is an any type, but the event receives the passed value cast to a string. This does not seem desirable. Is there a reason for this?

**Comment by jquense** [comment]
yes we really should be clearer about this in the docs! it needs to be serializable to a string because in lots of casuses the key is actually stored on the DOM node as a `data-*` attribute in order to coordinate focus and selection states. Yes this was the best way to do it, the more react-y way would be a lot more code and less reliable.

**Comment by scrust** [comment]
Following up from #3957, in addition to updating the docs the [type definitions for `eventKey`](https://github.com/react-bootstrap/react-bootstrap/search?l=TypeScript&q=eventKey) will also need to be updated; it seems like most are already typed as `string`, `unknown`, or `any`, but the types for `DropdownItem` are _particularly_ misleading:

https://github.com/react-bootstrap/react-bootstrap/blob/d9429a93e989c69e019bffac37b8b0eb75ff3a7c/types/components/DropdownItem.d.ts#L7-L14
