### ISSUE TITLE
Setting flip to false on DropDown does not work.

### ISSUE THREAD

**Issue by tzanis** [react-bootstrap/react-bootstrap#3589]
Even though I m setting flip to false, I still see dropdown flipping position.

Example here: https://codesandbox.io/s/o4wppl4x5y .

**Comment by taylormadesoft** [comment]
Hi Guys, Any fix on the flip issue?  Have not figured out workaround yet to solve to force dropdown to not flip and stay "down" or direction given to the "drop" attribute.
Thanks,
JT

**Comment by srianbury** [comment]
Until there is a fix try setting the flip prop on Dropdown.Menu not Dropdown.

**Comment by harsh6646** [comment]
My team and I would like to work on this issue.
@alexeicoreiba @KohilanMohanarajan @gagankbl @KostyaIliouk

**Comment by KohilanMohanarajan** [comment]
Upon looking more into the issue, it seems that the issue is within react-overlays, and not the Dropdown module itself.  react-overlays deals directly with popper.js, which is obfuscated in the main react-bootstrap project.  If it hasn't been brought up in the react-overlays project yet, I would consider opening a ticket to deal with it there.
