### ISSUE TITLE
replace external CSS with inline styles

### ISSUE THREAD

**Issue by AprilArcus** [react-bootstrap/react-bootstrap#362]
Vjeux's excellent [slide deck](https://speakerdeck.com/vjeux/react-css-in-js) and [talk](https://vimeo.com/channels/684289/116209150) "React: CSS in JS" makes a scathing indictment of current CSS practices that will resonate strongly with bootstrap users who have been frustrated by its pollution of the global CSS selector namespace:

>It is really crazy to me that the best practices in CSS is still to use global variables. We learned in JS for a long time that globals are bad. […] Yet we still use global variables everywhere in CSS-land. For example, Bootstrap introduces a whooping 600 global variables :(

Particularly egregious is the liberal use of unqualified HTML tags as selectors. This can be a real problem when bootstrap is added post-hoc to an app with a home-grown widget toolkit, or when trying to add someone else's custom widget to a bootstrap project.

I think this project is in an excellent position to refactor away from this pattern, eliminating bootstrap.css as an external dependency and allowing smooth interoperation with other front-end frameworks and react components. This will be a multi-stage process:

  1. Pick a version of bootstrap to fork from, and include bootstrap.css as a dependency in the test runner.

  2. Remove tests based on DOM element class names and replace them with tests based on successfully applied DOM element styles

  3. Add inline styles to each component, remove bootstrap class names, and ensure that all style tests continue to pass.

  4. Remove bootstrap.css as a dependency.

Additionally, we will need

  * Some way of compartmentalizing bootstrap's global CSS reset. My first thought is to store these general-purpose styles in a mixin object and import into the relevant components on an as-needed basis. We could use a similar approach to support bootswatch theme variables.
  * A re-implementation of the grid system's `@media-screen` breakpoints. We could do this by having `<Grid>` listen to `window.onresize` events and trigger updates when necessary.
  * Either a container component for styled text responsible for recursively iterating over and styling its `props.children`, or react-bootstrap counterparts for each of the basic tags (`<P>`, `<H1>`, `<H2>`, `<Ul>`, `<Img>`, etc)

If the maintainers feel like this is a good direction, I am happy to start writing tests!

**Comment by mtscout6** [comment]
This has been a though on my mind as well. Thanks for putting together a better action plan than I could have! 

An additional concern I've had with this is that existing [React Inline Styles](http://facebook.github.io/react/tips/inline-styles.html) documentation highlights how to use vendor specific prefixes, but I'd rather use something like [AutoPrefixer](https://github.com/postcss/autoprefixer). This is a direction that Bootstrap has taken as well twbs/bootstrap#12670. 

I'd like to get additional buy in from a few of the other maintainers and the community.

/cc @react-bootstrap/owners

**Comment by mathieumg** [comment]
This is definitely something I'd love to see too. :+1: for AutoPrefixer as well. If it's done well it could be very beneficial for a number of reasons.

I'm sure some people will be against such a change *today* however (they should voice their concerns here!), so this might be something that needs opting-in, but that certainly would add extra complexity to manage and/or overheard to the resulting code.

**Comment by AprilArcus** [comment]
Opt-in is the only sane way to start. We'd put an `inline-style="true"` flag in the component props. The test runner would open two iframes, include bootstrap.css into one and render a component with the flag set to false, render a component into the other with no style sheet and the flag set to true, extract the style object for each from the DOM, diff them and report discrepancies.

**Comment by mtscout6** [comment]
Another concern that should be address is for those that start with stock bootstrap and then tweek styling here and there but keep the same class names. So we would need to have some kind of means to merge or overwrite styles.

I think at this point spiking something out to give some folks code to see would help sway those who are on the fence. By all means try it out and let us know what you learn.

**Comment by mtscout6** [comment]
I'm not fond of the actual implementation this guy uses, but it at least highlights a possible api for AutoPrefixer like support: https://github.com/nmn/react-stylePrefixr. Or it may be worth our time to see that it utilized the caniuse-db, nmn/react-stylePrefixr#2.

**Comment by AprilArcus** [comment]
I think it's cool that he prefers information available from the browser at runtime over something like caniuse-db, but 

> All properties are left untouched when run in Node.

would be a problem for isomorphic apps. I think the right thing to do is prefix as aggressively as possible when run server-side.

**Comment by mschipperheyn** [comment]
I would personally be more interested in this approach if in stead of applying in-line styles which sounds very hard to maintain, a parser would be written that applies LESS and SASS in-line. Given the existing javascript parser for LESS it might not even be all that hard to write. Haven't really thought it through completely yet but it should be possible.

**Comment by mathieumg** [comment]
I imagine it's relevant to mention https://github.com/FormidableLabs/radium-bootstrap here.

**Comment by mschipperheyn** [comment]
Yeah, it looks like it's going in that direction somewhat

**Comment by ironblock** [comment]
One of the reasons I use Bootstrap is that it's a "known quantity" and has a really low barrier to entry. Members of my team who are less familiar with the latest web trends are still able to use it, and we compile LESS as part of our build step. There's a single master LESS file that pulls in the Bootstrap LESS source from Bower, and then applies our overwrites (basically just re-written sections of variables.less), and finally our own LESS.

It also means that our buildout pattern is to do a "skank UI" in default bootstrap first, and then restyle and tweak in a cleanup pass, adding whatever new LESS we need at that time.

It's hard for me to imagine that something like Radium would be a simpler way to execute that workflow, or that it would offer a better alternative out of the box.

Based on the specificity of inline styles, I see three outcomes:
- Do all your overwrites to the components themselves, through props or mixins or something else
- Accept the style choices made by the component's authors and don't even try to overwrite them
- Roll your own components, which negates the entire point of using a library

Am I missing something? Or is this a proposal to remove the cascading nature of cascading style sheets? I'd really like that not to be the case.

**Comment by sthzg** [comment]
+1 ``react-bootstrap`` together with the common build-tools already provide a nice workflow to cherry-pick components. I can imagine many use cases in which only a few selected elements from bootstrap are needed. But as long as the Bootstrap CSS needs to be loaded on the host page its styles are very likely to clash with existing styles.

**Comment by 0xdabbad00** [comment]
I believe this idea does not play nicely with Content Security Policies (CSP).

**Comment by AprilArcus** [comment]
@mathieumg — Radium looks interesting. Perhaps using a Turing-complete language for styling really is overkill; I may try re-implementing `<Button>` their way and see how the experience compares.

@ironblock — You understand the proposal correctly. As I stated above, I think as we move in this direction we should maintain the expected classnames and present inline styling as an opt-in. There are clear tradeoffs with this approach that we must acknowledge.

@0xdabbad00 — `<style>` tags are different from `<div style="...` attributes; CSPs are not applicable.

I've developed `<Button>` into a [proof of concept](https://gist.github.com/AprilArcus/9f7affd7bfe7680de27d). The idea works and is useful. Instead of adopting the BDD approach outlined above, I pragmatically adapted the logic of the underlying LESS source to JavaScript. This leads to a terser component with clearer logic — we avoid setting and then overriding certain properties in the case of link-style buttons and disabled states — but of course, it's harder to be sure that it's correct. In particular, it doesn't work in Mobile Safari (due to not utilizing the global CSS-reset), and hasn't yet been set up to render `<button>` and `<a>` type bootstrap buttons. 

One obvious area for improvement is that the style functions should be made into pure functions in terms of bsStyle, bsSize, and props.style, so that they can be memoized.

**Comment by jquense** [comment]
It should be noted, that while inline styles solve some issues with css, they are not issues that we all have. Specifically facebook, deals with a level of complexity and scale that makes managing css difficult, but I most of us don't operate at that level of complexity. I mention this only because inline styles also introduce their own set of problems and complexity, it isn't without cost. In our experience inline styles are just not worth it (and we have some reasonably large projects), they introduce problems that end up leading one to build a  less preformant and feature rich css engine in javascript. 

Certain things are just very difficult to do in inline styles, and require that a consumer shoulder the burden of managing those issues. For instance take a line from the bootstrap modal style:

```less
.modal-footer {
  .btn + .btn {
    margin-left: 5px;
    margin-bottom: 0;
  }
  .btn-group .btn + .btn {
    margin-left: -1px;
  }
  // and override it for block buttons as well
  .btn-block + .btn-block {
    margin-left: 0;
  }
}
```

the above is extremely difficult to deal with programmatically, without requiring that the modal consumer, handle `btn` spacing themselves. Just handling the descendant selector is hard (ignoring the very complicated sibling one). You can try to have the Modal footer component check its children  and clone them with the styles they need (what if the the buttons are grand children?), you can also try and use context (needs to be parent based, not here until 0.14), Or you do something like have a `modalFooterButtonStyles` object with the right styles that you expose and require the user to mix them in when they use buttons in the footer (I think this is what Facebook does?). In my opinion all options are bad. The first two require fragile hacking of components and essentially just re-implement the part of the selector engine in js. The last option is fine, but verbose and introduces its own set of management issues, and exposes a lot of new api surface area.

My point is not that it is impossible to, but that you can't just simply switch to inline styles, it costs something, you need to think differently from the beginning about how you structure and export styles. The cost may be worth paying for large projects like Facebook (or projects with many teams), but for most of us it is just going to be a burden with little to no practical benefit, especially when bootstrap already offers both less, and sass versions of their stylesheets.

I admire the desire to maintain both, but I don't see how that would be possible (I could be wrong). You'd need to maintain a _seperate_ repo for inline styles otherwise if I don't use them I am going to be pulling down a lot of extra bytes for style code I don't use. And as I tried to illustrate above, not all styles will just translate without changing the API or user expectation.

**side point**. inline styles also means that ALL bootstrap themes will no longer work with react-bootstrap.

**Comment by AlexKVal** [comment]
It seems that solution for `react + bootstrap inline styles` would be a creation of a stand-alone project.
Can we close this issue if there are no objections ?

**Comment by mtscout6** [comment]
I've been on the fence for a while now about this, and without seeing any real progress on making it happen I'm fine with closing it. If anything changes which can sway this discussion then we'll consider re-opening it.
