### ISSUE TITLE
Usage with Next.js?

### ISSUE THREAD

**Issue by corysimmons** [react-bootstrap/react-bootstrap#3646]
https://react-bootstrap.github.io/getting-started/introduction#browser-globals says to import unpkg.com links to add stuff to the `window` object, but when I do this, I get a console warning:

```
Uncaught TypeError: Cannot read property 'createContext' of undefined
```

What about SSR? Can we get some Getting Started docs on how to use this in an SSR environment?

**Comment by taion** [comment]
looks like these docs are screwed up due to the same bug as in https://github.com/react-bootstrap/react-bootstrap/issues/3540

if you want to see the instructions, navigate away from that page via links and navigate back. the way you do this is to just install the relevant deps via npm, then import things that way.

**Comment by arenddeboer** [comment]
I guess this had nothing to do with the linked doc issue. Did you find a solution or is react-bootstrap not ready for universal / SSR scenario's.

**Comment by corysimmons** [comment]
Dunno. I just decided not to use it.
