### ISSUE TITLE
Add a codesandbox starter

### ISSUE THREAD

**Issue by Shelob9** [react-bootstrap/react-bootstrap#3844]
## Is your feature request related to a problem? Please describe

It would be really helpful if there was a quick link in getting started to a Code Sandbox with everything setup and ready to test.

## Describe the solution you'd like

Add a link in the docs to a code sandbox. I made one: https://codesandbox.io/s/brave-star-p38k1?fontsize=14

**Comment by bpas247** [comment]
FWIW, I've had this code sandbox open for a few months now, I do my best to keep it up to date with the latest version since I fork it pretty frequently to show off different examples on our channel in the Reactiflux server. [Link](https://codesandbox.io/s/reactbootstrapnextstarter-9oopv7km04)

The biggest issue I would have with something like this is that CodeSandbox repositories don't have tight version control, unless it's integrated with a specific GitHub repository.

Maybe we can consider creating a GitHub repository on our org page and integrate a CodeSandbox repository for it?

**Comment by taion** [comment]
That sounds like a great idea. It'd be a great use of the GH org.

**Comment by bpas247** [comment]
Awesome, I can work on getting this setup then :+1:

Should we call the new repository `code-sandbox-example`?

**Comment by Shelob9** [comment]
This is awesome. I would be happy to contribute examples in the demo sandbox.

**Comment by jquense** [comment]
🙌 sounds great!

**Comment by bpas247** [comment]
Quick update: I have initialized this repository ([Link](https://github.com/react-bootstrap/code-sandbox-examples)) under the name `code-sandbox-examples`, in case we end up having multiple sandbox examples.

I will push a common setup of a create-react-app (I'm open to suggestions about this setup ✌️ ) project soon, with a very basic example that uses React-Bootstrap components. Then we should be able to just import this directly into a CodeSandbox repository :tada:

**Comment by bpas247** [comment]
I'm gonna close this issue for now.
@Shelob9 Please feel free to open a PR to add your CodeSandbox example to the `code-sandox-examples` repo :slightly_smiling_face:
