### ISSUE TITLE
<Nav.Item> in <Nav> ignores the id prop

### ISSUE THREAD

**Issue by vatosarmat** [react-bootstrap/react-bootstrap#3940]
## Describe the bug

Can not set id attribute to ListGroupItem

## To Reproduce

Just type something like this and look into browser DevTools - ListGroup has an id, but list items doesn't
```   
	  <ListGroup id="items">
        <ListGroupItem id="item1">Pit</ListGroupItem>
        <ListGroupItem id="item2">John</ListGroupItem>
        <ListGroupItem id="item3">Ivan</ListGroupItem>
      </ListGroup>
```

![Screenshot from 2019-06-22 12-39-14](https://user-images.githubusercontent.com/35213999/59958498-03978d80-94eb-11e9-85b6-7e4152b6326c.png)

## Reproducable Example

https://codesandbox.io/embed/frosty-ride-252jt

**Comment by taion** [comment]
This is happening because `<AbstractNavItem>` always takes `id` from its nav context when present: https://github.com/react-bootstrap/react-bootstrap/blob/9e18f95d48c7498fcc3b0311a8ed1c08575fb987/src/AbstractNavItem.js#L50

But this only really makes sense in the context of `<Tabs>`. @jquense what do you think is the right thing here?

**Comment by baktiaditya** [comment]
@taion hi, can you review this PR #4618 thanks

**Comment by kyletsang** [comment]
Tested on 1.3.0 and original example works now
