### ISSUE TITLE
Tab and Tabs should allow `href` to control pills URLs

### ISSUE THREAD

**Issue by vitpankin** [react-bootstrap/react-bootstrap#4083]
## Is your feature request related to a problem? Please describe

My current solution is to use weird composition of `NavLinks` and `Tab.Content`/`Tab.Container`/`Tab.Pane`. This is not elegant in any meaning. Since you rendering ul>li>a anyway why wouldn't to add this possibility?

## Describe the solution you'd like
Add a `href` prop to `Tab` component which will be added as a `href` to `ul>li>a` in Tabs navigation.

**Comment by taion** [comment]
It is indeed the case that you're supposed to use the lower-level API when doing custom nav stuff. `<Tabs>` is intentionally only suitable for very simple use cases.

Follow https://react-bootstrap.github.io/components/tabs/#tabs-custom-layout and just render a `<Nav.Link>` with `href` instead of `eventKey`.
