### ISSUE TITLE
Beta to Public Release

### ISSUE THREAD

**Issue by trish123** [react-bootstrap/react-bootstrap#4138]
Any tentative date for removing beta from the React Bootstrap?

**Comment by ostyn** [comment]
I would also be interested in this! What are the blockers currently?

**Comment by bpas247** [comment]
We've recently had a closed discussion about the future roadmap of the full release for React-Bootstrap, and besides #3563 there isn't much else we are currently hoping for the full release.

A lot of it just boils down to how confident we are as maintainers of this library to release the full version, which I think we are nearly there 😃

I'm thinking we should open a new issue to further discuss the explicit details for the full release, just so that it's transparent enough as to what needs to be done for it.

**Comment by kosmiq** [comment]
Closing this since it has been answered.

**Comment by warunikar** [comment]
@bpas247 Is there an ETA on the beta to public release?
