### ISSUE TITLE
Change calls to e.preventDefault() to allow onClick and onSelect calls to override

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#419]
There has been a number of concerns raised recently regarding `e.preventDefault();` getting applied without regard for what a developer would actually want to occur. This occurs regularly when attempting to do client side routing. [This search](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue+is%3Aopen+preventDefault) will highlight a few such cases.

I'd like to move to a more consistent model similar to [this](https://github.com/rackt/react-router/blob/v0.12.4/modules/components/Link.js#L59-L76). Where the user's `onClick` or `onSelect` handler can return true or false to explicitly control it. This is also similar to how [jQuery](http://stackoverflow.com/questions/1551389/how-to-enable-default-after-event-preventdefault) has handled things.

List of components to address: (Not conclusive yet)
- [ ] Dropdown
- [ ] Panel (Collapse)
- [ ] PanelGroup
- [ ] Button
- [ ] Nav
- [ ] Navbar
- [ ] NavItem
- [ ] Carousel
- [ ] CollapsableNav
- [ ] PageItem
- [ ] Pager
- [ ] Split Button
- [ ] TabbedArea

refs about documenting it:
#432
#320

**Comment by stefanfisk** [comment]
Per http://facebook.github.io/react/docs/events.html, React no longer checks the return value of event handlers to decide how to proceed. If we do this, the behaviour will probably be unexpected by a lot of people, since one wouldn't expect to have to read the docs to figure out how onClick and other standard handlers work.

In es6 it is also easy to accidentally write event handlers that return values when using fat arrows without curly braces, potentially leading to hard to identify bugs.

**Comment by stefanfisk** [comment]
My point is that if the behaviour is to be implemented then the handlers should use non-standard names to make it clear that they implement specific behaviours.

**Comment by mtscout6** [comment]
Good points, thanks! I can agree with your points and go without a return value for those event handlers. 

We can still check the event value `event.defaultPrevented` which may be all we need in most cases. Although we'll have to take it on a case by case basis, but I think that should take care of most of the scenarios. 

With Dropdown MenuItem with an href this gets tricky. In a client side routing scenario such as described in #368 we want to call `event.preventDefault()` to stop the browser from following a link, but we still want the dropdown to close.

I see three options:

1. Stick with an `onSelect` event where we pass the original `event` where we depend on the handler to append a `selected` property on the event directly. If that's set to true then we continue with closing the dropdown.
2. Add an additional parameter to the `onSelect` handler function which does something similar to what `event.preventDefault()` does today.
3. Have the `onSelect` function return a boolean.

I'm leaning towards #1, though I don't know how well this translates to the other cases where we are imposing our will in other `onClick` chains.

**Comment by vinnymac** [comment]
1. is a great option. It will become more than a footnote in the documentation, as it is an additional property. 
2. is the worst option, as it is unfamiliar and deceiving in functionality. 
3. isn't too bad because there are those who are familiar with jQuery, and will be able to associate the behavior, the downside comes to explaining this in the documentation, as everyone who uses react is not necessarily a jQuery user (myself included).

So if I had to pick one of those it would definitely be 1. I have run into this problem myself, and at that moment I looked at the source code for a prop I could use to modify the behavior of ```onSelect```.

**Comment by stefanfisk** [comment]
how about a `shouldCloseOnSelect` property which accepts a boolean or a handler which is passed the event? `shouldCloseOnSelect` would then be handled in `onClick`, and allow developers to both specify if the drop down should close and if the event should stop propagating etc.

**Comment by joemcbride** [comment]
I'm liking option 1.

I think `shouldCloseOnSelect` is a little too specific of a name.  For instance, that name wouldn't make sense when working with panels.  I think it would be easier on us developers to have a consistent name to work with across all controls.  `selected`, `handled`, `defaultPrevented` - something like that would make sense.

**Comment by stefanfisk** [comment]
my suggestion was that the component should have that property, not the event, such that if the property is not defined then the component does nothing. and the naming is probably crap, I was just thinking about the general pattern.

**Comment by mtscout6** [comment]
I'll go ahead and say that we should use option 1 going forward.

**Comment by santiagoaguiar** [comment]
+1 to @stefanfisk suggestion. 

Having it as a property on the control to say if it should close after the select event is handled is less magical than having to append a new property to the reactjs event object. Better to stick to the idea of handling object types as if static, instead of adding props on the fly (and the option of adding yet another wrapper over the event seems overkill to support an edge case). Also, appending properties breaks stuff like typescript (and I guess other type checking tools, like flow, too).

Returning something form the event handler can also work, but it's also obscure, and might not scale well...

In any case +1 to have a way of avoiding the dropdown to close on select ;).

**Comment by mtscout6** [comment]
I know it's been a while since we initially discussed this, and we haven't done too much action against it yet. I'm preparing some documentation on plans for a 1.0.0 roadmap and this is one of the concerns.

@stefanfisk I'm not too keen on having an additional prop on components, primarily because of the overhead to understand and document that this is only related to the handling of specific events.

@santiagoaguiar I can see where you are coming from about appending an additional property on the event itself. I'm not personally familiar with either TypeScript or Flow; something I guess I should remedy soon :wink:. 

One issue I failed to address initially was that of the `eventKey`. At the time I did't feel that I entirely understood how useful it was, I'm coming around on that and feel that we should probably continue to support that as well.

The new function signature I'm thinking of is `function(event, selectedEvent, eventKey)` where:

- `event` is the original event
- `selectedEvent` is an object with signature of `ItemSelectedEvent`
- `eventKey` is the given eventKey for the item

Where `ItemSelectedEvent` is an object built something like:

```
function buildItemSelectedEvent() {
  let selectionPrevented = false;

  return {
    preventSelection() {
      selectionPrevented = true;
    },
    isSelectionPrevented() {
      return selectionPrevented;
    }
  };
}
```

What are your thoughts on this?

**Comment by santiagoaguiar** [comment]
I like that! Better than extend/wrap the original event IMO.

Can the 'eventKey' be a property of  'ItemSelectedEvent'?

**Comment by mtscout6** [comment]
I like that idea too so the above snippet would become:

```
function buildItemSelectedEvent(eventKey) {
  let selectionPrevented = false;

  return {
    preventSelection() {
      selectionPrevented = true;
    },
    isSelectionPrevented() {
      return selectionPrevented;
    }
    get eventKey() {
      return eventKey; 
    }
  };
}
```

**Comment by AlexKVal** [comment]
I am definitely not an expert, but I like the idea to not multiply props.

It leads to benefits
- less maintaining overhead. (the number of conponents is quite a few and probably will increase)
- less documentation overhead
- a bit easier and more generalized usage of components

I like that proposed function interface promotes API generalization. 
Components that needs it are quite different in mechanic and, 
as I've mentioned already, their number is quite a few to maintain

**Comment by mtscout6** [comment]
Looks like the NavItem has even more to consider with this, note how it is currently invoking `onSelect`:

[`this.props.onSelect(this.props.eventKey, this.props.href, this.props.target);`](https://github.com/react-bootstrap/react-bootstrap/blob/v0.24.3/src/NavItem.js#L65)

We aren't currently using this anywhere within the library or in react-router-bootstrap. Though folks may be using it from the `Nav` component. It was introduced in #262 but that PR doesn't really present a use case or even documentation of these extra parameters.

I think that in the spirit of this issue I'd like to remove these parameters. We will be surfacing the actual click event so it's default behavior can be prevented. Whether or not the event would be selected though is troubling me. If we say the event is not selected because it is loaded on another page what should happen to parent components handling state such as expanded or collapsed? If we say that the item is selected will that cause problems with the parent changing other view states without being aware of another page getting loaded? 

It seems to me that the only way to cleanly handle this is to have two possible states that can be prevented on the selectEvent. First is the selection all together which would be used to prevent application state changes. The second being the atomic component selection which is used solely for the  [molecule](http://patternlab.io/).

I still need to stew on this a little bit but I wanted to get my thoughts and concerns out and potentially get feedback from the community.

**Comment by jquense** [comment]
I would like to chime in a bit on this, I admit i have missed most of the conversation (I tried to catch up) on this issue and am definitely not super qualified to offer suggestions here but I am wondering why we don't just do this the idiomatic React way. and make these props properly controllable?

If the user wants to control what happens when something fires then they specifically opt into controlling that behavior, otherwise the component handles it for them. This approach is already tried and true, declarative, and composes _really_ well without creating another psuedo event system.

for instance if an `onSelect` action would like to 

- close the popup
- change the value

Then it fires two handlers: `onChange` and `onToggle`, If the user wants to do something different with the close/open state they can add an `onToggle` and `open` prop to handle it, and the value will still be set without them. or they can control both, or none. This seems like a better idea then trying to have something like `onSelect` control a bunch of different unrelated state.

as discussed in #820. we can use a library to make this sort of thing really straightforward to add.

**Comment by jquense** [comment]
To address another little concern about that is that you can still have `onSelect` function like an event, returning whatever it wants but internally we can fire additional callbacks, that function solely as notifiers to the parent that they want some state adjusted; the `onRequestClose` sort of things.

**Comment by taion** [comment]
@jquense That sounds really elegant! :+1:

**Comment by mtscout6** [comment]
@jquense I'm coming around on this, it sounds familiar to what @stefanfisk was proposing earlier. I originally thought the event approach wouldn't be that complicated, though it is definitely proving to be so.

**Comment by jquense** [comment]
I think we are either done, or on track for this to be done. Most cases now use uncontrollable and preventing library functions is a matter of controlling them or not. Internally we now only call preventDefault where it really makes sense, such as `SafeAnchor`.

gonna call this ✅
