### ISSUE TITLE
test: BootstrapModalManager

### ISSUE THREAD

**Issue by mxschmitt** [react-bootstrap/react-bootstrap#4206]
Seems to be that [src/utils/BootstrapModalManager.js](https://github.com/react-bootstrap/react-bootstrap/blob/5f0bb108e8b1fe581ca9be67a397ff7851d0f885/src/utils/BootstrapModalManager.js) is obsolete.

@taion? what do you think? The `qsa` selectors will never be called.

**Comment by taion** [comment]
It's used here, no? https://github.com/react-bootstrap/react-bootstrap/blob/0d02bf6d279d227f92703520b3e45727bfded3bf/src/Modal.js#L171

**Comment by mxschmitt** [comment]
Sure, but unit tests does also pass and the behavior in my mind is the same when we pass the default `import ModalManager from 'react-overlays/ModalManager';`

**Comment by taion** [comment]
@jquense What do you think? We do use this in our code... is it pointless?

**Comment by jquense** [comment]
It's not pointless, it auto adjusts the fixed and sticky navbars so they don't shift when the body scroll is hidden. Likely this is not something the tests cover, but it makes a difference in user experience. 

I do know that this works because when we used it directly recently in our code at work it fixed the shifting navbars :P

**Comment by mxschmitt** [comment]
So maybe possible to cover it by tests? :)

**Comment by bpas247** [comment]
> So maybe possible to cover it by tests? :)

Covering this via integration tests should be enough, I would feel wary about unit testing it directly.
