### ISSUE TITLE
Collapsable => collapsible

### ISSUE THREAD

**Issue by wmertens** [react-bootstrap/react-bootstrap#425]
the correct spelling is "collapsible". Perhaps change all occurrences in the code and provide aliases where appropriate?

**Comment by mtscout6** [comment]
If we provide an alias than usage of the Alias should output a warning to the console so we can plan to deprecate it later.

**Comment by dozoisch** [comment]
Adding that to 1.0.0 wiki

**Comment by AlexKVal** [comment]
I have already refactored CollapsableMixin => CollapsibleMixin.
All tests are green and dependent components are working with deprecation warnings.

**Comment by AlexKVal** [comment]
*Rename property `collapsable` => `collapsible` for 
CollapsableNav, Nav, Panel and PanelGroup components*

This is not trivial task and I move it into standalone issue #589,
because it includes components that doesn't connected 
with CollapsableMixin and CollapsableNav.
> Nav, Panel and PanelGroup

**Comment by AlexKVal** [comment]
Deprecations
-

Components 
`CollapsableMixin` and `CollapsableNav` 
were moved respectively into
`CollapsibleMixin` and `CollapsibleNav`.

`CollapsibleMixin` has and use four methods.
-
It has in itself 
`getCollapsableClassSet()` => `getCollapsibleClassSet()`

It awaits existence of these methods in component
`getCollapsableDOMNode()`= > `getCollapsibleDOMNode()`
`getCollapsableDimensionValue()` => `getCollapsibleDimensionValue()`
and this one is optional. It can be defined or not defined in component:
`getCollapsableDimension()` => `getCollapsibleDimension()`

### `CollapsibleNav` doesn't contain renamed public API methods.

Use of old named components and methods causes warnings about deprecation in console.
Minified version of `react-bootstrap` does not write any console warnings, because this code are stripped out by `webpack DefinePlugin`.

These warnings also will be stripped out if you are using `envify` or `webpack DefinePlugin` in your project.

**Comment by AlexKVal** [comment]
What is left:

Rename property `collapsable` => `collapsible` for
- [ ] Nav
- [ ] Panel
- [ ] PanelGroup

**Comment by AlexKVal** [comment]
This function
```js
function collapsable(props, propName, componentName) {
  if (props[propName] !== undefined) {
    deprecationWarning(
      `${propName} in ${componentName}`,
      'collapsible',
      'https://github.com/react-bootstrap/react-bootstrap/issues/425'
    );
  }
  return React.PropTypes.bool.call(null, props, propName, componentName);
}
```
is needed to use in `CollapsibleNav`, `Panel` and `PanelGroup` components.
It is about deprecation and will be deleted at some point in future.

I don't want to create another file in `utils/_function_for_collapsable_prop_check_.js` 
(naming should be another of course)

I want to put it into `utils/deprecationWarning` as 
```js
export default function deprecationWarning(...)
...
export function collapsable(props, propName, componentName){...}
```
and then use it in those three components as:
```js
import deprecationWarning, {collapsable} from './utils/deprecationWarning';
```

Any thoughts ? Suggestions ?

**Comment by AlexKVal** [comment]
Another question:
It seems the `collapsable` property in `PanelGroup` is kind of `rudiment`:
here [PanelGroup.js#L13](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/PanelGroup.js#L13)

It was introduced by this patch https://github.com/react-bootstrap/react-bootstrap/commit/855e5b29cb, but it doesn't used anywhere.

This is a property of locally created `props` object for the child
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/PanelGroup.js#L54

Does this property need deprecation warning or we can just remove it ?
(I've checked: If I remove it then neither tests nor docs are broken)

**Comment by mtscout6** [comment]
I think that one can just be changed to `collapsible` without a problem. It's being used in the `cloneElements` call, so it really depends on what's being cloned. But if it's cloning a `Panel` and if `Panel` can already handle `collapsible` than just renaming it should be fine.

**Comment by yordis** [comment]
I know doesn't matter at this state but I am not agree with this change. We use a lot of -able subfix for non english words and we are fine with it (e.g https://github.com/plataformatec/devise ). It's even a standards sometime create whatever word use this when you need to say that word is an action.

I don't thing this was a valuable time. For me, this is weird now. :-1:

**Comment by wmertens** [comment]
In that case it should be CollapseAble. Javascript doesn't have cheap type
checking, let's not make things difficult by using non-existing words that
look like existing ones.

On Sat, Jun 27, 2015, 7:32 AM Yordis Prieto <notifications@github.com>
wrote:

> I know doesn't matter at this state but I am not agree with this change.
> We use a lot of -able subfix for non english words and we are fine with it
> (e.g https://github.com/plataformatec/devise ). It's even a standards
> sometime create whatever word use this when you need to say that word is an
> action.
>
> I don't thing this was a valuable time. For me, this is weird now. [image:
> :-1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/react-bootstrap/react-bootstrap/issues/425#issuecomment-115965008>
> .
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by AlexKVal** [comment]
Just an additional side note.

`CollapsibleMixin` could be deprecated and removed at all in a couple of releases
( if @jquense would allow it to happen :wink: )

here is the proposal
https://github.com/react-bootstrap/react-bootstrap/pull/848

like here
https://github.com/react-bootstrap/react-bootstrap/pull/848/files#diff-c5a88cb9e192df4b2a4e2ed9a0a18884L3

**Comment by yordis** [comment]
@wmertens Who defined what is English? Languages are defined by the people, culture, region ... There is no rule for actually say Collapseable instead of Collapsable. Just answer me something, Why, and just why, was there Collapable? Probably because is normal for this culture.

If we like developer defined that is a normal word, why you are saying is not a word when, again, we defined the language, the language doesn't defined us. What is nigger, what is bro, what is ...., what is acere in Spanish, or actually, what was nigger 60 years ago? Hopefully you get my idea because I just want to make you see the other side of that.

And my big point about this: time, the most important thing for us because probably maintain and update those thing come from people who actually have to take the free time and do it. This is the only thing I care about it.

**Comment by AlexKVal** [comment]
I believe that `React-Bootstrap`'s issues tracker is not an appropriate place for discussions about language nuances.

@yordis `React-Bootstrap` is an open source project, i.e. anybody can (and should :wink:)
contribute their ideas to it.

If you have anything to bring in, move ahead and make a PR :wink: 
PRs are very welcome. :sparkle: 

I'm locking this topic to prevent a 'flame'.
:cherries:

**Comment by jquense** [comment]
we all appreciate both sides to this issue and understand the cost of changing the names of things in terms of maintenance and time. in the future this mixin will most likely be deprecated and then removed so the whole thing is moot. 

rather then let this issue get into the fraught area of discussing the meaning of words and the subjectivity of language we are just going to lock this and call the discussion finished, having heard both sides
