### ISSUE TITLE
Revisit constants and configurability

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#440]
Issue #306 highlights the ability to modify the constants used for prop validation and mapping. The name constants is deceiving since they are not truly constant values. We should give some thought to this practice give it a proper name. When we do this we should add some documentation for those wishing to work with custom classes. Issue #404 is a fine example of such a case.

**Comment by trevorr** [comment]
Perhaps the right fix is to add `isKeyOf` to `CustomPropTypes` and use that within the `propTypes` definition of `BootstrapMixin`, so that additions to `STYLES` are used? I think it would also be better to add a function to `BootstrapMixin` to define new styles, rather than modifying `constants`. That would provide more control (e.g. add but not remove), clarity (`STYLES` being a map is strange from an external perspective), and debuggability (a place to set a breakpoint when styles are added), and it's slightly less of an exposed implementation detail. It might be reasonable to then make `constants` private again. Thoughts?

**Comment by AlexKVal** [comment]
Superceded by https://github.com/react-bootstrap/react-bootstrap/issues/646
