### ISSUE TITLE
Documentation bug: "React Overlays" doc page has a link to itself rather than to somewhere useful

### ISSUE THREAD

**Issue by gimbo** [react-bootstrap/react-bootstrap#4455]
## Describe the bug

The "React Overlays" doc page, which is quite short, includes a hyperlink which looks like it should take the reader to somewhere they can find out more info, but instead it's just a link to the same page the reader is already looking at.

## To Reproduce

TL;DR version: go to https://react-bootstrap.github.io/utilities/react-overlays/ and click on the 'react-overlays' link in the body of the page; it takes you nowhere.

Detailed steps a user seeking documentation might conceivably follow:

1. Go to https://react-bootstrap.github.io/
2. Click on 'Components', to go to https://react-bootstrap.github.io/components/alerts
3. Click on 'Utilities' in the sidebar, to go to https://react-bootstrap.github.io/utilities/transitions/
4. Click on 'React Overlays' in the sidebar, to go to https://react-bootstrap.github.io/utilities/react-overlays/
5. Find the text "are built on top of components from react-overlays" in the body of the page; click on the 'react-overlays' hyperlink in that text.
6. Nothing happens - it's a link to the same page.

## Expected behavior

I'd expect that link to take us somewhere with more info. Presumably it should go to https://github.com/react-bootstrap/react-overlays or https://react-bootstrap.github.io/react-overlays/

**Comment by malsf21** [comment]
Yeah that's reasonable, I think taking it to the documentation page for the project makes a lot more sense. I can quickly fix this in a PR!

**Comment by malsf21** [comment]
Interestingly, I think this is an error with how Gatsby and GitHub Pages interacts. The link points to [https://react-bootstrap.github.io/react-overlays/](https://react-bootstrap.github.io/react-overlays/) in the code, but clicking it gives an issue with Gatsby's router:

![image of error](https://i.imgur.com/F6kj4IR.png)

I think it's because Gatsby is looking for a `/react-overlays/` in the Gatsby project, which *doesn't actually exist*; rather, [https://react-bootstrap.github.io/react-overlays/](https://react-bootstrap.github.io/react-overlays/) is a different project page all together.

**Comment by bpas247** [comment]
https://github.com/react-bootstrap/react-bootstrap/blob/2e627302222dcc0c3e67c336ed05052b79dcf315/www/src/pages/utilities/react-overlays.js#L20-L22
It seems like if you open the link in a new tab, everything works fine. So should we just change the behavior to default to opening the link in a new tab?

**Comment by malsf21** [comment]
That makes sense, we could probably do that by just setting `target="_blank"` and `rel="noreferrer noopener"` on each external anchor tag.

**Comment by malsf21** [comment]
Submitted a PR! #4545
