### ISSUE TITLE
Example standalone HTML for this lib?

### ISSUE THREAD

**Issue by afcondon** [react-bootstrap/react-bootstrap#450]
I hope i'm not overlooking something obvious but i don't find that i have enough information on the "Getting Started" page to build the react-bootstrap components into even a simple hello world page from a "bower install react-bootstrap" sort of basis.

I get that it's supposed to be requireJS'd in or browserify'd in somehow but i have been unable in playing around with it to get anything working. Any advice or example would be much appreciated.

**Comment by mtscout6** [comment]
Can't say that I personally have a requriejs example, but you can see a commonjs example which is what our docs are based on. Check out the docs folder of this repo to see usage.

**Comment by afcondon** [comment]
thanks for the help - i'll look at the docs example again and see if i can work out what is needed. 

Aren't the docs served from express tho?

**Comment by mtscout6** [comment]
When running from dev on your local machine. In public they are generated static html files, which github serves. However, not using requirejs as you are specifically looking for.

**Comment by afcondon** [comment]
It doesn't matter to me at all whether it uses requireJS, i just need to work out how to generate that static version.

It seems that this gets done by the ```node build.js && browserify client.js``` in the docs directory which produces the bundle.js. I think that's probably what i need to work with.

thanks again for the pointers.

**Comment by rgehring** [comment]
I'll jump on this bandwagon as well---I'd love a pointer or tiny bit more docs on how to deploy this as a static page to github pages. For example, when I run 
```
npm run build
```
the build finishes and html and assets appear in the docs-built directory. But if I navigate a browser to the index.html in that directory, I receive javascript errors / failure to load css etc. I also receive checksum mismatch errors in the browser when i push the contents of docs-built to gh-pages and navigate to the corresponding github pages site.

Do you have a deploy script you could share, or a note about the process? Would be really useful, I'm more of a back-end hacker and less familiar with the node / react ecosystem. Thanks!

**Comment by mtscout6** [comment]
Have you seen this: https://github.com/react-bootstrap/react-bootstrap/blob/master/docs/README.md

**Comment by rgehring** [comment]
Yes, thanks for the reference. I'm able to get the app to run locally via the normal ```npm run docs``` and even ```npm run docs-prod``` which serves the page using static files. When I navigate to localhost:4000 everything works as expected.

However, I'm having trouble deploying these static files to Github pages (or opening index.html in my local browser). For example, if I open the static HTML index.html from the docs-built directory in a browser, I get checksum mismatch errors. This also happens when I stick the contents of docs-built in a github pages project. 

From a little googling it seems like checksum mismatch happens when React's application state doesn't match the state of the html on the page.I noticed in the code there is a window.INITIAL_PROPS variable 

https://github.com/react-bootstrap/react-bootstrap/blob/master/docs/src/Root.js#L45-L62

which seems to be designed to fix this issue, but I'm having trouble getting it to work.

Thanks for replying though, and I can understand if you have bigger fish to fry. However, in my opinion one of the weaknesses of javascript frameworks is that they often have complex deploy processes that lock out curious non-experts, even when the whole app is  'just' a single static page of html. It might possibly help you get more users to invest that last hour to really explain how to build something people can put on the internet without having to deploy an express server, if they are just trying to build a blog or static page to try out the framework. (This was my first React experience, if you can't already tell.)

**Comment by mtscout6** [comment]
That checksum is not matching because I haven't been able to figure out how to get the CodeMirror to work in Node. So that part is not currently getting rendered server side, thus the invalid checksum.

**Comment by rgehring** [comment]
Ah, thanks for the tip! I'll try carving up my fork to see if I can remove or fix the codemirror issue and get the index page to run in a browser. I'll update if I make any progress worth sharing.

**Comment by mtscout6** [comment]
Thanks!

**Comment by rgehring** [comment]
Hey, reporting back--- I spent a few hours investigating. Unfortunately for posterity, I wound up deciding that the 'easy way out' of just deploying an express server behind a CDN was simpler for me than trying to figure out all the checksum errors. Sorry for the cop-out! I really enjoyed using your library, though, and was able to get a little blog-like app set up. Thanks for helping investigate.

**Comment by taion** [comment]
To answer @afcondon's original question, if you were installing react-bootstrap from Bower, then the most straightforward approach would be to import the library as a browser global, per the "Browser globals" section of http://react-bootstrap.github.io/getting-started.html
