### ISSUE TITLE
Panel animation only happens in accordions

### ISSUE THREAD

**Issue by maxkorp** [react-bootstrap/react-bootstrap#453]
I have a few panels in a group, like so
```HTML
<PanelGroup>
  <Panel collapsable header="Panel A">
    Panel A's contents
  </Panel>
  <Panel collapsable header="Panel B">
    Panel B's contents
  </Panel>
  <Panel collapsable header="Panel C">
    Panel C's contents
  </Panel>
</PanelGroup>
```

They collapse and expand properly (and individually, which is what I want), but they don't animate, they just snap open or closed instantly. In the demos here http://react-bootstrap.github.io/components.html#panels (The panel with tables example, the id is wrong on that header so I cant link it) that works (well it works outside of a panelgroup, but I tried that too).  
If i take out `collapsable` from the panels and make the group `PanelGroup accordion` (or `Accordion`) the animation works, but only one can be open at a time. As a bit of a workaround, I've got each panel wrapped in an accordion, but that seems cludgy. Any ideas whats going on?

**Comment by mtscout6** [comment]
I tried commenting on this yesterday, but guess it didn't post properly.

I tested your example on the docs page with Chrome and the animation worked just fine. I'm wondering if this is a browser specific issue, which browser did you test this on?

**Comment by maxkorp** [comment]
Hrm, its inside of atom-shell v0.20.7 which is based on Chromium 0.39.

**Comment by kaoz28** [comment]
I am also seeing some weird stuff going on with the Collapsable Mixin (which is used by <Panel collapsable>).  I am posting this here as I was also forced to use the <PanelGroup accordion> to get a collapsing animation.  The examples on (http://react-bootstrap.github.io/components.html#panels) for "With tables and list groups" and "Collapsable Mixin" won't even run anymore since classSet() function isn't even part of react (react/addons) anymore per this link (https://facebook.github.io/react/docs/class-name-manipulation.html).  Even including that new project yielded no results.  Anyone seeing this as well, or is it just me.  I already poked around SO, and IRC react chats.  No luck so far.

**Comment by mtscout6** [comment]
The current version of react-bootstrap is v0.20.0 and the classSet deprecation in react occurs in react v0.13.0, which we have accounted for since v0.18.0 of react-bootstrap. We accounted for the classSet deprecation by pulling in the [classnames](https://www.npmjs.com/package/classnames) dependency.

The current [`CollapsableMixin`](https://github.com/react-bootstrap/react-bootstrap/blob/v0.20.0/src/CollapsableMixin.js) does not use or have a dependency on a `classSet` functionality.

**Comment by mtscout6** [comment]
@maxkorp Are you still running into your issues?

**Comment by maxkorp** [comment]
@mtscout6 Yeah, but I just ended up stuffing things into individual accordions to get it working. A quick test confirms it's still an issue.

**Comment by AlexKVal** [comment]
`Collapsible` mechanic will be totally remade by https://github.com/react-bootstrap/react-bootstrap/pull/848
