### ISSUE TITLE
autoFocus not correctly implemented

### ISSUE THREAD

**Issue by flolege** [react-bootstrap/react-bootstrap#4607]
Behaviour:

```
<Form.Control
  autofocus="true"
/>

```
is the only combination of autof(F)ocus and "true"/{true} that does work as expected.

However it raises an exception:
Warning: Invalid DOM property autofocus. Did you mean autoFocus?

Expected Behaviour: It should not raise an exception. 

Alternatively, another combination should work as expected.

**Comment by taion** [comment]
You can see that we don't do anything special for `autoFocus` here, and instead just pass it down to the `<input>`: https://github.com/react-bootstrap/react-bootstrap/blob/e976fd92d5243c03668244d1783cb0b94419ffc9/src/FormControl.js

In practice just doing `autoFocus` has been working fine for us.

**Comment by rockchalkwushock** [comment]
@taion 

This seems to still be an issue. I pulled down the repository and was looking at the source and as you state about at the moment the library is just forwarding props on to the component. Adding `autoFocus` causes the following  `<input autofocus="" />`. You mentioned above that in practice it is working for you. May I ask what versions you are running?

Since the library is not handling that is it React that is _suppose_ to be making that mapping from `autoFocus` to `autofocus="true"`?

Environment:

`react@^16.10.2`
`react-bootstrap@^1.0.0-beta.16`

The work around I came to for getting the element to focus was the following:

```typescript
const myComponet: React.FC = () => {
  const ref = React.createRef<HTMLInputElement>()
  
  React.useEffect(() => {
    if(ref.current) {
      ref.current.focus()
    }
  })
  return (
    // @ts-ignore (typing is off)
    <Form.Control ref={ref} />
  )
}
```

**Comment by taion** [comment]
It's a boolean attribute, so that's actually how it works: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/autofocus

Your issue may be more around when the input itself gets mounted.

**Comment by jquense** [comment]
React doesn't/shouldn't pass through autoFocus, b/c it provides it's own implementation of it

**Comment by rockchalkwushock** [comment]
@taion thank you for the speedy response. I think you are on to something with the mounting. We are doing something different there that could be effecting it. Thank you for idea!

**Comment by imageck** [comment]
> React doesn't/shouldn't pass through autoFocus, b/c it provides it's own implementation of it

AFAICT, all React does is call `focus()` on certain types of elements (i.e. interactive elements primarily), right? For some reason, `Button`s that `autoFocus` inside a `Modal` do not show the focus ring. With `Element.focus({ focusVisible: true })` it is visible but this option is only supported in Firefox.
