### ISSUE TITLE
onClick event for Simple Panel with header ?

### ISSUE THREAD

**Issue by mightwork** [react-bootstrap/react-bootstrap#466]
Is it any way to fire an event when a simple Panel is clicked by the user ?

**Comment by mtscout6** [comment]
The `Panel` component takes an `onSelect` prop which is invoked when it is clicked. We need better docs on this still but you can check out the click handler at https://github.com/react-bootstrap/react-bootstrap/blob/v0.20.1/src/Panel.js#L25-L37. The docs update is part of #419.

**Comment by mtscout6** [comment]
Does this help you accomplish what you needed?

**Comment by 01bit** [comment]
From what I gather from the code, the handleSelect() function is used only if the panel is declared as collapsable. What I actually want to do is to render a component when my Panel with heading is clicked. I was thinking of editing the /src/Panel.js file to add an onClick handler on the Panel's wrapper div and rebuilding the module.

**Comment by AlexKVal** [comment]
You already can do what you need because of that https://github.com/AlexKVal/react-bootstrap/blob/ccc50e01917ba75e5a983ba068c1db4b790bb85d/src/Panel.js#L58


Just try to copy / past this code into code-editor under a `show code` button
 http://react-bootstrap.github.io/components.html#panels:
```js
const panelInstance = (
  <Panel onClick={()=>alert('It works')}>
    Basic panel example
  </Panel>
);

React.render(panelInstance, mountNode);
```
:cherries: 

Does it help you ?
