### ISSUE TITLE
Button as input does not set type attribute

### ISSUE THREAD

**Issue by reykjavikingur** [react-bootstrap/react-bootstrap#4762]
## Describe the bug

The JSX code `<Button as="input" type="button" value="Click" />` renders the HTML `<input class="btn btn-primary" value="Click"/>`, which lacks the attribute `type="button"`. This also applies for the use cases with "submit" and "reset". This leads to incorrect functionality when used in forms as well as incorrect styling due to lack of type-attribute specificity.

- Operating System: [all]
- Browser, Version [all]
- React-Bootstrap Version [e.g. 1.0.0-beta.14]

**Comment by bpas247** [comment]
https://github.com/react-bootstrap/react-bootstrap/blob/2cdd633bd06d1efcb0a73a39db784cc49df10763/src/Button.js#L97-L99

Looks like this is intentional as of #4173, due to the original issue of #3340. I'm not really sure what the best approach would be here, since passing and not passing the `type` prop to custom components seem to both lead to inconsistent styling issues.

**Comment by kosmiq** [comment]
I think that the current behavior is correct. Not passing `props.type = type` when setting `as` makes it easier in a typescript project to not be forced to set all props.

Take this issue: https://github.com/react-bootstrap/react-bootstrap/issues/3596

By setting as to a you can send href etc without having to pass all the button props. Otherwise we would have to default to type="button" and provide an escape hatch for it (type="undefined") or whatever.

**Comment by kyletsang** [comment]
Could we apply `type` if `as === 'input'`?

We currently advertise the usage of "Button as input" [here](https://react-bootstrap.github.io/components/buttons/#button-tags), but it would never work properly due to missing type attribute.

**Comment by jquense** [comment]
we can make an exception for when it's an `input` since it'd be kinda broken otherwise

**Comment by taion** [comment]
We should probably distinguish between "default-inferred `type`" from "explicitly-specified `type`" – if the user specifies a `type` prop, we should always respect it.

**Comment by kyletsang** [comment]
> 
> 
> We should probably distinguish between "default-inferred `type`" from "explicitly-specified `type`" – if the user specifies a `type` prop, we should always respect it.

This makes more sense.  I'll amend the PR.
