### ISSUE TITLE
Versioning should match original project

### ISSUE THREAD

**Issue by user453584** [react-bootstrap/react-bootstrap#477]
Shouldn't the version numbers match those of bootstrap itself so developers can know what version of bootstrap they're using?

**Comment by mtscout6** [comment]
I would disagree, they are different projects coordinating two different technologies. If React bumps versions and Bootstrap doesn't, or if Bootstrap bumps a version and React doesn't which version do you use? We are trying to follow the [Semver](http://semver.org/) spec as closely as possible. We have not settled on a public API yet which is why we have not made a 1.0.0 release yet. Prior to the 1.0.0 release I have been trying to bump the minor version for breaking API changes.

It has been on my mind to outline a roadmap for our plans to arrive at a 1.0.0 release, I just haven't been able to get around to that yet.
