### ISSUE TITLE
Can't specify correct types for a wrapper component around `Button`, in TypeScript

### ISSUE THREAD

**Issue by garyking** [react-bootstrap/react-bootstrap#5013]
I've written a wrapper component for `Button`. Like this:

```ts
import { Button } from 'react-bootstrap';

function WrapperButton(props) {
  const { children } = props;

  return <Button {...props}>{children}</Button>;
}
```

Since I'm using this in TypeScript, I'm trying to add types to `props`. In addition to allowing all attributes that `Button` accepts, I also want to accept all attributes that the underlying `button` accepts (like `style`). 

The type definitions for `Button` in `react-bootstrap` is:

```ts
declare class Button<
  As extends React.ElementType = 'button'
> extends BsPrefixComponent<As, ButtonProps> {}
```

But if I set the type for `props` to `props: BsPrefixComponent<'button', ButtonProps>` then it doesn't accept attributes like `style` and `children`.

Is there a more appropriate type I could use, for this scenario? Or is there indeed something missing in the type definitions provided by `react-bootstrap`?

**Comment by jquense** [comment]
`props: React.componentPropsFor<typeof Button>`

**Comment by garyking** [comment]
Thanks. I got `React.ComponentProps<typeof Button>`. It seems like it accepts any prop, though. There's no way to restrict it to only props that Button and button accept?

**Comment by FlaTutu** [comment]
+1

I love the `Card` component and I use it in many ways. I often build components wrapped in a Card, and I should love to extend this components props to the `Card` component props so I juste have to pass the props.

It should be great if each component export his props interface (or type) which can be passed directly to the component. Actually `ButtonProps` and `CardProps` don't do the trick.

With this issue, we can imagine :
```typescript
import React, { FunctionComponent } from 'react';
import Button, { ButtonPropsInterface } from 'react-bootstrap/Button'; // ButtonProps actually already exists, maybe a new name to avoid BC ?

export interface MyButtonProps extends ButtonPropsInterface {
    myCustomProps: string;
}

const MyButton: FunctionComponent<MyButtonProps> = ({ children, className, myCustomProps, ...props }) => {
    // Do stuff with "myCustomProps"
    return (
        <Button {...props} className={`custom-class-name ${className}`}>
            {children}
        </Button>
    );
};

export default MyButton;
```

**Comment by kyletsang** [comment]
Component prop types are improved in the new 1.1.1 release.  Something like below should work:

```
import Button, { ButtonProps } from 'react-bootstrap/Button';

interface MyButtonProps extends ButtonProps {
  test?: string;
}

const MyButton: React.FC<MyButtonProps> = ({ test, ...props }) => {
  return (
    <Button {...props}>{test}</Button>
  );
};

<MyButton test="test" style={{ backgroundColor: 'red' }} />
```

**Comment by dietergeerts** [comment]
> Thanks. I got `React.ComponentProps<typeof Button>`. It seems like it accepts any prop, though. There's no way to restrict it to only props that Button and button accept?

Although this works to show the "custom" react-bootstrap properties for that component with intelli-sense, it does not show all the other properties that can be used for the element defined in `as` , or its default, which would be very useful for a better developer experience.

![image](https://user-images.githubusercontent.com/7393706/120206392-70654780-c22b-11eb-8c5b-ccc7bba0f248.png)

Even the types aren't completely correct. The following does a better job on the types though:

![image](https://user-images.githubusercontent.com/7393706/120206315-5a578700-c22b-11eb-84b6-a76ac5f9bd7c.png)

I'm trying to figure out how to show all the other props from the base element, so I can pass them through from my custom component, so that I can have intelli-sense show me what's possible. If the `as` prop was set, it should use that to "calculate" the props possible. But it's hard, and I would like to see this corrected in the typings instead, because it's something that's expected, that we can just use `React.ComponentProps` and that all props and their types are correctly calculated.

**Comment by dietergeerts** [comment]
The problem is with the following:
```
export declare type ReplaceProps<Inner extends React.ElementType, P> = Omit<React.ComponentPropsWithRef<Inner>, P> & P;
```
And e.g. 'div' is used for the type of card by default, but `'div` itself isn't a `React.ElementType`, and thus it's not working, but due to how the typings are done, you don't see the error. Try to disassemble the typings and you'll see the error.
