### ISSUE TITLE
Forms - Multiselect with validation example

### ISSUE THREAD

**Issue by kieranbop** [react-bootstrap/react-bootstrap#5031]
## Is your feature request related to a problem? Please describe

By following the examples and documentation for forms. I cannot get the multi select to work with the formik and yup example.

Tried to trim it down to some basic implementation just get the values I have selected but I cannot access the values to pass it along to anything. Be it state or formik.

## Describe the solution you'd like

An example on the docs showing the multi select work with validation.

## Describe alternatives you've considered

Looking at other libraries for that feature, but I feel I'm missing something silly.

**Comment by jquense** [comment]
we can't really provide support for using Formik here. The example in the docs is not meant as a full integration guide just an illustration of how to you the programatic isValid props.

Otherwise the bootstrap form components are just native html elements with CSS classes, any approach for making this work with the normal `<select multiple>` will Just Work for the bootstrap components

**Comment by kieranbop** [comment]
@jquense Even if we take an example without yup. I cannot even get the values I click on in any sort of object or to print out. It will look like it is visually selecting them but I cannot then doing anything with those values? How would you console.log after selecting a few for example?

**Comment by jquense** [comment]
Your question is how to use ` <select multiple>` with Formik, i'd google for that. Or for more basic form instructions with React, check out their documentation https://reactjs.org/docs/forms.html there is nothing different about the bootstrap components, they are JUST presentational wrappers around the native input components so behave in the exact same way
