### ISSUE TITLE
Updating states in Modal documentation

### ISSUE THREAD

**Issue by Stadl0r** [react-bootstrap/react-bootstrap#5131]
## Describe the bug

Link: https://react-bootstrap.github.io/components/modal/

Currently in the modal documentation you suggest using this state

`const [show, setShow] = useState(false);`

However it kicks compile error and is resolved by targeting the React component as such:

`const [show, setShow] = React.useState(false);`

**Comment by mxschmitt** [comment]
We just recommend the way of using [React Hooks](https://reactjs.org/docs/hooks-reference.html) as storing the state. You can also use class based components components with the normal traditional way of storing the state in it.

(You cant use Hooks inside class based components, I think thats the reason why an error will be thrown.)

**Comment by jquense** [comment]
yeah, examples will generally demonstrate patterns using hooks, because they tend to be less verbose and clearer to understand than the class equivalent *in the context of a short example*. Hooks aren't the only way to do things tho and you can use class components and `this.setState` to accomplish the same thing, but that is left as an exercise for the viewer
