### ISSUE TITLE
Click on NavbarToggler will reset the state of other components

### ISSUE THREAD

**Issue by jpacora** [react-bootstrap/react-bootstrap#5246]
## Describe the bug

I have a compontonent with the navbar and a div with a Switch of my routes to show my content. When I click the NavbarToggler to open the Collapse, all my components inside my Switch gets their state reset or re-mounted.
## To Reproduce

1. Fill form or change the state from some component inside the Switch
2. Click on 'NavbarToggler icon'
3. The forms gets empty

## Expected behavior

Keep the components mounted with their respective states

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version: Chrome 83.0.4103.106 (Official Build) (64-bit)
- React-Bootstrap Version [e.g. 1.0.0-beta.8]

## CodeSandbox example

https://codesandbox.io/s/interesting-cdn-zk2qu

**Comment by kyletsang** [comment]
Can you post a repro on CodeSandbox?

**Comment by jpacora** [comment]
> Can you post a repro on CodeSandbox?

https://codesandbox.io/s/interesting-cdn-zk2qu

PD: also main comment updated!

**Comment by kyletsang** [comment]
Your router component is being unmounted due to your state change in App.js.  What you want to do is move your NavBar and its toggle function into its own component so whenever you modify the toggle state, it won't affect the entire react component tree.  

You're also in the wrong github project btw.  This is the "react-bootstrap" project and you're using "reactstrap".
