### ISSUE TITLE
Building react-bootstrap: Why only client.js can import CSS?

### ISSUE THREAD

**Issue by andrerpena** [react-bootstrap/react-bootstrap#525]
Hi.

I'm sorry for so many questions. I want to understand react-bootstrap to the core and possibly become an active contributor.

I've noticed something intriguing. [Client.js](https://github.com/react-bootstrap/react-bootstrap/blob/master/docs/client.js) can load CSS files normally. That's because, while building docs, the `ExtractTextPlugin` is loaded and `tests` for CSS and LESS are added so it can handle styles correctly. I understand that. That's fine.

What's intriguing is that it seems that only the `client.js` file can handle CSS. lol. That's very strange. 

Example:

`Client.js` imports the `Routes.js` file. However, If from the `Routes.js` file I try to import **the same CSS** imported from `Client.js`. I get this error:

![image](http://i.imgur.com/hY8sXDs.png)

So, building `Routes.js` uses the same `webpack/strategies/docs.js` file than `Client.js`, so how the hell can't it load CSS?

Any help will be appreciated.
Thanks.

**EDIT**

This is the line I added to `Routes.js`:

    import from '../assets/style.css';

That's the same CSS that `Client.js` loads normally.

**Comment by mtscout6** [comment]
Excellent question, glad you asked!

We are using [webpack](http://webpack.github.io/) to build the documentation assets. We are also using an [express](http://expressjs.com/) server at development time so we can leverage server side rendering of react components. This allows us to debug problems with components being able to render on the server as well as the client to help maintain the capability for an isomorphic web application.

With that said NodeJs does not know what to do with a `*.css` or `*.less` file. Webpack does know what to do with these though which allows for an optimal set of scripts to deliver to a client. We are not yet using webpack on the server, although that would be a goal at some point in the future. Which means Node will fail anytime a file that it doesn't know what to do with is loaded. The client.js file is not being loaded by the development NodeJs server. The Routes.js file is used by both a browser and by the NodeJs express js server. So, that script needs to play well with both webpack and NodeJs.

The `docs/src/CodeMirror.js` and `CodeMirror.client.js` is another odd ball script pair. I have a custom webpack loader that will use CodeMirror.client.js when building the assets for the browser, but Node will load CodeMirror.js. This one was interesting because CodeMirror.client.js needs access to the DOM to work. Well, there's no DOM in NodeJs so that is another curve ball to be aware of.

I hope that answers your questions, if not don't hesitate to follow up with more questions :wink:

**Comment by andrerpena** [comment]
I really appreciate your willingness to help.

So this is what I understand: Even though Webpack knows how to handle CSS and LESS because of the `ExtractTextPlugin` extension, the server side React renderer, which I assume to be `React.renderToString`, doesn't.

Is that it?

So, if I wanted to make the above example to work, I think I'd have to tweak the `server.js` to configure the Webpack middleware to understand CSS and LESS... 
 
      let webpackConfig = webpackConfigBuilder({
        development: development,
        docs: true
     });

Is that correct?

**Comment by mtscout6** [comment]
It's not because React doesn't know what to do with it. It's because NodeJs
doesn't know what to do with it.

**Comment by andrerpena** [comment]
Yeah, that's what I meant. :)

That's interesting. If I'm creating a component library that is supposed to be exported as AMD, then there's no problem at all on "requiring" CSS because webpack can handle it. But, in the other hand, if I intend to export that as CommonJS, then I can't require CSS because Node.js doesn't know how to handle that.

I'm just getting acquainted to this whole JavaScript ecosystem thing now. It's HARD! haha..

Thank you very much for your attention.

**Comment by mtscout6** [comment]
No problem glad the guidance helped.
