### ISSUE TITLE
Add individual CarouselItem intervals

### ISSUE THREAD

**Issue by kyletsang** [react-bootstrap/react-bootstrap#5305]
https://getbootstrap.com/docs/4.5/components/carousel/#individual-carousel-item-interval

**Comment by jquense** [comment]
oof that is not straight forward :/

**Comment by bpas247** [comment]
So if I'm understanding the feature correctly, the API would look something like
```jsx
<Carousel>
  <Carousel.Item interval={10000}>
    <img
      className="d-block w-100"
      src="holder.js/800x400?text=First slide&bg=373940"
      alt="First slide"
    />
    <Carousel.Caption>
      <h3>First slide label</h3>
      <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
    </Carousel.Caption>
  </Carousel.Item>
  <Carousel.Item interval={2000}>
    <img
      className="d-block w-100"
      src="holder.js/800x400?text=Second slide&bg=282c34"
      alt="Second slide"
    />
    <Carousel.Caption>
      <h3>Second slide label</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    </Carousel.Caption>
  </Carousel.Item>
</Carousel>
```
A couple questions regarding this:
- Since the `Carousel` component handles all of the state, should we go about communicating the children's `interval` prop values to the `Carousel` component? 
What we could do is store an object in a ref, and mutate it when we map over all of the children with the values of `child.props.interval`, which we could then use as a lookup table for setting the proper interval time, although I'm not sure if there's a better way of approaching that.
- In the event that `Carousel` is also passed an `interval` prop, what would take precedence? 
I would imagine the `Carousel`'s interval value would, but just wanted to confirm.

**Comment by kyletsang** [comment]
In the bootstrap example, it looks like the children intervals take precedence, and in the absence of a child interval, the `Carousel` interval would be used.

**Comment by taion** [comment]
Child interval values might not be too bad... we need to iterate through the children to count them anyway, so why not also grab their intervals when we do so?

**Comment by bpas247** [comment]
> we need to iterate through the children to count them anyway, so why not also grab their intervals when we do so?

Yep, that's the current plan I'm going with 👍 just need to get it working lol
