### ISSUE TITLE
Changelog generation from GitHub issues instead of commits

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#534]
There has been a lot of confusion around generating the changelog from commit messages based on a regex pattern. That was my initial stab at generating a changelog which @mathieumg had requested when we produce releases in the gitter room on [February 11 2015 9:26 AM](https://gitter.im/react-bootstrap/react-bootstrap?at=54db82b2620fc547551ea99c). I added documentation for such in the Contributing Guide, yet it is commonly not applied in PRs or completely mis-understood. I recently attended the [.Net Fringe](http://dotnetfringe.org/) conference in Portlan, Oregon USA this week and [Jimmy Bogard's](https://github.com/jbogard) keynote address identified the need for a changelog in OSS projects. He mentioned that he was generating his changelog based on GitHub Issues and PRs. I personally like this idea better since we'd be in more control of this regardless of what a contributor may do in their pull request. The question I pose is whether this would make more sense to people going forward? 

There is a good website up at http://keepachangelog.com/ which is great at explaining the general need and guidelines for a changelog.

There are a few tools out there that do this (For various platforms):

- https://github.com/Particular/GitHubReleaseNotes (C#)
- https://github.com/skywinder/Github-Changelog-Generator (Ruby)
- ~~https://github.com/piwik/github-changelog-generator (NodeJS?)~~ Html based...
- https://www.npmjs.com/package/github-changes (NodeJS)
- ~~https://www.npmjs.com/package/gh-changelog (NodeJS)~~ Incomplete and poor documentation
- https://www.npmjs.com/package/github-changelog (NodeJS)

An additional item that would be nice is to include these changelog or release notes through the GitHub release API: https://github.com/blog/1547-release-your-software

The question is whether one of those tools or another tool I don't know about do what we want and allow a clean integration with our existing release process. Our current release process is attained by running the `./tools/release` script within this repo.

/cc @AlexKVal

**Comment by AlexKVal** [comment]
Actually I think it is not so bad that I am the main reason of this proposition :)

Sarcasm aside, I believe that the idea to use GitHub Issues and PRs 
for `change log` entries is the right one.

The alternatives are:
a) parse commits headers
b) write them by hands every time

`a` already is in use and as practice shows ... in result we have this proposition.

For starters I would like to try to explain the way of my thoughts 
from a newbie point of view to this whole `changelog` thing.
(I believe that everyone else who is new to github and open source projects out there 
do and think just about the same way)

I have read [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/v0.20.3/CONTRIBUTING.md)
all from start to end. 
In general I am diligent person and because of that 
I had read it _before_ I did my first commit to this project.

And nevetheless I did fail to write the right commit headers and PR's.
And failed several times. ( I hope those were last though :) )
Why ?
It's simple.
Such is the nature of human's mind. 
We have a blind spot on things that we don't know or did not try yet.
By reason of that we did not try / touch something, our brain has no questions about it.
And as a consequence it does not look for answers.
We read.. but we don't see. The blind spot.

One begins to look for answers only after them have been tried / touched and failed.

Everybody does like that. That's the way of learning.

That is the reason why people fail to write the right commit headers and PRs.
Not because they are lazy or ignorant. ( We must to think positively :) )


Ok. Back to topic.
This idea aims to ease the burden of maintaining.
Sure enough it does not solve the whole problem,
because of human factor,
but nevetheless it will alleviate the process.

As Matthew has mentioned `we'd be in more control of this`.
It is obvious that I am :+1: about it.

**Comment by taion** [comment]
Per https://github.com/rackt/react-router/issues/2399, I'd actually rather we move to updating the changelog manually. What do y'all think?

**Comment by mathieumg** [comment]
Haven't read that issue yet, but I've always been a fan of manual changelog updating, so :+1:

**Comment by mtscout6** [comment]
I'd be fine with that as well!

**Comment by taion** [comment]
Closing this for now; I don't think we want to go ahead with this, and at some point I'd rather generate changelogs manually anyway.
