### ISSUE TITLE
DropdownButton/Tooltip.id should be optional (and other id's)

### ISSUE THREAD

**Issue by mortoray** [react-bootstrap/react-bootstrap#5391]
In a component based application there is no possibility to provide globally unique id's to components. An individual control is unable to come up with a unique name, as the same control may be used elsewhere in the application.

If the id is absolutely necessary for the control, then it should generate a unique string on its own.  Though for the most part the controls work without an id being specified -- but TypeScript reports errors if you attempt to use the control without.

**Comment by jquense** [comment]
IDs are required for accessibility, and while it can be a pain to generate meaningfully unique ones in an application it's definately possible (we and others do it). We recommend that you try not to encapsulate the ID prop so consumers in the app can provide them in a place with larger context. For instance, when your app has data items with IDs.

We would love the option to generate IDs automatically, but that isn't possible right now because it would cause mismatches for server side rendering in react, breaking appa. React has been working on an API to allow this but it's not stable (or released) yet.

**Comment by ranneyd** [comment]
@jquense I think it's inappropriate to force accessibility compliance on developers. A required property should only be for things that, when absent, would break the component. I think requiring it is a little self-righteous, honestly. If I'm working on an internal tool for 6 people who don't use screen readers, I'm not going to spend time making sure my site is accessible. And if I want make an inaccessible public site, I may face consequences or it may be immoral, but that's my prerogative; since when is react-bootstrap a moral arbiter?

**Comment by jquense** [comment]
Guy, we aren't going to provide a shittier UI library because you think "making the components work for the most people" is inconvenient to your specific use case. You could have put IDs on your tooltips in the time it took you to write a this. Instead you decided to complain at people whose work you benefit from for free. The only self-righteous one here is you. Take your pearl clutching elsewhere.
