### ISSUE TITLE
Pagination.Item usage with Gatsby Link component?

### ISSUE THREAD

**Issue by arafatamim** [react-bootstrap/react-bootstrap#5395]
## Is your feature request related to a problem? Please describe

Currently the Pagination.Item component is wrapped by an 'a' tag which is incompatible with Gatsby's Link component.
Is there a solution?

**Comment by nbkhope** [comment]
The previous reply is incorrect as the behavior from `as` would pass through `as` attribute to the HTML element, resulting in undesired behavior:

```
import NextLink from 'next/link';
...
<Pagination.Item as={NextLink} href="?page=123">
  123
</Pagination.Item>
```

```
<a class="page-link" as="[object Object]" href="?page=123">123</a>
```

An `<a>` tag is rendered instead of whatever comes from `<NextLink>`. The attribute `as` is added, with value being the string representation of NextLink.

It would be nice if `as` prop given to Pagination.Item behaved like `<Button linkAs={NextLink} />`
