### ISSUE TITLE
Vertical and horizontal scroll implementation?

### ISSUE THREAD

**Issue by JCODEPENG** [react-bootstrap/react-bootstrap#5470]
Hi there, I just wanted to ask a question about how to create a responsive table using React bootstrap <Table>
I was able to make it horizontally scrollable by using <Table responsive> but is there a way to make it both vertically and horizontally scrollable?

**Comment by kyletsang** [comment]
You would need to set a height and overflow for in the wrapping element of the table.

Unfortunately this won't be possible if you are using the `Table` component with the `responsive` prop because the code currently doesn't pass any other modifiers to the wrapping element.  You need to manually create the wrapping element and use `Table` without the `responsive` prop.  See below snippet for an example:

```
<div className="table-responsive" style={{ height: '200px', overflowY: 'auto' }}>
  <Table>
    ...
  </Table>
</div>
```

**Comment by JCODEPENG** [comment]
Sorry I forgot to mention but is there a way to have a fixed header, because with that method, the header also scrolls away. Is there a way for the <thead to be fixed but the <tbody to be scrollable?

**Comment by kyletsang** [comment]
There's nothing built-in for bootstrap.  I don't know of the specific css off the top of my head.

You'll have to check sites like stack overflow - they may have an answer there.

**Comment by JCODEPENG** [comment]
Oh okay I see, but anyways thanks for the help!
