### ISSUE TITLE
ProgressBar props warning

### ISSUE THREAD

**Issue by eugenmihailescu** [react-bootstrap/react-bootstrap#5634]
I have a ProgressBar with children which are also ProgressBar (emulates [multiple-bars](https://getbootstrap.com/docs/4.6/components/progress/#multiple-bars)). I get the following React props warning:

> Warning: React does not recognize the `isChild` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ischild` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

The problems seems to be in [ProgressBar.js](https://github.com/react-bootstrap/react-bootstrap/blob/v1.4.3/src/ProgressBar.tsx#L208). I was able to silence that by changing the code from `cloneElement(child, { isChild: true })` to `cloneElement(child)`.

However, I'm not sure if that's the right solution to fix it, it is merely an attempt to silence only that warning.

**Comment by kyletsang** [comment]
Can you post a repro?  

Does your code look like the example [here](https://react-bootstrap.github.io/components/progress/#progress-stacked)?

**Comment by kyletsang** [comment]
Closed due to inactivity

**Comment by kyletsang** [comment]
@zz-james I tried your example and still can't reproduce.  The only way I could see this happening is if a non-ProgressBar component was placed underneath ProgressBar.

Could you put together a minimal repro on codesandbox?

**Comment by zz-james** [comment]
Hi 
You are right, in the code causing the error I do have a non-progress bar underneath - good catch.
James

**Comment by sgedye** [comment]
FYI - I also had this issue (warning in the console), and like kylesang said it was caused by a non-ProgressBar component being nested in the ProgressBar. Basically I wanted to have the numbers rendered to the side if it was less than 20% full (as small value labels were being cut off).

I ended up resolving this issue by wrapping the child Progress Bar, and the conditionally rendered (i.e. if less than 20%) child span in a react fragment (although I had to give the child progress bar a 100% width and absolutely position the span.

![image](https://github.com/react-bootstrap/react-bootstrap/assets/14964449/28eb4075-9e0b-454f-be4a-7c4c94cb5403)
