### ISSUE TITLE
react-bootstrap will not work with Snowpack bundler

### ISSUE THREAD

**Issue by Intelliflex** [react-bootstrap/react-bootstrap#5834]
## Describe the bug

Trying to use Snowpack bundler with React and react-bootstrap. 
If you attempt to use navbar with dropdowns (or also modals) your will get an error (This is tested against fresh snowpack build using 

`npx create-snowpack-app my-project --template @snowpack/app-template-react`

If you attempt to add a Navbar, eg : from docs
```

<Navbar bg="light" expand="lg">
  <Navbar.Brand href="#home">React-Bootstrap</Navbar.Brand>
  <Navbar.Toggle aria-controls="basic-navbar-nav" />
  <Navbar.Collapse id="basic-navbar-nav">
    <Nav className="mr-auto">
      <Nav.Link href="#home">Home</Nav.Link>
      <Nav.Link href="#link">Link</Nav.Link>
      <NavDropdown title="Dropdown" id="basic-nav-dropdown">
        <NavDropdown.Item href="#action/3.1">Action</NavDropdown.Item>
        <NavDropdown.Item href="#action/3.2">Another action</NavDropdown.Item>
        <NavDropdown.Item href="#action/3.3">Something</NavDropdown.Item>
        <NavDropdown.Divider />
        <NavDropdown.Item href="#action/3.4">Separated link</NavDropdown.Item>
      </NavDropdown>
    </Nav>
    <Form inline>
      <FormControl type="text" placeholder="Search" className="mr-sm-2" />
      <Button variant="outline-success">Search</Button>
    </Form>
  </Navbar.Collapse>
</Navbar>
```
The following error is produced

```
Unhandled Runtime Error
Uncaught TypeError: (0 , _camelize.default) is not a function

Source
http://localhost:8080/_snowpack/pkg/react-bootstrap.v1.6.0/common/Dropdown-70f399dd.js [:903:55]
TypeError: (0 , _camelize.default) is not a function
    at pascalCase (http://localhost:8080/_snowpack/pkg/react-bootstrap.v1.6.0/common/Dropdown-70f399dd.js:903:55)
    at createWithBsPrefix (http://localhost:8080/_snowpack/pkg/react-bootstrap.v1.6.0/common/Dropdown-70f399dd.js:910:51)
    at http://localhost:8080/_snowpack/pkg/react-bootstrap.v1.6.0/common/Dropdown-70f399dd.js:976:54
    at createCommonjsModule (http://localhost:8080/_snowpack/pkg/react-bootstrap.v1.6.0/common/Dropdown-70f399dd.js:26:5)
    at http://localhost:8080/_snowpack/pkg/react-bootstrap.v1.6.0/common/Dropdown-70f399dd.js:939:18

```

error 

## Environment (please complete the following information)

- Operating System: Windows
- Browser, Version Chrome Version 90.0.4430.212 (Official Build) (64-bit)
- React-Bootstrap Version: 17.0.2

**Comment by kyletsang** [comment]
Not really familiar with snowpack, but it looks like it didn't include dom-helpers lib which RB depends on.  This issue might be worth filing over at the snowpack git repo.

**Comment by JaredReisinger** [comment]
I've just been investigating this myself, and it appears that there's a bug somewhere between snowpack and react-bootstrap (or its dependencies).  The dom-helpers functions are embedded in the script sent to the browser for react-overlay/Dropdown, but the `interopRequireDefault()` helper ends up wrapping an extra object around the result.  Therefore, instead of `_camelize.default` being the expected function, it's probably at `_camelize.default.default`.

I've been dealing with a very similar-looking problem with NavDropdown, which results in the same symptoms at react-overlay/Dropdown's "matches.default".  The `interopRequireDefault()` function looks for the object passed to it to have an `__esModule` property, but the definition of matches (inlined from dom-helpers into react-overlay/Dropdown) is:

```js
// matches is defined as a function...

var matches$1 = /*#__PURE__*/Object.freeze({
  __proto__: null,
  'default': matches
});

// ... and then in the Dropdown code...
var _matches = interopRequireDefault(matches$1);

// ... and the call...
(0, _matches["default"])(menuRef.current, '[role=menu]')
```

Notice that `matches$1` is _not_ defined with an `__esModule` property.  This means that the `matches$1` value is wrapped in _another_ object, and set as the `default` property, effectively being:

```js
var _matches = {
  default: {
    default: matches,
  }
};
```

so, rather than `_matches["default"] being the `matches()` function, it's actually the _object_ `{ default: matches }` (a.k.a. `matches$1`).

I'm not sure where along the lines the inlining of dom-helpers is happening, but it would appear that whatever is doing it is missing the `__esModule` property that the calling code is expecting.

**Comment by kyletsang** [comment]
Nice write-up @JaredReisinger. 

This sounds like this issue in Snowpack:
https://github.com/snowpackjs/snowpack/issues/2908

**Comment by Valerio-boi** [comment]
The problem you described still persists even though I have installed the latest version. How can we solve?

TypeError: (0 , _camelize.default) is not a function
    at pascalCase (http://localhost:3000/_snowpack/pkg/react-bootstrap.v1.6.4/common/createWithBsPrefix-814b06ea.js:39:55)
    at createWithBsPrefix (http://localhost:3000/_snowpack/pkg/react-bootstrap.v1.6.4/common/createWithBsPrefix-814b06ea.js:46:51)
    at http://localhost:3000/_snowpack/pkg/react-bootstrap.Navbar.v1.6.4.js:332:50
    at createCommonjsModule (http://localhost:3000/_snowpack/pkg/react-bootstrap.v1.6.4/common/ThemeProvider-4a89d938.js:14:5)
    at http://localhost:3000/_snowpack/pkg/react-bootstrap.Navbar.v1.6.4.js:295:16

**Comment by kyletsang** [comment]
Closing since snowpack is no longer maintained
