### ISSUE TITLE
Styling of input validation is broken

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#586]
![screen shot 2015-04-27 at 4 21 44 pm](https://cloud.githubusercontent.com/assets/736870/7359277/c01d7c74-ecf9-11e4-8885-fc28d1e8e269.png)

I don't know when this broke but we need to fix it.

**Comment by dozoisch** [comment]
That is so weird

**Comment by dozoisch** [comment]
https://gitter.im/react-bootstrap/react-bootstrap?at=554101dcc79c38843629d78b

https://github.com/twbs/bootstrap/commit/77c1a528ab48ba695f52f4f8f7b97bf7bbde05d1

**Comment by aabenoja** [comment]
@dozoisch Thanks for linking that. With that new styling the glyphicon will appear in the correct place when:
* You don't provide `Input` with a `label` property
* You don't provide `Input` with a `wrapperClassName` property

That being said, after discussing it with @mtscout6 that wrapper div should be stripped and the `wrapperClassName` provided to `FormGroup`, though that would break some backwards compatibility.

**Comment by mtscout6** [comment]
@liamcmitchell You were the original author of this wrapper what are your thoughts?

**Comment by liamcmitchell** [comment]
Sorry, I haven't looked at the code for a while and I'll be away from my
computer for the next few weeks so can't help.

**Comment by aabenoja** [comment]
Welp, I finally found the original intention of `wrapperClassName`: horizontal forms have column widths defined on the label and a wrapper around the input-group and other goodies. Because of this, I don't feel comfortable removing the property outright, but we may need to rethink how we handle case like this. `wrapperClassName` was not very descriptive of the intention and has taken me a week to solve.

**Comment by aabenoja** [comment]
Either way, we should probably remove the use of `wrapperClassName` from our example in the docs...
