### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by Beyazatli** [react-bootstrap/react-bootstrap#5899]
## Describe the bug

Error caused by using Overlay and OverlayTrigger. I searched for other problems to solve the error, but I could not find a result for me, it may be because of the beta version.

## To Reproduce

Using Overlay and OverlayTrigger only

## Screenshots
Code:
![image](https://user-images.githubusercontent.com/39380337/124064690-f5679a80-da3d-11eb-94d2-25e38fb1553e.png)
Error:
![image](https://user-images.githubusercontent.com/39380337/124064728-07493d80-da3e-11eb-842c-5d2746342e54.png)

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version 91.0.4472.114 Chrome
- React-Bootstrap Version "^1.6.1"

## Additional context

Also it has nothing to do with the problem, but the "xxl" parameter in the Col component does not work.

**Comment by kyletsang** [comment]
For v1 and bootstrap 4, this is an option to remove the warning in overlay: https://react-bootstrap.github.io/components/overlays/#customizing-trigger-behavior

Other components like the transitions will still show a warning in strict mode though.  This is fixed in v2 beta for bootstrap 5 if you're interested in using that.  Also xxl is only part of bootstrap 5 and does not exist in bootstrap 4.

**Comment by Beyazatli** [comment]
@kyletsang how can i install v2?

**Comment by kyletsang** [comment]
> 
> 
> @kyletsang how can i install v2?

`npm i react-bootstrap@next`
