### ISSUE TITLE
Closing Offcanvas when opening a Modal removes vertical scrollbar

### ISSUE THREAD

**Issue by catamphetamine** [react-bootstrap/react-bootstrap#5905]
https://codesandbox.io/s/xenodochial-andras-08551

* Open the demo. See the vertical scrollbar.
* Open the menu, then click "Open Modal", then close the modal.
* See that the vertical scrollbar has disappeared.

**Comment by bay-jacewhitten** [comment]
I have this same issue, its due to the check for the body class in the overlay system, it sees its and doesn't know to remove the class since the modal function didn't apply it. It came from the offcanvas component. I been meaning to report this on my personal account. Basically, the overlay remove function needs to be remove all class instances and return the body back to having an overflow auto or whatever is best there. (IE: overflow-y , etc)

**Comment by illiteratewriter** [comment]
You can add `scroll={true}` to `OffCanvas` component which will make the content scrollable even when `OffCanvas` is shown. This will prevent the above bug. I think the bug occurs because when the OffCanvas closes, the scroll toggle is not getting triggered.

**Comment by kyletsang** [comment]
The ssue is caused because the `ModalManager` from `Modal` is saving the wrong container styles prior to opening the modal.  The offcanvas hasn't fully closed yet, so the modal is saving a container style that doesn't contain the overflow style.

Here's the timeline:
1. Open offcanvas
2. Offcanvas manager saves the container style including the overflow
3. Open modal
4. Modal manager saves the current container state which has no overflow
5. Offcanvas closes
6. Offcanvas manager applies the overflow style back (you can see a scrollbar while the modal is open)
7. Close modal
8. Modal manager applies the saved container style which has no overflow
