### ISSUE TITLE
Popover not working

### ISSUE THREAD

**Issue by gauravgupta98** [react-bootstrap/react-bootstrap#5954]
## Popover is crashing

Popover has some issue with the rendering. After clicking the button it is throwing error.
Please go through the code sandbox for the issue - https://codesandbox.io/s/angry-meninsky-4k4f8?file=/src/App.js

## Reproducible Example

[CodeSandbox](https://codesandbox.io/s/angry-meninsky-4k4f8?file=/src/App.js).

## Expected behaviour.

Popover should be displayed without any error.

**Comment by gauravgupta98** [comment]
I was able to fix this one. Actually `<Popover.Header>` and `<Popover.Body>` should be changed to `<Popover.Title>` and `<Popover.Content>` and this will fix the issue.

Kindly raise a documentation bug to fix the [documentation](https://react-bootstrap.netlify.app/components/overlays/#popovers)

<img width="909" alt="Screenshot 2021-07-29 at 4 56 03 PM" src="https://user-images.githubusercontent.com/31717079/127484173-838a4dbc-cb43-43bb-80c5-c75b8705db1f.png">

**Comment by kyletsang** [comment]
React-bootstrap supports many versions of Bootstrap and there are breaking changes between each version.  You need to make sure you're reading the correct version of the docs for the version of react-bootstrap you are installing.  You can choose the correct version from the dropdown in the right side of the navbar.

**Comment by malipetek** [comment]
Hi, I am trying same example and what you point out is not relevant. You see this example appears in Bootstrap 5.x docs. 
![image](https://user-images.githubusercontent.com/13527277/130436841-dbc17acc-cf99-4f2d-93c8-101647a9d608.png)

My bootstrap version is 5.1 
![image](https://user-images.githubusercontent.com/13527277/130436907-e861d037-000d-46b0-8ec2-7ab040b363f1.png)

and react bootstrap version is 1.6.1
![image](https://user-images.githubusercontent.com/13527277/130437016-7edcfca4-6974-4292-b4d4-412e88dcc123.png)

However I m getting this error, and it doesn't make sense because it gives same error even if its a function component or a jsx expression like in the example.

Could you give a bit more detail about how this issue is related to versions?
