### ISSUE TITLE
[Docs] Is the library still not tree-shakable?

### ISSUE THREAD

**Issue by igorsantos07** [react-bootstrap/react-bootstrap#5990]
## Describe the bug

By oversight, we used `import { X, Y, Z } from 'react-bootstrap'` in a new file. This was caught during the PR, but _surprisingly_ fixing that (back into individual imports) didn't change the build size. I thought we had that somewhere else but found no other place.... Then I decided to include on that line a component we're not using (`Breadcrumb`) and voilà, 409b included in the final build!

Thus I'm wondering if the suggestion for individual imports in the docs is still valid?
Or could this be, somehow, because we started using [Craco](https://www.npmjs.com/package/@craco/craco) (successor of CRA-rewired) a couple of months ago? We're only using it to include some Babel proposals, though, so I don't see where it could have "enabled" tree-shaking...

## Environment 

- Operating System: Linux Mint 20.1
- React-Bootstrap Version: 1.4.0 _(yep, a bit afraid of updating with the current rush of tasks)_
- Create-React-App (react-scripts) Version: 4.0.0
- Craco Version: 6.1.2

**Comment by jquense** [comment]
The suggestion is still valid. However, it's not being made because RB doesn't support tree shaking. RB should be tree shakeable. The issue is that tree shaking as an optimization is unreliable, and less effective than cherry picking imports. We don't think it's good to encourage users to depend on it, but consider it nice additional optimization for production fields if it happens.

**Comment by igorsantos07** [comment]
Hmmmm got it.
Our files got pretty ugly (tons of imports from the same library), and
we're really considering depending on tree shaking to get back some sanity.

Do you think these considerations you said could be somehow summarized and
included in the docs, as a "full disclosure" of the suggestion?
