### ISSUE TITLE
Why can't I change pagination items's label?

### ISSUE THREAD

**Issue by dgncksgl** [react-bootstrap/react-bootstrap#6041]
I want to change pagination items's label. But I don't know that how can I do it.

**Comment by kyletsang** [comment]
`<Pagination.Item>label goes here</Pagination.Item>`?

**Comment by dgncksgl** [comment]
> `<Pagination.Item>label goes here</Pagination.Item>`?

Sorry. I didn't give any detail to you. 
When I implement the label like this _<Pagination.First>test</Pagination.First>_ , it displays _testFirst_.
I am attaching screenshot.

![50](https://user-images.githubusercontent.com/50733406/134411574-057ad8cc-c248-43a8-9902-259d36a1aa2e.png)

**Comment by kyletsang** [comment]
For `Pagination.First`, `Pagination.Last` etc, those are convenience components that have the labels and everything all preset.  You don't have to use them.  They all use `PageItem` under the hood:

https://github.com/react-bootstrap/react-bootstrap/blob/86e5503d74eeac0944b32e79c3b73a9e1a98b29a/src/PageItem.tsx#L76-L89

In your case, since you're looking for custom labels, you should be using `PageItem` directly.

**Comment by dgncksgl** [comment]
> For `Pagination.First`, `Pagination.Last` etc, those are convenience components that have the labels and everything all preset. You don't have to use them. They all use `PageItem` under the hood:
> 
> https://github.com/react-bootstrap/react-bootstrap/blob/86e5503d74eeac0944b32e79c3b73a9e1a98b29a/src/PageItem.tsx#L76-L89
> 
> In your case, since you're looking for custom labels, you should be using `PageItem` directly.

Ok. I got it. Thank you.
