### ISSUE TITLE
NavDropdown onSelect prop typescript error

### ISSUE THREAD

**Issue by quinn-freshly** [react-bootstrap/react-bootstrap#6148]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

NavDropdown seems to be resolving to the wrong ts prop definition for onSelect, it seems to be using the prop from react rather than from Dropdown. 

### Expected behavior

onSelect should expect a function with an arg of `string | null`, not a react event. 

### To Reproduce

https://codesandbox.io/s/friendly-cherry-m2k0r?file=/src/App.tsx

### Reproducible Example

https://codesandbox.io/s/friendly-cherry-m2k0r?file=/src/App.tsx

### Screenshots

![image](https://user-images.githubusercontent.com/60898462/145657089-b86ca0d2-4b7c-453f-84a8-2d0ef7b73f77.png)

### What version of React-Bootstrap are you using?

2.0.3

### What version of Bootstrap are you using?

5.1.3

**Comment by quinn-freshly** [comment]
I moved the `onSelect` handler from NavDropdown to the Nav, and it works ?? 🤷‍♂️

**Comment by kyletsang** [comment]
Both should work.  Nav has one so you can handle all the different nav items with a single callback.  I'm going to reopen this because we do need to fix the types for NavDropdown.

We need to remove `onSelect` in the `Omit`

https://github.com/react-bootstrap/react-bootstrap/blob/d2cc2522dd147a4a550283d6843c8e2afe06c6fc/src/NavDropdown.tsx#L12

Interested in sending a PR?
