### ISSUE TITLE
ModalTrigger with a MenuItem triggers a route change

### ISSUE THREAD

**Issue by psbanka** [react-bootstrap/react-bootstrap#616]
I have a very weird bug with regards to an interaction between `react-bootstrap` and `react-router`. When I implement a `DropdownButton` with a `MenuItem` that kicks off a modal, as follows:

```javascript
    <DropdownButton title='More' dropup disabled={disabled}>
        <ModalTrigger modal={confirmModal}>
            <MenuItem eventKey='2'>Bulk Tear-down</MenuItem>
        </ModalTrigger>
    </DropdownButton>
```

I'm getting a route-change event and reverting to the base route. However, if I use a `Button` instead of the `MenuItem`, as in the following code I do not:

```javascript
<DropdownButton title='LESS' dropup disabled={disabled}>
    <ModalTrigger modal={confirmModal}>
        <Button bsStyle='link' id='weird-button' disabled={disabled}>
            TEAR DOWN
        </Button>
    </ModalTrigger>
</DropdownButton>
```

Any ideas? Thanks!

**Comment by mtscout6** [comment]
That would be because the onClick handler for MenuItem fires before the ModalTrigger has a chance to. The offending code would be this: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/MenuItem.js#L23 Which is why #419 exists. Also, Dropdowns inherently have problems right now which is why we have #526.
