### ISSUE TITLE
Dropdown does not respect boundary in strict mode (react 18)

### ISSUE THREAD

**Issue by jannec22** [react-bootstrap/react-bootstrap#6284]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

When rendering Dropdown inside React.StrictMode, Dropdown.Menu does not respect horizontal boundary, and causes horizontal overflow.

### Expected behavior

Dropdown should work properly inside Strict Mode

### To Reproduce

start a fresh create-react-app project, install react18-rc.1, bootstrap 5, and react-bootstrap 2.X
render Dropdown inside StrictMode close to the edge of the screen.

### Reproducible Example

see [sandbox](https://codesandbox.io/s/goofy-nash-32yhc5?file=/src/index.js)

### Screenshots

with strict mode:
![image](https://user-images.githubusercontent.com/33345694/159958217-09ee8131-5441-4edd-a170-84afa23d318f.png)

without strict mode:
![image](https://user-images.githubusercontent.com/33345694/159958325-d0271115-0132-44ff-9864-cf4d9ae08b55.png)

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.2.0

### What version of Bootstrap are you using?

5.1.3

**Comment by golota60** [comment]
I've done a brief investigation using react ver `18.0.0-rc3`, and found a few things.

On the surface, the problem is that the component rendered in `StrictMode` is not receiving `style` props.
From a code perspective, it looks like upstream's [useDropdownMenu](https://github.com/react-restart/ui/blob/f7916f45c72e64c27247ad4354d3cb6468574233/src/DropdownMenu.tsx#L104) is not returning the same values with and w/o StrictMode , even though the functions receive exactly the same input data. It **seems** like this is an effect of [React 18's strict mode changes](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode). My best bet it's because [upstream's usePopper function](https://github.com/react-restart/ui/blob/f7916f45c72e64c27247ad4354d3cb6468574233/src/usePopper.ts#L110) is not correctly handling the new [mount -> unmount -> mount pattern](https://github.com/reactwg/react-18/discussions/19). 

I'll try to fix it upstream over the next few days, posting this comment so that in case im unable to fix it someone can benefit from this little investigation

**Comment by golota60** [comment]
Update: the issue seems to be with upstream's `useSafeState` hook. At some point the `useMounted` hook thinks the component is unmounted, and doesn't update the state, this is probably related with React 18's changes to StrictMode.
