### ISSUE TITLE
Importing components - same bundle size

### ISSUE THREAD

**Issue by Djo1e** [react-bootstrap/react-bootstrap#6293]
Following the docs regarding [importing components](https://react-bootstrap.github.io/getting-started/introduction#importing-components) I've changed all imports in my project from `import * as rb from 'react-bootstrap'` to `import <component> from 'react-bootstrap/<component'`. I was expecting this would lead to a smaller bundle size, but after analysing via `source-map-explorer` the bundle size is pretty much the same (it even grew by unnoticeable amount). The project was created by `create-react-app`.
```
"react": "^17.0.2",
"react-bootstrap": "^2.2.2",
```

**Original**
<img width="1509" alt="Screenshot 2022-04-03 at 22 16 54" src="https://user-images.githubusercontent.com/34274884/161434863-6a2d9e27-6d90-4d99-8479-f4eca94e4eb5.png">
 
 **Updated**
<img width="1496" alt="Screenshot 2022-04-03 at 22 17 18" src="https://user-images.githubusercontent.com/34274884/161434876-d3186bc4-41fd-4c1b-a98e-19fe8cfbad65.png"> 

**Question:** Does it still make a difference to import components as suggested in the docs?

**Comment by jquense** [comment]
In this case your bundler is correctly tree shaking the `import *` case. which is effectively the same as cherry-picking the imports (it may be a bit more efficient even). The reason we recommend cherry picking, is because three shaking is finicky and prone to silently de-opting without realizing it. Small changes in code can cause the compiler to be unsure about whether a thing is safe to tree-shake and cause it to fall back to including everything.

**Comment by Djo1e** [comment]
@jquense That makes sense. Thank you for the detailed response! Closing this issue.
