### ISSUE TITLE
Every Component Should Implement shouldComponentUpdate

### ISSUE THREAD

**Issue by francoislaberge** [react-bootstrap/react-bootstrap#633]
Is there plans to implement ```shouldComponentUpdate``` for each component? I'm evaluating solutions for wrapping bootstrap in react and this project seems pretty strong. Best so far. Was surprised though that this hadn't been done for the components. Many components should have a pretty cheap ```shouldComponentUpdate``` implementation so worth doing. Nothing that groups components unfortunately as it's unknowable if grouped components need to be redrawn.

**Comment by mtscout6** [comment]
I was only really learning about the benefits to this this week. I agree that many of the components would benefit from this, I would like to stay away from the mixin approach as I'd like to move any many components as we can to be ES6 classes. I'm not sure yet if we want to take on another dependency like [react-pure-render](https://github.com/gaearon/react-pure-render). I've just been too busy on other things really to dig into exactly how to solve something like this. If you're up to evaluating each component for this then be our guest, we love pull requests.

**Comment by taion** [comment]
I think incorporating react-pure-render would be the right thing to do. It's structured so that you can pull in just the code you need, and I think it's better to do that than to re-implement the trivial bits of code that are there.

**Comment by taion** [comment]
It turns out that "react-purerender" actually does expose this via a decorator: https://github.com/brigand/react-purerender

**Comment by talkhot** [comment]
I'm relatively new to react, but would some (static) components like a grid not benefit from setting ```shouldComponentUpdate``` to ```false```?  it seems this talk shows some great insides: [React.js Conf 2015 - Making your app fast with high-performance components](https://www.youtube.com/watch?v=KYzlpRvWZ6c).

Two example's out of the talk:

```javascript
// example of pure-render-mixin
<OuterScroller scrollTop={props.offsetTop}>
    // InnerTable should use pure rendering, so that we don't re-render
    // when the scroll offset changes (16:34 youtube video)
    <InnerTable width="123" style="blue"/>
</OuterScroller>
```

```javascript
// example of shouldComponentUpdate
var StaticTwoColumnSplit = React.createClass({    
  shouldComponentUpdate: function(nextProps) {    
    return false;
  },

  render: function() {
    return (
    	<div>
    		<FloatLeft>{this.props.children[0]}</FloatLeft>
    		<FloatRight>{this.props.children[1]}</FloatRight>
    	</div>
    );
  }
});

<AdsApp width={props.width}>
	<Header />
	<StaticTwoColumnSplit>
		<SocialWidgetContainer />
		<MusicWidgetContainer />
	</StaticTwoColumnSplit>
<AdsApp/>
```

**Comment by francoislaberge** [comment]
@mtscout6 For simple components like buttons you could manually implement pure react mixin like behavior. But is it really that big? It only implements a comparison of the previous and new props and state. So I'd be surprised if does that much. Just using it to do the common implementation most simple components need would make sense I think.

Buttons for instance, only have a few props/states so it should definitely have a shouldComponentUpdate() implementation. Many components will work this way. Then composing these leaf components becomes quite efficient by default.

**Comment by francoislaberge** [comment]
Reminder: 

From https://facebook.github.io/react/docs/pure-render-mixin.html:
> This only shallowly compares the objects. If these contain complex data structures, it may produce false-negatives for deeper differences. Only mix into components which have simple props and state, or use forceUpdate() when you know deep data structures have changed. Or, consider using [immutable](https://facebook.github.io/immutable-js/) objects to facilitate fast comparisons of nested data.

> Furthermore, shouldComponentUpdate skips updates for the whole component subtree. Make sure all the children components are also "pure".

So in terms of size, tracing PureRenderMixin. It might make sense to just pull out the code as it's not clear how you include it without the kitchen sink from the react module. Here's the entire code required to implement PureRenderMixin: (I removed comments to just show lines of code)

From [addons/ReactComponentWithPureRenderMixin.js]
```js
(https://github.com/facebook/react/blob/master/src/addons/ReactComponentWithPureRenderMixin.js):
'use strict';
var shallowCompare = require('shallowCompare');
var ReactComponentWithPureRenderMixin = {
  shouldComponentUpdate: function(nextProps, nextState) {
    return shallowCompare(this, nextProps, nextState);
  }
};
module.exports = ReactComponentWithPureRenderMixin;
```

From [addons/shallowCompare.js](https://github.com/facebook/react/blob/master/src/addons/shallowCompare.js):

```js
'use strict';
var shallowEqual = require('shallowEqual');
function shallowCompare(instance, nextProps, nextState) {
  return (
    !shallowEqual(instance.props, nextProps) ||
    !shallowEqual(instance.state, nextState)
  );
}
module.exports = shallowCompare;
```

From [utils/shallowEqual.js](https://github.com/facebook/react/blob/master/src/utils/shallowEqual.js)
```js
'use strict';

function shallowEqual(objA, objB) {
  if (objA === objB) {
    return true;
  }

  if (typeof objA !== 'object' || objA === null ||
      typeof objB !== 'object' || objB === null) {
    return false;
  }

  var keysA = Object.keys(objA);
  var keysB = Object.keys(objB);

  if (keysA.length !== keysB.length) {
    return false;
  }
  // Test for A's keys different from B.
  var bHasOwnProperty = Object.prototype.hasOwnProperty.bind(objB);
  for (var i = 0; i < keysA.length; i++) {
    if (!bHasOwnProperty(keysA[i]) || objA[keysA[i]] !== objB[keysA[i]]) {
      return false;
    }
  }
  return true;
}
module.exports = shallowEqual;
```

Using all of that code, you get a good generic and understood props/state based optimization.

Thoughts? Would it help if I made an npm module that just has this code so other's following our trail get to include just it also. Maybe I'm missing something but I couldn't find a module that has implemented just it.

**Comment by taion** [comment]
@francoislaberge You've just described react-pure-render. And react-purerender.

**Comment by francoislaberge** [comment]
Ha, I had just created [react-pure-render](https://www.npmjs.com/package/pure-render-mixin) too. I didn't look far enough down the results for the [?q=pure+render+mixin](https://www.npmjs.com/search?q=pure+render+mixin) query I ran.

**Comment by AlexKVal** [comment]
Yeah.. all that in 32 loc is in `react-purerender` :smiley:  
For those who interested, just for quick reference https://github.com/brigand/react-purerender/blob/master/index.js

**Comment by taion** [comment]
I'd say that we should go with react-pure-render and extend the base component. What does everyone think?

**Comment by francoislaberge** [comment]
Sounds good to me. I just vote for adding as many no-op render calls as possible.

**Comment by AlexKVal** [comment]
In the case the way with `pure-render` mixin is taken:

I would do the same as `react-purerender` did but for this project.
(I mean it's borrowed code from some react files, simplified it and placed into one file)

I would create `utils/pure-render.js` file with those 32 loc.

Files in `utils` folder are borrowed from another projects
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/utils/EventListener.js#L2
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/utils/Object.assign.js#L2

The code for `pure-render` in fact is a one file.

And it less one dependency 
that could make [![devDependency Status][dev-deps-badge]][dev-deps] button red on the [Readme](https://github.com/react-bootstrap/react-bootstrap) page


[dev-deps]: https://david-dm.org/react-bootstrap/react-bootstrap#info=devDependencies
[dev-deps-badge]: https://david-dm.org/react-bootstrap/react-bootstrap/dev-status.svg

That's just my two cents :smile:

**Comment by francoislaberge** [comment]
@AlexKVal  :+1: to just inlining it into a util's file.

**Comment by taion** [comment]
I think it makes more sense to have the dependency instead of repeating that code. If we don't trust third-party dependencies, why are we even using `classNames`? We'd benefit from any relevant upstream bugfixes, for example.

That said, thinking about this a little more, this is not a valid change to make. To wit:
>Furthermore, shouldComponentUpdate skips updates for the whole component subtree. Make sure all the children components are also "pure".

Even for something as straightforward as a `Button`, there's nothing to prevent users from sticking a child component inside the `Button` that is not pure, and thus implementing pure render functionality would be incorrect. In general, in this sort of case, the only available solution is relying on virtual DOM diffing.

If a user knows that his usage of a component does follow the pure render contract, then the user can include pure render at a higher level in his preferred way. However, we can't do it at this level, so I'm inclined to reject this issue as invalid.

**Comment by francoislaberge** [comment]
How do you stick something inside of a button in react without explicitly supporting it? Does this module's button support that?

**Comment by taion** [comment]
The same way you put things inside `<div>` elements. It just boils down to virtual DOM diffing.

Any component that supports user-specified children cannot calculate `shouldComponentUpdate` by itself. Unfortunately, that's most of React Bootstrap.

**Comment by francoislaberge** [comment]
Gotcha. You could check for that. If there are no children the optimization can apply. Right?

**Comment by taion** [comment]
Yes, but that ends up being much less neat. Better at any rate for the higher-level component that is calling into React Bootstrap to implement the relevant pure render logic, both from the perspective of performance and the perspective of code cleanliness.

I think it's the wrong thing to spend a lot of effort avoiding redraws on buttons and inputs, when what you really want is to e.g. set up the pure render behavior on the containing form element itself. This is pretty much how normal buttons and other things work.

**Comment by AlexKVal** [comment]
@taion My two cents about `32 loc new file` in `utils` was all about a compromise :smiley: 

as @mtscout6 wrote
> I'm not sure yet if we want to take on another dependency like react-pure-render.

Just a compromise :beers: 

As for the main theme of topic:
It seems that added functionality would have questionable benefit:
a) It would cause an additional maintenance overhead.
b) And, what I think is the most crucial, it would lead to subtle bugs and additional questions from users.

"All the great things are simple."

This library has to be as simple as possible. 
Just a layer of glue between Bootstrap and React. No more.
Except perhaps `Accessibility` - the main feature of this project in the future.

> If a user knows that his usage of a component does follow the pure render contract, then the user can include pure render at a higher level in his preferred way.

We cannot and have not to solve all possible user cases.

I lean more to back up @taion's decision
> ...to reject this issue as invalid.

**Comment by francoislaberge** [comment]
@AlexKVal Good recap/thoughts. I'm sold by the multiple points people have made in this thread, that not trying to integrate is probably the best move for the reasons you outline above. This lib could be wrapped in another layer by people who do want this optimization on a set of components they've built on top of it.

...not that this is my project to have an opinion. But just saying as the issue submitter I don't take offense to it being rejected as a proposal.

**Comment by AlexKVal** [comment]
I'm not rejecting your proposal ! :balloon: 
There are owners who determine shape of this project :flags: 

This is not my project to accept or reject proposals. :baggage_claim: 
(But I like it and I use it. :smile: )
I just voiced my opinion from maintainer's point of view. :cake: 

Least of all I wanted to offend or upset someone. :cherries: 
Especially someone who wants to make contribution. :sparkle: :sparkle: 

I know it by my very own expiriense how offensive can look someone's posts written in neutral tone :cherries: 
That's my fault that I've written my arguments without emojis :wink: 
(BTW: Your perseverance alone by itself deserves acknowledgment :+1: )

**Comment by francoislaberge** [comment]
Nope, wasn't offended. Just saying I'm cool with that decision, and wasn't trying to sound like I was sad that my original idea wasn't the best fit for the goals of the project. You didn't sound anything but articulate and neutral in a professional cordial way. So no worries.

**Comment by AlexKVal** [comment]
Oh... Thank you :blush:

**Comment by francoislaberge** [comment]
Hahaha, and hilarious use of emoticons to make it clear you are positive.

**Comment by mtscout6** [comment]
@francoislaberge I'd also like to voice my appreciation for following though on this issue and taking many angle into account. After reading all of this, I'm on the same page as the other collaborators. I appreciate the eye for performance tuning as that objective can get lost at times when focusing on a clean API. However, as you mentioned earlier it's still possible to wrap the components you need with this performance enhancement when you need to. Also, with the use case of a `context` (the undocumented feature of react that react-router has been based on) that would also cause problems.

**Comment by francoislaberge** [comment]
No problem. My pleasure. I now have a better idea of the considerations for my component set that I think I'll be using ```react-bootstrap``` for.

**Comment by timkendrick** [comment]
Just come across this issue – are you sure you can't implement `shouldComponentUpdate` across the board?

As far as I see it, the sole objection is the following statement in the PureRenderMixin docs:

> Furthermore, shouldComponentUpdate skips updates for the whole component subtree. Make sure all the children components are also "pure".

...but my understanding is that this refers only to descendant components that are *created within the render function*.

As far as I'm aware, any 'child' components that are created externally and *passed in via the `children` property* will still be re-rendered based on their own `shouldComponentUpdate` rules.

I've made [a jsFiddle](https://jsfiddle.net/ocx304qf/) that demonstrates this behavior – the `Wrapper` component always returns `false` in its `shouldComponentUpdate` method, however if you click the `Toggler` element which is injected in via the `children` property, it will re-render (because it's not technically part of the `Wrapper` component's subtree).

Let me know if I'm misunderstanding the problem here!

**Comment by taion** [comment]
That's coming via a `setState` in the child. If e.g. the state lived on wrapper or a parent of wrapper, then you wouldn't see the update.

**Comment by jquense** [comment]
@timkendrick the problem is that we accept children for many/most components so updates move through the components not jsut under or above them:

see: https://jsfiddle.net/ocx304qf/2/

**Comment by dozoisch** [comment]
@jquense I guess what he means would be using the a shallow diff in scu instead of a static one?

**Comment by timkendrick** [comment]
Hi guys – sorry for the delay in responding.

Thanks for the fast response @taion and especially for the modified example @jquense. I didn't realise `shouldRenderComponent` behaves like this – turns out my assumptions about `children` belonging to a different subtree were completely false. You learn something new every day I guess…

Thanks again for the clarification!

**Comment by jquense** [comment]
It would be feasible in some cases, there is just little benefit to doing so. In the cases where we can really can use a SCU, those components are usually ad the end and bottom of a component hierarchy. for instance Button, where you really gain nothing by adding a SCU because it costs almost nothing to do the reconcilation and if you did decide to not update that only prevents a a small small number of dom changes. For components that are higher up like Panel, or Tabs, the user can more easily (and durably) add a SCU to their components that wrap or go instead the Panel, Tab, etc. So in general any place an SCU might be useful, its easiliy addable by the consumer, which is a lot less error prone and more likely to be useful then us doing it in a some very general way.

**Comment by timkendrick** [comment]
@jquense @taion Sorry to keep dredging this back up, but I've just thought that perhaps @jquense's example doesn't disprove what I was suggesting in the first place – see updated fiddle [here](https://jsfiddle.net/ocx304qf/3/). The `Static` component now has a fully-functioning `shouldComponentUpdate` method, but its injected child content still re-renders as expected.

The injected child component is passed as the `props.children` value, so any changes to the child component would be correctly picked up by the `PureRenderMixin`. Therefore the `shouldComponentUpdate` would return `true` for situations where the injected child components have changed, rather than `false` all the time as in my (incorrect) original example.

Unless I'm mistaken, I can see this being useful for react-bootstrap components such as `Panel` (which according to the `react-addons-perf` is one of the main sources of wasted redraws in an app I'm working on).

See [here](https://jsfiddle.net/ocx304qf/4/) for an updated example showing how a react-bootstrap `Panel` component with a `shouldComponentUpdate` method can interact gracefully with user-defined components without a `shouldComponentUpdate`.

I'm probably missing something major that you guys are taking for granted, so let me know if I'm barking up the wrong tree here!

**Comment by taion** [comment]
If you care about reconciliation checks, why can't you put the pure render check one level up?

Anyway, see discussion on https://github.com/facebook/react/pull/6914 – it's really generally not appropriate for libraries at the level of abstraction of R-B to impose purity checks, at least until issues like the ones in the linked PR get resolved regarding edge cases with impure user components.

**Comment by timkendrick** [comment]
My use case was more for situations like large accordions, where you might have one panel that updates and ten sibling panels that don't, therefore you can't put the pure render check one level up, so you have to put it 'one level down', i.e. within the child component. I was hoping that if the child component render check came back falsy, the `Panel` component wouldn't need to re-render seeing as the child content hadn't changed.

This is where my assumptions were totally wrong: I've just done [a test](https://jsfiddle.net/ocx304qf/5/) for this multiple-child scenario and it turns out that even if the child's `shouldComponentUpdate` comes back falsy, the parent's `render` method still generates a whole new (identical) child component instance that it passes into the `Panel`, rather than passing in the pre-existing instances (which makes total sense now I think about it).

This means that a strict equality check on `this.props.children` within the `Panel` component would always come back suggesting the children might have changed, so I'm guessing that while perhaps not harmful, it doesn't actually reduce the number of re-renders which is what I was hoping for.

Thanks so much for your patience, and sorry for muddying the waters – I'll back out now! 😄
