### ISSUE TITLE
Scrolling popovers example renders the popover in the wrong place

### ISSUE THREAD

**Issue by AlexKVal** [react-bootstrap/react-bootstrap#641]
@taion [has noticed it](https://github.com/react-bootstrap/react-bootstrap/issues/157#issuecomment-100559732)
> This feature actually looks to be broken right now. The example on the components page with scrolling popovers sets container, but renders the popover in the wrong place:

![](https://cloud.githubusercontent.com/assets/3112159/7552417/99e7b05c-f667-11e4-8203-72fc891ac2c9.png)

**Comment by taion** [comment]
My plan is to update the positioning code for #173. If we're lucky, that might fix this issue as well.

**Comment by taion** [comment]
This doesn't happen when I run this example locally with `npm run docs`.

**Comment by mtscout6** [comment]
`npm run docs` is good for the most part but can have issues. Have you tried it with `npm run docs-prod`? That will build all the assets and run a server that only provides static assets similar to the github pages.

**Comment by taion** [comment]
That's an incredibly bizarre edge case though. Not sure what's going on.

**Comment by taion** [comment]
Of all things, this looks like it's a bug with the CSS minification. Somehow the `position: relative` on the example container gets lost.

Looking at the way `domUtils.getPosition` is implemented, that shouldn't matter, but I don't have any more time to look at popovers for now.

**Comment by taion** [comment]
FWIW, `domUtils` has a way to find the actual offset parent: https://github.com/react-bootstrap/react-bootstrap/blob/1d52a762515665d91b76afa22d81b63831aa2370/src/utils/domUtils.js#L104-L114

However, we don't use it for this codepath (I missed that check earlier), which is probably for the best. It should be sane to require containers to be relatively positioned. Otherwise it makes the "fit in viewport" logic much more complicated.
