### ISSUE TITLE
PurgeCSS support.

### ISSUE THREAD

**Issue by k1rowashere** [react-bootstrap/react-bootstrap#6443]
### Is your feature request related to a problem? Please describe

React-bootstrap is incompatible with [purgecss](https://purgecss.com) due to the fact that RB uses string interpolation to set classnames.

PurgeCSS is good for removing unused css and making load times faster. ( I got my bootstrap css down to less than 9KB compressed )

### Describe the solution you'd like

It is possible to add a logging function of sorts to each component which logs the classnames used by that component, then export the list to a file to whitelist in purgecss.

Example:
`
// classes.txt
active
align-content-center
align-items-center
align-items-end
align-self-center
btn
btn-close
btn-close-white
btn-light
btn-outline-dark
btn-outline-light
...
`

(I tested this by adding an `append to file` function to the [classnames](https://www.npmjs.com/package/classnames) module which is used by RB to set some (but not all) classnames)

Sadly this only makes sense in a static generation environment (I used nextjs), but something could be figured out on the browser (maybe log it to the console in dev mode?)
Also it wont work if the component is rendered conditionally or on client only.

### Describe alternatives you've considered

Alternative solution may involve a regex to get component props from src then use the same logic to calculate classnames, this seems overly complex, but will work on all types of rendering. 

### Additional context

PS. Feel free to suggest ideas, I am down to implement this one and push it somewhere.

**Comment by golota60** [comment]
heyo! If we were to implement such support, it would definitely have to work both in browser and on the server(i suspect react-bootstrap is mostly used on the client). With that being said, this would be quite challenging since we can't know what classes will the components use upfront without explicitly and imperatively specifying such info. 

What makes it even more tricky is that a lot of components accept a `bsPrefix` param that prefixes bootstrap classes, which would potentially break any hard-coded list of classes. 

To be quite honest, I've got no idea how we could implement that without creating some massive hacks that would be hard to maintain(e.g. creating corresponding files/comments with classnames a given component uses). I'm open to ideas though
