### ISSUE TITLE
Dropdown toggle overlayed not overlayed by dropdown menu

### ISSUE THREAD

**Issue by Jakbejk** [react-bootstrap/react-bootstrap#6451]
# Prerequisites
- [ ] Build dropdown with **custom toggle** inside **react-bootstrap/Tab (react-bootstrap/Tabs)** (must contains at least three Tab)
- [ ] Resize it on phone size (items must align vertically)
- [ ] Open first dropdown menu
# Describe the bug
Dropdown toggle **is not** overlayed by dropdown menu. 
# Expected behavior
Dropdown toggle is in background.
# Screenshots
![image](https://user-images.githubusercontent.com/63671846/192290615-267dfc18-d955-4e25-8f7b-d1b7137ebd55.png)

**Comment by golota60** [comment]
Hey! Not really sure what the steps to reproduce are here - would you be able to provide a [codesandbox example](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic) or share the JSX markup you used to achieve this? thanks

I've tried reproducing it [here](https://codesandbox.io/s/long-fast-lorjqv?file=/src/App.js) but to no avail.

**Comment by Jakbejk** [comment]
I replicated issue in [SandBox](https://codesandbox.io/s/awesome-darwin-vvfplx?file=/src/App.js)

**Comment by golota60** [comment]
Thanks! I've dove a little bit more into it and it's caused because the stacking contexts are getting mixed up. The broader issue though is that we're rendering a `a` inside an `a` element, which is invalid markup(interactive content inside another interactive content). This is why the issue is not happening if you simply render a dropdown under a dropdown.

If you try to repro this in bootstrap(like I've tried [here](https://stackblitz.com/edit/cfakh5-jrip2b?file=index.html)) what you'll see that when you try to render a `a` inside an `a`, like this:
![image](https://user-images.githubusercontent.com/37072867/192594635-f1f95f5a-42ca-41dd-8233-8703250c6d70.png)
you'll see that what is actually rendered is quite different
![image](https://user-images.githubusercontent.com/37072867/192594774-d8be0e7b-1eff-490f-8e2a-00acf130637c.png)

I'm afraid if you really want to take control of `Tabs`, you should create your own [custom tab layout](https://react-bootstrap.github.io/components/tabs/#custom-tab-layout). Then you can fully control z-indexes and stacking contexts.

If you want a quick and easy solution you can add a `tabClassName` to `Tab` component and then add a `z-index` to it [like this](https://codesandbox.io/s/brave-stitch-d6eh8z?file=/src/App.css)
