### ISSUE TITLE
Add documentation for an input addon with checkbox or radio button

### ISSUE THREAD

**Issue by dlong500** [react-bootstrap/react-bootstrap#665]
I haven't been able to get an addon with a checkbox or radio button to work like shown here in the Bootstrap docs: http://getbootstrap.com/components/#input-groups-checkboxes-radios

Is this not supported yet or am I just not seeing the proper way?  Admittedly I'm fairly new to React so it's possible I'm just missing something.

**Comment by mtscout6** [comment]
I don't think you'll be able to use our `Input` component for the radio since that will attempt to wrap the radio button with other bootstrap markup. But you can get it with the html input. For example:

```
const innerRadio = <input type='radio' />;

const inputAddonsInstance = (
  <form>
    <Input type='text' addonBefore={innerRadio} />
  </form>
);

React.render(inputAddonsInstance, mountNode);
```

You can copy and paste that into any of the "show code" tabs on http://react-bootstrap.github.io/components.html and see it in action.

**Comment by mtscout6** [comment]
Since Bootstrap is documenting this we should also add this example to our documentation.
