### ISSUE TITLE
Trim down the Bower release

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#693]
We have been running into problems recently with the bower release not being as usable as the npm release primarily due to the different distribution mechanism that bower proposes.

Seeing as React, as well as many Bower packages, only provide the concatenated and minified build output I'm inclined to do the same here.

Pros:

- Easier to maintain since dependency differences between the two will be less complicated.
- React addons/utils can be cherry-picked as needed, and not committed to this repo.
- Allow us to use [`babel-runtime`](http://babeljs.io/docs/usage/runtime/) without declaring it as a bower dependency.
- Use `require('babel-core/polyfill')` in `Interpolate.js` and `OverlayTrigger.js` and remove `babel-plugin-object-assign` dependency.

Cons:

- Bower users will be forced to load the entire library all the time. They will not be able to optimize their release.
- This will complicate the react-router-bootstrap bower release and source. (Will be resolved by react-bootstrap/react-router-bootstrap#74)

My questions for bower users, since I don't personally use it:

- What is bower gaining you that you can't get with npm?
- What would you expect from a bower package?
- What am I missing here?

**Comment by mtscout6** [comment]
@tacomanator Are you using bower with those factories you made or npm?

**Comment by kirill-konshin** [comment]
> What is bower gaining you that you can't get with npm?

Not all libraries are accessible via NPM and it's not guaranteed that NPM distribution will be browser-compatible in general or will be compatible with client-side module loaders (primarily RequireJS).

> What would you expect from a bower package?

To me, best practice is to have NPM/Bower code 100% compatible (UMD declarations) for those who need granularity and who is not afraid to use cherry-picked files. But minified distribution must be provided anyway.

> What am I missing here?

Libraries should not use internals of other libraries. Even in NPM world it's considered as a bad practice to cherry-pick individual files like `require('packageName/lib/stuff')`, it's recommended to use `require('packageName').stuff`. 

On the other hand when it comes to NPM use for client-side (say, Browserify or Webpack) it makes sense to include only specific files in order to save some bytes of the build. I think it's kind of acceptable to use individual files in the *product* but not in *library*.

For example in React Router package authors specifically mentioned that only public API may be used and usages of individual files are prohibited since it leads to constant errors (file structure may change over time, API usually is more well-maintained thing).

If you *really* need modular approach, you can release core + buttons + glyphicons (say, most widely used parts) as one package and the rest as another package that depends on first package. Angular is a perfect example of that, there is Angular itself, Angular-Resource, Angular-Route and so on and developers are free to choose what to include.

By the way, React Bootstrap minified is ~100K which is fine for what it brings, Twitter Bootstrap (JS itself) is 36K, by the way. Maybe if we can optimize the code base and make it smaller, we can offload the question about size. I'd say, that anything that is smaller than ~50K or even ~100K is OK to be included as-is without messing with modularity.

**Comment by tacomanator** [comment]
@mtscout6 while I had used Bower in the past, but all of my current projects use NPM.

In a perfect world all libraries would allow selective import and customization during build.

I try to use existing libraries whenever possible which is often so I usually end up using quite a lot of libraries in my projects. For a single library it's easy to think "who cares just import everything" but with many the size adds up quickly. For libraries such as react-boostrap with are not small or single-purpose, it's very nice when things can be used selectively.

The perhaps more important consideration for me was the ability to set variables and have bootstrap built for me during the build process. I don't understand why this hasn't caught on more widely than it has. IMO it's the most maintainable approach, and I wish more libraries adopted it.

**Comment by mtscout6** [comment]
Closed by #815

**Comment by alampros** [comment]
The docs need to be updated to reflect this change.

**Comment by AlexKVal** [comment]
Definitely :+1: 
Thank you for pointing to this :cherries:

**Comment by mtscout6** [comment]
Closed by #1107
