### ISSUE TITLE
Pre-releases should not generate a changelog

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#746]
When releasing with the `--pre` option we should not generate a changelog. This may require a deviation from the current changelog tool to pick up changes since the last non-pre-release release.

**Comment by dozoisch** [comment]
I'm not sure about this. Because it's always useful to have the changes in PRE.. especially in between different RC. You want to see what has been fixed. Maybe we'd need to be able to have the changes written in the pre, but once the release is made, we "squash" the changes together under the release.

**Comment by mtscout6** [comment]
If that's the case I wonder if it would make sense to have a separate changelog for the pre-releases. Which we can remove once the actual release occurs. Then start the cycle again for the next round of pre-releases.

Related to #747
