### ISSUE TITLE
Why drop support of bsStyle on Modal ?

### ISSUE THREAD

**Issue by YannPl** [react-bootstrap/react-bootstrap#750]
Hi !
Why have you dropped the support of bsStyle on Modals (https://github.com/react-bootstrap/react-bootstrap/commit/379ea3ecbcf0cb2838a6cf85fc8fd9a3d07240ea), I think it was an awesome feature !

I couldn't find a workaround in 0.23, is there an easy way I haven't seen to put Bootstrap's color on modal Headers without having to deal with custom CSS ?

**Comment by mtscout6** [comment]
There were a number of issues with it.

It was first introduced in #403, and we first noticed a problem in https://github.com/react-bootstrap/react-bootstrap/pull/403#issuecomment-75964220 which we fixed by applying an inline style in [13f395d](https://github.com/react-bootstrap/react-bootstrap/blob/13f395d2304727d65ee22242423150c22b73addb/src/Modal.jsx#L61).

This had unintended consequences like the ones described in https://github.com/react-bootstrap/react-bootstrap/pull/605#issue-72734913 and #448.

We tried to take the idea directly to the Bootstrap team in twbs/bootstrap#16431 which was promptly denied.

I liked the idea, but don't know how to implement properly at the moment. If we were able to figure out a proper solution that did not create so many undesired effects then I could still see value in it. Our first priority is parity with Bootstrap at the moment, and this is one such case where this is not the same. So we opted to remove it instead of fight it.

I'd be open to a PR that re-introduced it, though I don't know how the other @react-bootstrap/collaborators would feel about it. That PR would need a lot more scrutiny to ensure we didn't end up in the same boat again.

**Comment by mathieumg** [comment]
I'm on the fence about this one since it provides something that Bootstrap decided not to provide. I would have said that it's fine as long as it's done in a way that doesn't degrade the current experience, as you pointed out, however I imagine supporting it would require some custom CSS from the user (to address the rounded corners, if I understood correctly), is that correct? 

At that point, how different would it be for the user to provide a custom `className` rather than a `bsStyle` property? My point being, if users try to use the `bsStyle` without being aware that it requires custom CSS, they would think the feature is broken, wouldn't they?

**Comment by YannPl** [comment]
Thanks for both of your answer ! Helped me a lot to understand what's going on. :+1: 
I'll see if I have a good implementation for thar or I'll simply end up with some custom CSS.

**Comment by mtscout6** [comment]
Sounds good, feel free to re-open or send a PR if you figure out something that will work.
