### ISSUE TITLE
Is react-bootstrap a server side library or can I use it in a browser.

### ISSUE THREAD

**Issue by mingfang** [react-bootstrap/react-bootstrap#77]
Sorry I'm completely to this these things.
I created a simple test like this

```
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <script src="http://fb.me/react-0.10.0.js"></script>
    <script src="http://fb.me/JSXTransformer-0.10.0.js"></script>
    <script src="react-bootstrap.js"></script>
</head>
<body>
<div id="react"></div>
<script>
</script>
<script type="text/jsx">
    /**@jsx React.DOM */

var buttonsInstance = (
    <ButtonToolbar>
      <Button>Default</Button>
    </ButtonToolbar>
  );

React.renderComponent(buttonsInstance, document.getElementById('react'));</script>
</body>
</html>
```

But I'm getting this error in Chrome
Uncaught ReferenceError: ButtonToolbar is not defined 

Does this framework only work on the server side?

**Comment by knsn1994** [comment]
This was a lifesaver! Had already wasted two days over it.

**Comment by drorsun** [comment]
oh wow, what a save (wasted just six hours)

**Comment by dpford** [comment]
Why is this not in the docs?

**Comment by taion** [comment]
Why is _what_ not in the docs?

The example in the OP that's just plainly confused because it's not server-side code at all?

The caveat about JSX that is actually just wrong at this point?

Some utterly pointless, trivial, and unnecessary caveat given that all of React works just fine on both browser and server?

Please enlighten me.
