### ISSUE TITLE
Live help sessions?

### ISSUE THREAD

**Issue by cmrnh** [react-bootstrap/react-bootstrap#783]
I contacted @mtscout6 and he suggested posting this here as you guys do everything by open governance.

What do you think about setting up regularly-scheduled, live hangouts for helping react-bootstrap users work through integration issues?

The goal is to create an extra layer of support for users who otherwise might open up issues for questions that could be better solved by jumping into a short pair-programming / screenshare session.

It's the kind of thing we do with our students at [Thinkful](http://thinkful.com) and I'd be curious to see if it works outside our walls... We already hold sessions on React so it'd be easy to open those up to the broader react-bootstrap community.

The closest comparison to anything currently out there is IRC / Slack / Gitter. The difference is that live hangouts naturally enable pairing and code review.

Let me know what you think.

**Comment by mathieumg** [comment]
I only could find information about pricing regarding courses, what does it look like for mentoring?

**Comment by mtscout6** [comment]
How is this better than https://www.codementor.io/ ?

**Comment by cmrnh** [comment]
@mtscout6: Codementor is more like consulting, while Thinkful's courses have a structure for learning.

In any case, though, this program would be separate from our courses entirely. 

We already host regular React Q+A sessions for our students. This would open those regular (currently weekly) sessions up for free with the expectation that developers would show up with questions related to react & react-bootstrap.

@mathieumg: Here's the [mentor team](https://www.thinkful.com/mentors/) — pretty wide range of backgrounds, but we have a few folks (myself included!) who've been working with react in production for awhile.

**Comment by mtscout6** [comment]
Do you have a session that we could join this week to observe what this entails?

**Comment by cmrnh** [comment]
@mtscout6 sure thing! our next React group session is scheduled for tomorrow actually — 11am ET. For anyone interested — [sign up](http://start.thinkful.com/react-mentoring) and we'll send you a link to the hangout just before the session: http://start.thinkful.com/react-mentoring

**Comment by mtscout6** [comment]
I will try to jump in tomorrow, if not I'll have to check it out next week. My son has kindergarten graduation tomorrow morning. I may need to leave the session early if I do join.

**Comment by cmrnh** [comment]
Sounds good @mtscout6 — the hangouts are pretty casual / come and go.

**Comment by mtscout6** [comment]
I joined the hangout this morning and I did like the ease of joining and the care that was taken to teach and include everyone that joined in. I could see a lot of benefit for these sessions towards those front-end developers that are just getting started. In fact @tomatau was there as one of the mentors, who is a recent contributor with the Utils namespace pull request.

@cmrnh I think you were another party on that hangout, though I'm not completely sure about that.

I heard mentioned, by @tomatau I think, that these sessions would occur at various times so as to account for people in multiple time zones. Has there been any consideration to presenting more than just the next session that's going to start at http://start.thinkful.com/react-mentoring?

Another concern I have is that there is no Code of Conduct listed on that site that you linked here. I think something like that would be useful to ensure that people are reminder to be human beings with each other in this forum. Not that I saw that as a problem, only to help prevent future issues.

I personally wouldn't mind adding a link to our documentation site to direct traffic there. I'm thinking that a new Support page would be helpful. I say a new page because there are a number of avenues that people can use to get support. For Example: (In no particular order)

- [Stack Overflow - tag react-bootstrap](http://stackoverflow.com/questions/tagged/react-bootstrap)
- [Github issues](https://github.com/react-bootstrap/react-bootstrap/issues)
- [Gitter](https://gitter.im/react-bootstrap/react-bootstrap)
- [Reactiflux slack community channel #react-bootstrap](http://www.reactiflux.com/)
- [Thinkful](http://start.thinkful.com/react-mentoring)

There may be more! The beauty of it all is that each of those are very active.

@cmrnh Would you or one of your team member's at Thinkful be up to submitting a PR to add such a page? @react-bootstrap/collaborators would you all be ok with such a gesture?

**Comment by mathieumg** [comment]
I totally missed @cmrnh 's post indicating there was a session this morning, bummer.

:+1: for the Support page and I have no problem with everything you mentioned.

**Comment by AlexKVal** [comment]
This could popularize this library. :rainbow: 
I am :+1: :sparkle:

**Comment by cmrnh** [comment]
Thanks @mtscout6 @AlexKVal @mathieumg — and yes that was me :wave:

Re/ Code of Conduct: good suggestion! Will make that apparent.

Re/ showing more than just the next session: Yes! We're building a more robust reservation process that shows all the group mentoring sessions we have available across timezones.

@mtscout6 will submit a PR with a support page with the various resources laid out... stay tuned!

**Comment by mtscout6** [comment]
Fantastic we look forward to it.

**Comment by tomatau** [comment]
Yeh thanks for coming along!

Make sure you add "don't talk about material ui" to the code of conduct @cmrnh ! You've been warned! :P

**Comment by dozoisch** [comment]
@tomatau Actually that'd be cool if a merged happened like React-Bootstrap and React Material-UI and make a big React-UI master-race org!

**Comment by mtscout6** [comment]
Off topic, but that would be nice, though it would require a lot of decoupling from the current css classnames.
