### ISSUE TITLE
Use of a higher order function library utility

### ISSUE THREAD

**Issue by mtscout6** [react-bootstrap/react-bootstrap#889]
There was some discussion a while ago on gitter about adding [lodash](https://lodash.com/) for use of it's utilities for cleaner work with arrays, objects and other things. We are already using it as a dev dependency in our build scripts, testing, and in our documentation. The concern with adding it for support in the library itself is due to the added size that the library will be force to incur as a result.

I'd like to re-open the discussion in a formal tone and figure out a solution to at least allow us to pick and choose which functions we want from it in the project itself.

Options:

1. Use lodash's individual npm dependencies per function.
2. Be cautious that we don't import the entire library anywhere within the src folder.

Option 1 is there specifically because the lodash team has recognized this as a problem for their library, though it's tedious to maintain for each function we wish to use. Option 2 is nice since there would be fewer dependencies to maintain, but the likelihood of human error to remember not to import the entire library is high. Though I wonder how hard it would be to write a custom eslint rule that would enforce this for use. I'm thinkig of something similar to what @jquense proposed in #860. If it's feasible I prefer Option 2.

This has become a priority for me since using some of the functions from lodash would make the code cleaner for #526. 

Another curveball I'd like to get a feel for is potentially using [Ramda](http://ramdajs.com/) instead of lodash as it seems to follow functional programming standards for avoidance of state mutation, which is precisely reasonable when working with React. I have heard somewhere some time ago that React will make more use of [immutablejs](https://facebook.github.io/immutable-js/) more internally.

**Comment by mtscout6** [comment]
Turns out an eslint rule is easy to write for this: https://github.com/react-bootstrap/react-bootstrap/blob/lodash-eslint-error/tools/eslint-rules/lodash-import.js

**Comment by taion** [comment]
I'd prefer (2). Lodash is preferable because people are more familiar with it.

**Comment by AlexKVal** [comment]
[eslint-rules/lodash-import.js#L17](https://github.com/react-bootstrap/react-bootstrap/blob/lodash-eslint-error/tools/eslint-rules/lodash-import.js#L17)
`node.source.value !== 'lodash'` => `node.source.value === 'lodash'`

As for the using of `lodash` in the project:
- perf 
- size

are the main concerns here because this project is a general library with tons+ usage cases.

My current knowledge is that other libraries from the same niche are not using `lodash` (or equivalent)
in their code.
https://github.com/jquense/react-widgets 11,518 downloads in the last month
https://github.com/callemall/material-ui 9,868 downloads in the last month

https://github.com/instructure-react/react-menu/ 1,443 downloads in the last month
https://github.com/Khan/react-components 820 downloads in the last month

And it seems @jquense has the most experience to express on this topic. :cherries:

**Comment by jquense** [comment]
I tend to not use lodash or any utility libs because react already requires that you polyfill the Array methods and that's most of what I use them for. I don't usually need much else, they few methods I do use I just write myself since they are just a few line: omit, pick, transform. Mostly because even the modular lodash is a lot more code then the 10 line's needed to implement basic versions of all of those methods. 

So far I've just never hit a use case were lodash perf tweaks have mattered in libraries I've written (I have in apps).  It does protect against some bugs as well but they are usually far edge cases that haven't affected me. 

I am a big fan of lodash for apps. I tend to find the extra code unnecessary in libraries, solving problems I don't really have. I find the normal js code a lot more readable at this point, but readable is super subjective :)

**Comment by mathieumg** [comment]
Would option 2 allow deduping the same way option 1 would?

**Comment by jquense** [comment]
version 2 will also allow deduping but for others who use the full package. My impression is that most frontend use of lodash is going the option two route so that might be more beneficial.

The individual packages can also create issues for Windows issues, resulting in paths too long for windows to handle. This has been much improved in version 3, but it is still possible

**Comment by mathieumg** [comment]
I was under the impression Lo-Dash referred to its own modules through their npm package (even if they come from that same repo originally), but it seems it's rather they're published alongside the bundled version. Option 2 seems fine to me then, especially with the custom rule to enforce it already written! :+1:

**Comment by taion** [comment]
I'd say we should use lodash but keep it to things where we actually need it, i.e. don't use lodash's `forEach` when `Array.prototype.forEach` is fine.

**Comment by mtscout6** [comment]
@taion that makes perfect sense, I think I'll plan to make a lodash eslint-plugin where rules like that can be written. No need for something like this to be isolated to this repo.

**Comment by mtscout6** [comment]
I put together an new org and repo for the lodash eslint stuff at: https://github.com/eslint-plugins/eslint-plugin-lodash.

It only has the one import rule, but I figured that it would be a good start for anyone that wanted to add to it. Also felt like it was a better home for this.

**Comment by mtscout6** [comment]
Let me know if there are any takers to be members of that org to help maintain it.

**Comment by mathieumg** [comment]
I'll ping you if/when I need to update/add a plugin. :) I'm wondering, does that rule also support `require` calls?

**Comment by mtscout6** [comment]
Not at the moment, I tried to take a quick look to see if the require keyword was exposed in the AST for other parsers, I could not immediately see anything :disappointed: though I take PRs :wink:
