### ISSUE TITLE
Modal steals focus from children with 'autoFocus' property

### ISSUE THREAD

**Issue by Nutelac** [react-bootstrap/react-bootstrap#903]
Check out this Fiddle, it should hover input after modal after appers - https://jsfiddle.net/5rfx3ppp/
When `Input` is not inside `Modal`, it will focus - https://jsfiddle.net/4xmkbbk2/

Everything works in `^0.18.0`.

**Comment by dozoisch** [comment]
Try adding `enforceFocus={false}` on the modal

https://jsfiddle.net/5rfx3ppp/1/

**Comment by Nutelac** [comment]
Thanks. BTW why is this necessary?

**Comment by dozoisch** [comment]
maybe @jquense can enlighten you a bit more than I can!

**Comment by jquense** [comment]
I actually think this should be considered a bug. enforceFocus solves it but it loses the baby with the bath water, since it disables a bunch of important accessibility features. 

the problem is that it shouldn't steal focus from something inside the modal. I'm not sure we can fix it but we should at least split enforceFocus into two props. one for auto focusing the modal and one that maintains focus in the modal.

**Comment by Nutelac** [comment]
Thanks for the clarification.

**Comment by AlexKVal** [comment]
BTW Pull requests are welcome :wink:

**Comment by yordis** [comment]
@jquense I want to understand something. I tried using autofocus instead of autoFocus, just in case, and for some reason when my element is rendered there is not autofocus attribute in the element.

Where can I start to dive in about this? I am really new so give me some trouble to understand everything inside

**Comment by jquense** [comment]
React itselfhandles the autofocus attribute, it's not a react-bootstrap feature. Whether or no it actually uses the html5 attribute is an implementation detail to react, in its attempt to provide a consistent cross browser behavior for it. I don't believe this is documented anywhere in reacts doc though so it may be helpful to bring that question to that repo :)

**Comment by yordis** [comment]
Ya, I tried to debugged inside of React but I lost myself there :smile:
