### ISSUE TITLE
ListGroup TypeError: Cannot read property 'href' of undefined when children is Immutable iterable

### ISSUE THREAD

**Issue by cassus** [react-bootstrap/react-bootstrap#935]
From v13 React supports _iterators and immutable-js sequences as children._ (https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html)

ListGroup fails with `TypeError: Cannot read property 'href' of undefined` when the children is an iterable object.

Example:
```jsx
<ListGroup>
            { Immutable.List(['foo']).map((foo) =>
                    <ListGroupItem>
                        {foo}
                    </ListGroupItem>
            )}
        </ListGroup>
```

Workaround: add `.toJS()` after the map

**Comment by AlexKVal** [comment]
Could you please provide reproducible code snippet, then we can work with ?

Otherwise it is not clear what the problem is and how it should be addressed :sweat: 

Thank you :cherries:

**Comment by apkiernan** [comment]
I tried mocking something up to see what the issue is. The issue appears to be that the use of `Immutable.List.map` returns as the children to `ListGroup` an object containing ImmutableJS List objects, meaning they are not React components which are expected. I think the quote about supporting iterables and immutable sequences refers to the ability to map arrays and such from inside the children of a component which would then return React components. 

The workaround I found for this was to use Immutable's `toArray()` method before the `map` call, then use the map method as usual:

```
const Foo = React.createClass({
  render() {
    return (
      <ListGroup>
        {Immutable.List(['foo']).toArray().map((foo) => {
          return (
            <ListGroupItem>
              {foo}
            </ListGroupItem>
          );
        })}
      </ListGroup>
    );
  }
});
```

This is the same even if using generic components such as spans and divs. The result of the Immutable sequence needs to be React component(s), not just the Immutable object.

Please let me know if I'm missing something or am off base, and I will look into it further.

**Comment by jquense** [comment]
@apkiernan you are on track, react supporting iterates is not the same thing as supporting immutable js. if the sequence is not one of ReactElements then react can't render them, even tho it can iterate through it.

**Comment by cassus** [comment]
I don't see how Immutable.List.Map returns not React components when iterated.

```js
const iterator = Immutable.List(['foo', 'bar']).map((foo) => {
    return (
        <ListGroupItem>
            {foo}
        </ListGroupItem>
    )
})

for(const foo of iterator) {
    console.log(foo)
}
```

Logs
```
ReactElement {key: null, ref: null, _owner: ReactCompositeComponentWrapper, _context: Object, _store: Object}
ReactElement {key: null, ref: null, _owner: ReactCompositeComponentWrapper, _context: Object, _store: Object}
```

**Comment by jquense** [comment]
Here is the actual problem if the list does return elements: The ListGroup is using [`this.props.children.some`](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/ListGroup.js#L23) which assumes an array, so is skipping all the react iterable stuff. I believe it might work if we used `React.Children.map` so if someone would like to PR that i'm sure we'd merge it.

**Comment by cassus** [comment]
Should I use `[added]` prefix for the commit?

**Comment by jquense** [comment]
Yeah that makes sense to me
