### ISSUE TITLE
Offer constants in Row and Col class for grid

### ISSUE THREAD

**Issue by binarykitchen** [react-bootstrap/react-bootstrap#960]
I realize that our code has too many magical numbers due to the bootstrap grid. From 1 to 12. I think it would make the code prettier if the grid classes come with constants we can reuse.

Instead of

```
          <Col
            xs = 3
            xsOffset = 2
          >
```

how about?

```
          <Col
            xs = Col.WIDTH_3
            xsOffset = Col.WIDTH_2
          >
```

**Comment by taion** [comment]
Wouldn't we be better off renaming the props if we thought things were unclear? I'm not really a fan of trivial constants.

**Comment by AlexKVal** [comment]
A user of `Bootstrap` after reading the manual for Grid system http://getbootstrap.com/css/#grid-options,
expects exactly something like
`xs = 3`, `lg = 5` etc.

`xs = 3` looks simpler and shorter and faster to type than `xs = Col.WIDTH_3`. Isn't it ?

Because it is possible to make a custom grid system http://getbootstrap.com/customize/#grid-system
hence constants could be more a hindrance than help.

This project seeks parity with `Bootstrap` API. Constants are not a part of `Bootstrap` API.

The React-Bootstrap's API for `<Col>` component are general and flexible enough
so everyone is free to write like that `xs = Col.WIDTH_3` in their code.

:cherries:
