### ISSUE TITLE
Hard to test new Modal, can't reach into the Modal content.

### ISSUE THREAD

**Issue by cassus** [react-bootstrap/react-bootstrap#966]
I'm looking for a `getModalContents` function that allows me to reach into the modal content's components in my tests.

```js
export const MyModal = React.createClass({
    render() {
        return <Modal onHide={()=>undefined} show={true}
            >
            <Modal.Body>
                Hello world!
            </Modal.Body>
        </Modal>

    },
})

it(`MyModal content`, async ()=> {
    var compInstance = ReactTestUtils.renderIntoDocument(<MyModal />)
    var modalContents = getModalContents(compInstance)
    assert.include(React.findDOMNode(modalContents).textContent, "Hello world!")
})

```

I tried and failed with `modalContents.refs['modal']` (no ref)
and `ReactTestUtils.findRenderedComponentWithType(compInstance, ModalMarkup)` (`ModalMarkup` is private)

**Comment by jquense** [comment]
The problem is that the modal content is actually  __not__ rendered in the same tree as the `compInstance`, but calls `React.render()` internally making the testutils not super helpful here (the same is true for anything using the Portal component like tooltips).

In probably the next upcoming release, we've added a ref on the Modal component to the ModalMarkup component for easier testing. For now though I would split the modal into two parts the content and the content wrapped in a modal, that way you can test the content component seperate from it being in a Modal

**Comment by cassus** [comment]
:+1: for the ref idea (I hope it works across different React render roots)

Splitting myModal into myModal and myModalContent is the way I'll go until next release.

**Comment by AlexKVal** [comment]
Can we close this issue now ? :smile:

**Comment by cassus** [comment]
Is there an issue to have a ref on the Modal component? I'd like to link to that issue as follow-up before closing this one.

**Comment by jquense** [comment]
sure its #942

**Comment by cassus** [comment]
:+1:
