### ISSUE TITLE
Change Panel and ListGroupItem API

### ISSUE THREAD

**Issue by kylehood** [react-bootstrap/react-bootstrap#983]
Per the documentation: http://react-bootstrap.github.io/components.html#panels, when using a panel, unless you specifically supply the header prop some heading tags, it will print the title area as normal text within the panel-heading div. If you wrap that Panel in an Accordion, supplying just a string to Panel's header prop will suddenly output a title wrapped in an H4.

I think this is inconsistent behavior. Is there any reason why it specifically creates an H4 tag in this instance? I would like to have an accordion panel where the heading text is just normal text and not an H4.

Panel.js:187 looks like it could be the culprit.

To reproduce create:

<pre>
   Panel header='test title' 
</pre>

Note that the title is rendered as normal text. Then try:

<pre>
   Accordion
        Panel header='test title'
   /Accordion
</pre>

The title now automatically becomes an H4

**Comment by AlexKVal** [comment]
According to `BS3` docs http://getbootstrap.com/components/#panels-heading
there are two additional classes for panel headers
`.panel-heading` class to make `div` as header for panel 
and `.panel-title` class exactly for use with `<h1>-<h6>` headers

`R-B` `Panel` component has just `header` property - which indeed has inconsistent behavior
http://react-bootstrap.github.io/components.html#panels-props

It seems it's need to be re-factored. :sparkle: 

--
Let's think about new / changed API for this.
What is the best way to achive it ? Your ideas guys.

**Comment by taion** [comment]
This API is poorly designed - we should have separate `heading` and `title` props.

**Comment by jquense** [comment]
Been thinking about this, but all api's strike me as verbose or ugly...

```
<Panel>
  <Panel.Header>
    <Panel.Title>hi!</Panel.Title>
  </Panel.Header>
  <Table>...</Table>
</Panel>
```

maybe? we'd loose some of the functionality with making it collapsible. Maybe we jsut drop that as a feature to begin with? Or make it probably controlled all the time, and let the user handle the heading click to collapse?

**Comment by taion** [comment]
I'd actually go with a more minimal change to the current API, where the user can do either

```js
<Panel heading="foo">
  bar
</Panel>
```

or

```js
<Panel title="foo" />
  bar
</Panel>
```

In the former we don't apply any of the `title` styling; in the latter we do. Plus spit out an error if the user tries to specify both `heading` and `title`... otherwise essentially the same as the current API, just slightly more explicit.

**Comment by AlexKVal** [comment]
Header could be any of `<h1>...<h6>` sizes.

**Comment by taion** [comment]
@jquense 

With that API, couldn't we do something like

```jsx
<Panel collapse>
  <Panel.Heading>
    <Panel.Title>hi!</Panel.Title>
  </Panel.Heading>
  <Table>...</Table>
</Panel>
```

for the simple uncontrolled case? IMO we need something like that to get a sensible `Accordion` component without forcing users to do too much on their own.

I don't know - for completeness, though, a basic `Panel` would have to look like e.g.

```jsx
<Panel>
  <Panel.Heading>
    <Panel.Title>hello</Panel.Title>
  </Panel.Heading>
  <Panel.Body>
    world
  </Panel.Body>
</Panel>
```

Is it worth the verboseness though? Compared to e.g.

```jsx
<Panel title="hello">
  world
</Panel>
```

Then again, it makes the API for panel-filling `Table`s and `ListGroup`s a more TWBS-y and a bit less of our own special then. It also makes the `Panel` API a lot more consistent with the `Modal` API, which is nice.

**Comment by jquense** [comment]
I am also a bit torn about the verboseness of the simple case. The simple api we have now, I think, is too simple. It doesn't really allow for the level of flexibility a "building block" component like a panel should really have.

I agree that we definitely need to have a straightforward and simple case for accordions. The problem right now is that the Title component is the trigger for the collapse, which would be nested in a Header, so the Panel component would need to recurse through its children, vs just checking this.children. That's probably not a big deal since the depth is pretty shallow. Alternatively would could use context to wire it up in 0.14, which I think is a better idea.

**Comment by taion** [comment]
Yeah - the only change I'd make is maybe to do

```jsx
<Panel.Heading title>
  hello
</Panel.Heading
```

rather than explicitly specify the `Panel.Title` component, because I don't think we get a lot of mileage out of that.

**Comment by jquense** [comment]
My one concern with that is that doesn't help usecases like: https://github.com/react-bootstrap/react-bootstrap/issues/1118#issuecomment-128701044

where folks want to stick something next to the title. Certainly debatable whether its worth trying to attend to that case tho.

**Comment by taion** [comment]
Huh? Isn't everything there in the `<h4 class="panel-title">` thing?

**Comment by jquense** [comment]
I guess so, I was assuming that title was the anchor and header was the `H4` but I guess not :P. In either case isn't the problem that the anchor is the the thing that triggers the collapse, but that gets magically added and inserted into the header and the title is it's content (in that case)

**Comment by jquense** [comment]
tangential: adding a h4 tag regardless of context is semantically weird no?

**Comment by taion** [comment]
Yeah, I guess it is strange - not sure what the default tag we should use for titles should be. Maybe even just a non-semantic `div` unless the user specifies otherwise? Or does the `.panel-heading` styling only apply for header tags?

**Comment by ctaymor** [comment]
A few thoughts: 
First, using h4 is a real problem. For accessibility, h1-h6 are supposed to be used as a semantic outline of the page. For example, if the previous header on the page is an h2 and we're skipping to an h4, this is a big no-no. Since we don't know the structure of our user's page, we can't decide for them what level of heading to use.

The PivotalUI team discussed possible solutions, and we like Taion's proposed API, but would suggest a small simplification:

The prop heading takes a string or React Element. Title is a boolean flag which indicates whether to add  `.panel-title` (default is false). When the panel is collapsible, instead of putting the link inside of an h4, we could either apply `.panel-title` to the link itself or wrap it in a div with that class.
```
<Panel heading="foo" title>
  bar
</Panel>
```

**Comment by taion** [comment]
I think `h4` is a weird default as well. TWBS applies different styling to `div.panel-title` v `h{n}.panel_title`, though, which would make this a breaking change.

Is your preference to not have a separate `Panel.Heading`, `Panel.Body`, &c. elements that get nested in the `Panel`, then?

**Comment by ctaymor** [comment]
Yes, that would be my preference. It seems like a cleaner API to have header, and footer as props. Since it would be invalid to have more than one header or footer on a panel, it seems unnecessarily verbose to have them as elements instead of props.

I think getting rid of the h4 is an important breaking change to make, and we do have a new version coming up. In terms of the h4, maybe for deprecation, we can switch it to a div, and use the `.h4` bs class? Then we're not messing up the semantic heading levels, but looking at the less code on TWBS, it looks like it would maintain the same styling `h{n}.panel-title`.

**Comment by jquense** [comment]
hmm I think maybe we are making this too complicated. the title class really just exists to kill the h margins when someone wants to use a header tag inside the heading. I think the heading prop should just a node and a user can put whatever they want in it, including a h tag and the title class

**Comment by jquense** [comment]
which is to say there is no real semantic meaning to the title class it's just a reset of header margins.

**Comment by taion** [comment]
It changes the font size too. Don't know how many of our users are relying on that or even using the stock TWBS CSS though.

**Comment by vizjerai** [comment]
I could use the verbose syntax because I would like to have an onClick on the heading's container instead of the onSelect's behavior. This would allow the whole heading to be clickable instead of just the title.

```javascript
<Panel collapsible>
  <Panel.Heading onClick={this.onClickHeading}>
    <Panel.Title>hello</Panel.Title>
  </Panel.Heading>
  <Panel.Body>
    world
  </Panel.Body>
</Panel>
```

**Comment by dptoot** [comment]
(nudge) :)  Any movement on this guys?

**Comment by delenius** [comment]
I would also like a "more detailed" API that allows full flexibility in the use of panels. For instance, I like to put buttons on the right side inside the panel header. I also want to *not* put the panel content inside a panel-body, because it adds margins that I don't want. So a Panel.Body tag should be required for those who want that. So, one more vote for introducing Panel.Heading, Panel.Body, and Panel.Footer, and for *not* adding a panel-body when Panel.Body is not used.

**Comment by jquense** [comment]
Ok folks I'd like to try nd start on this one. Do we have any consensus on what the best approach is so far? For illustration here is the raw markup:

```html
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Panel title</h3>
  </div>
  <div class="panel-body">
    Panel content
  </div>
  <div class="panel-footer">Panel footer</div>
</div>
```

The title class literally just resets margins and font-size its sort of dumb, and has no structural value (expect that you can't do `.panel-header.panel-title`).

The most complicated choice (I think) is dealing with collapsible. What I gather from folks is that they like put stuff inside and outside the collapse trigger "title". We also can't arbitrarily wrap any Header elements, because don't know that they will be valid in an anchor. Maybe we go the route of navbar api? That's annoyingly verbose but may cause the least problems in the future. 

Tangentially the panel successor (cards) in tbs4 looks like its a lot more "modular" anyway so maybe  a more destructured api is better looking into the future?

**Comment by taion** [comment]
As part of this, we should update list group items as well. Something like:

```js
// http://getbootstrap.com/components/#list-group-basic
const basicListGroupItem = (
  <ListGroupItem>
    Cras justo odio
  </ListGroupItem>
);

// http://getbootstrap.com/components/#list-group-custom-content
const customListGroupItem = (
  <ListGroupItem>
    <ListGroupItem.Heading>
      List group item heading
    </ListGroupItem.Heading>
    <ListGroupItem.Text>
      Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.
    </ListGroupItem.Text>
  </ListGroupItem>
);

const moreCustomListGroupItem = (
  <ListGroupItem>
    <ListGroupItem.Heading>
      List group item heading
    </ListGroupItem.Heading>
    <WhateverComponent />
  </ListGroupItem>
);
```

Or perhaps `<ListGroup.Item>` instead of `<ListGroupItem>`.

**Comment by jquense** [comment]
looks good to me, ends up better to just be more verbose in these cases

**Comment by taion** [comment]
Do we have any other components with magical `header` or `heading` props?

**Comment by anbhole** [comment]
I think, wrapping header in anchor is not needed and is not documented either clearly. There is an expanded prop and people can manage it with the state. Why is the need to put default unconfigurable behavior in the component.

**Comment by taion** [comment]
Yes, that's why we're looking to change the API.

**Comment by timkendrick** [comment]
Did you guys end up settling on an API for panel headers?

I've been playing around with jquense's solution in #1769 and it seems perfect to me...

**Comment by Siyfion** [comment]
@taion Without sounding too demanding, where are we at with this? It's been nearly 2 YEARS since this issue was first raised and we're still stuck here with no solution. It's getting to the point that I'm thinking it'd be easier to stop using `react-bootstrap`!

**Comment by AWorldSoCole** [comment]
This past week I witnessed first hand how difficult it is to use Panels and ListGroupItems. Even the documentation seemed to be lacking useful information. An update on this would be amazing.

**Comment by jquense** [comment]
ya'll can feel free to jump into the PR and help out. I understand that it's frustrating to wait a long time for these things to go in, but it's OSS, and we work on and maintain this in our free time. 

Best way to get something moving is to contribute to it

**Comment by quocble** [comment]
I use this little CSS hack to make the entire header clickable:

      a {
        display:block;
        height: 100%;
        margin: -15px;
        padding: 15px;
      }

**Comment by Billy-** [comment]
Worth mentioning that passing anything other than a string into the header prop on a `<Panel>` inside an `<Accordion>` breaks the accordion functionality - it replaces the `<a>` (which as mentioned above is possibly not a necessary element anyway).

**Comment by damianfabian** [comment]
I just found this project and want to tell one opinion. As a new user of the library I would like to have an easy way to achieve all the posible situations. I guess the idea of create a panel.title is good if you want to save some time, but this situation is one in 99 situations, in my opinion. If the api just let you put anything in the panel.heading, it will be more easy for me and you don't limit the possibilities for the users. In that case the user will decide if they use h4,h6 or an image. 

`<Panel collapsible>
  <Panel.Heading onClick={this.onClickHeading}>
    <h4>hello</h4>
  </Panel.Heading>
  <Panel.Body>
    world
  </Panel.Body>
</Panel>`

`<Panel collapsible>
  <Panel.Heading onClick={this.onClickHeading}>
    hello
  </Panel.Heading> // In this case I guess the result should be an string, pre-define an h4 does not have any sense
  <Panel.Body>
    world
  </Panel.Body>
</Panel>`

**Comment by xAKLx** [comment]
If the panel-title class use case is when the developer wants to use h1-h6 headings, the API should provide a way to choose only those elements. Some ways to do it:
`
<Panel>
    <Panel.Title.h1> title </Panel.Title.h1>
</Panel>`

`
<Panel>
    <Panel.Title size="h1"> title </Panel.Title>
</Panel>`

`
<Panel h1Title="title">
</Panel>`

But just ignoring the header attribute would be wrong, as the developer won't understand why the attribute is not affecting the result without reading the API.

**Comment by alexandresebrao** [comment]
Im having problems when trying to use a <a> inside the panelheader when it's collapsible, any thoughts on what can I do to fix this, ps: the link is required to be there so removing the link from there is not gonna work for me.
